### ISSUE TITLE
Enabling usage of SDK with earlier versions that Community 4.2 / Enterprise 4.1.2

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#110]
_From [colum...@gmail.com](https://code.google.com/u/100251676538566683892/) on January 24, 2013 12:54:05_

Currently whenever someone wants to build an AMP using the new SDK, he needs to add src/main/amp/module.properties.

This triggers the activation, in the sdk-parent POM, of the profile "enable-amp": this profile configures the alfresco-maven-plugin (correct) but also configures support for AMP unit testing (incorrect incapsulation).

The problem with this is that for AMP unit testing data-model:config:jar and repository:config:jar are required and are resolved by the build, also if the user wants ONLY to build the AMP, not specifically when a test goal is called. 

Since the "config" JARs are only available as of Alfresco 4.2 Community and 4.1.2 Enteprise, what this basically causes is that the 1.0 SDK version can NOT be used with earlier Alfresco versions, even for simple AMP packaging (with no testing).

Since unit testing is an advanced feature (which could be restricted to Alfresco 4.2+ Community and Alfresco 4.1.2+ Enterprise), while AMP packaging is a basic feature which we want as many users as possible to have available, my suggestion is:
- separate "enable-amp" from a new profile called "enable-amp-testing"
- "enable-amp" simply defines support for AMP packaging, and it's activated automatically with the module.properties file presence
- "enable-amp-testing" adds support for unit testing (so dependency on the config" JARs) and it's either activated manually (or we need to find a smart way of activating it). 
- Document that "enable-amp-testing" is available only in later versions, while AMP packaging _should_ work also with earlier versions.

WDYT?

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=110_

**Comment by jgoldhammer** [comment]
Due to the age of this issue, I will close the ticket. The interest of supporting older versions than Alfresco 4.2 should be very low in my point of view. If anybody feels, the SDK should support older versions, please create a new ticket with specific requirements.
