### ISSUE TITLE
Add automatic release notes generation upon release

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#111]
_From [colum...@gmail.com](https://code.google.com/u/100251676538566683892/) on January 24, 2013 15:06:27_

Configure the maven-changes-plugin to read issues from google code.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=111_

**Comment by mindthegab** [comment]
Release notes were autogenerated for 2.1.0 here https://artifacts.alfresco.com/nexus/content/repositories/alfresco-docs/alfresco-sdk-aggregator/latest/github-report.html

But we are also showing Open issues, need fixing.

**Comment by ohej** [comment]
Github report configured to exclude open issues
