### ISSUE TITLE
Provide a quick start (fast track)

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#117]
_From [gethin.j...@alfresco.com](https://code.google.com/u/107370465778594406461/) on March 05, 2013 07:11:32_

I've recently been recommending this project.  There's lots of documentation but I want to send someone a link with a one page quickstart and/or youtube video.

The quickstart would assume maven knowledge and would answer the question: "How do I get started developing against Alfresco 4.1.x? ".

It would show :
1. Which artifact to use
2. The project structure
3. How to start up an Alfresco embedded instance and write code against it.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=117_

**Comment by ohej** [comment]
We're completely rewriting the official docs on the SDK and doing a video tutorial once 2.1.0 is released. Assigning to myself to follow up once it's done.

**Comment by jgoldhammer** [comment]
@ohej 
Can you please send me your thoughts on this? Do you have anything, so that we can close the ticket?

Thx,
Jens

**Comment by ohej** [comment]
We did a nice redo of the docs a long time ago and we will have new docs and tutorials for SDK3 so I will close this one
