### ISSUE TITLE
Spring Context files not reloaded in "rad" mode

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#158]
_From [g.vanheu...@aca-it.be](https://code.google.com/u/106905735075060774234/) on November 26, 2013 07:03:05_

What steps will reproduce the problem? 1. Create a new alfresco amp module using the Alfresco Maven SDK 1.1.1
2. Import the project into Intellij and configure JRebel
3. Set the JAVA_OPTS an MAVEN_OPTS
3. Build and run the project using the rad and amp-to-war profile
4. Add a new bean to service-context.xml What is the expected output? What do you see instead? - The newly created bean should be loaded What version of the product are you using? On what operating system? - Alfresco Maven SDK 1.1.1, OSX, Intellij 12, JRebel 5.4.1

The generated rebel.xml file does not add "scr/main/amp/config" to the classpath.
I have overridden the "rad" profile and added the above path so the rebel.xml file contains the extra location to monitor. The "import" statement in module-context.xml should be updated as well because it uses the maven placeholders to point to the service-context.xml file. I just replaced the placeholder with the module string. After those changes I can update the module-context.xml file and JRebel detects those modifications! 
Unfortunately, JRebel doesn't monitor the service-context.xml file... Not sure if it is a configuration error or a problem with the import statement.

Do you think it is possible to provide the creation of new WebScripts as well if the Spring context reloading works?

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=158_

**Comment by ohej** [comment]
With SDK3 we have brought back JRebel which supports bean reloading and it supports reloading beans in XML definitions. Closing
