### ISSUE TITLE
Maven SDK 1.1.1 with junit-remote runs tests multiple times

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#165]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 02, 2013 08:27:50_

What steps will reproduce the problem? 1. Create a new project with the Alfresco Maven SDK version 1.1.1
2. Create at least 2 test classes with the @org.junit.runner.RunWith(com.tradeshift.test.remote.RemoteTestRunner.class) annotation.
3. Print out a statement in both tests. What is the expected output? What do you see instead? You will see that the all tests (except the first one) run several times. I expect every test to run only once. What version of the product are you using? On what operating system? Maven SDK 1.1.1 on OSX with Maven 3.1.1

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=165_

**Comment by ohej** [comment]
Given the age of this issue and the fact that SDK3 has a brand new way of doing integration tests I will close this issue
