### ISSUE TITLE
Maven SDK 1.1.1 does not copy module.properties to test classpath

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#166]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 02, 2013 10:20:00_

What steps will reproduce the problem? 1. Create a project with Maven SDK version 1.1.1.
2. Run the mvn clean install command.
3. Notice that the Alfresco context does not detect any module. What is the expected output? What do you see instead? I expect that the Alfresco context finds 1 module to install (this was the case in the SDK version 1.0.2). Otherwise custom components (e.g. for generating data at bootstrap) will not be able to be loaded. What version of the product are you using? On what operating system? Maven SDK 1.1.1 on OSX with Maven 3.1.1. Please provide any additional information below. Adding the following to my pom.xml is a temporary workaround (but it should be added to the SDK itself):

```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-resources-plugin</artifactId>

            <executions>
                <execution>
                    <id>prepare-amp-testing-classpath</id>

                    <configuration>
                        <outputDirectory>${project.build.testOutputDirectory}</outputDirectory>

                        <resources>
                            <resource>
                                <directory>${app.amp.folder}</directory>
                                <includes><include>module.properties</include></includes>
                                <targetPath>alfresco/module/${project.artifactId}</targetPath>
                                <filtering>${app.filtering.enabled}</filtering>
                            </resource>
                        </resources>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=166_

**Comment by jgoldhammer** [comment]
Due to the age of this issue, I will close the ticket. The ticket deals with an unsupported Alfresco SDK version. A workaround is provided. If somebody wants to provide input to this error, please reopen the ticket.
