### ISSUE TITLE
Maven SDK 1.1.1: deployedSpace.xml not found

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#167]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 02, 2013 10:23:42_

What steps will reproduce the problem? 1. Create a clean project with the Maven SDK 1.1.1.
2. Run your tests with the mvn clean install command
3. The build will fail saying that not all patches could be applied. What is the expected output? What do you see instead? The build should run out of the box, but it cannot find a file called deployedSpace.xml in the alfresco/bootstrap folder. Adding this file to the resources folder is a temporary workaround. What version of the product are you using? On what operating system? Maven SDK 1.1.1 on OSX with Maven 3.1.1 and Alfresco 4.2.e.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=167_

**Comment by jgoldhammer** [comment]
Does not relates to new Alfresco 5.x versions, so we can close the ticket now.
