### ISSUE TITLE
The AlfrescoPerson does not work in Maven SDK 1.1.1

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#168]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 02, 2013 10:30:31_

What steps will reproduce the problem? 1. Create a fresh project with the Maven SDK 1.1.1
2. Create a test using the AlfrescoPerson rule to create a temporary user
3. The test will fail, because it cannot find the bean "testUserComponent". What is the expected output? What do you see instead? The rule should still work (just like in Maven SDK version 1.0.2), but it complains about the bean that cannot be found. What version of the product are you using? On what operating system? Maven SDK 1.1.1. on OSX with Maven 3.1.1 and Alfresco 4.2.e. Please provide any additional information below. The bean is defined in the file "community-integration-test-context.xml". I added it to my resources and referenced it in the @ContextConfiguration annotation to work around this problem. However this should work out of the box.

I also noticed that it is difficult to make it work out of the box, because it is hard getting to the application context before the JUnit rule is initialised. To fix it:
- My test implements ApplicationContextAware
- I have a custom ApplicationContextInit class which has a setter for the ApplicationContext and a simple getter. I instantiate it as a private variable on my test class.
- I pass the ApplicationContext within my test in the setApplicationContext method provided by the ApplicationContextAware interface
- I am then able to pass the ApplicationContextInit instance to the AlfrescoPerson rule.

This is also necessary to be able to use the TemporaryNodes rule. I feel that it shouldn't be so hard trying to make the default test utility classes to work.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=168_

**Comment by ohej** [comment]
Hi Marco

Does this issue still happen with 2.0.0 / 2.1.0? It seems the dependency is added, but the issue was never closed. Could you verify and close the issue if it's fixed?

/Ole

**Comment by jgoldhammer** [comment]
In SDK 3, this dependency does not exists anymore.
So in SDK3 we have no generated unit-tests running.
@gravitonian and @ohej : what is the current state of testing with SDK 3?

**Comment by ohej** [comment]
Given the age of this issue I will close it. Feel free to reopen if this is still a valid issue with SDK3

**Comment by tmetten** [comment]
This is still a valid issue in SDK 3 (alfresco-platform version 5.0.3).
Defining the following dependency solves the issue:
`

    <dependency>
        <groupId>${alfresco.groupId}</groupId>
        <artifactId>alfresco-repository</artifactId>
        <version>${alfresco.platform.version}</version>
        <classifier>tests</classifier>
        <scope>test</scope>
    </dependency>

`
