### ISSUE TITLE
Multiple JUnit remote test with different @ContextConfiguration fail

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#169]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 10, 2013 07:46:33_

What steps will reproduce the problem? 1. Create a new Maven SDK 1.1.1 AMP archetype project
2. Create a dummy Spring context file in your test resources
3. Copy the DemoComponentTest and add the dummy Spring context file to the @ContextConfiguration. Do not do this in the original test. What is the expected output? What do you see instead? I expect that the tests run, however when the second test runs we get the error "Could not start JUnit remoteServer" a lot. The build will then fail. What version of the product are you using? On what operating system? Maven SDK 1.1.1 AMP archetype with Mac OS X and Alfresco 4.2.e.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=169_

**Comment by asborisov** [comment]
Problem is still existing.

**Comment by ohej** [comment]
SDK3 solves this
