### ISSUE TITLE
No logging regarding Spring context initialisation in Maven SDK 1.1.1 All In One archetype

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#170]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 10, 2013 08:16:53_

What steps will reproduce the problem? 1. Create a new project with the Maven SDK 1.1.1 All In One archetype
2. Add the JUnit dependency to the "amp" project and add a test to that project cfr. to the test in the AMP archetype
3. Run the build for the "amp" project (mvn clean install) What is the expected output? What do you see instead? I expect to see logging from the Alfresco Spring context bootstrap and from my test (just like when using the AMP archetype). Unfortunatly I do not see any output. So it is almost impossible to pinpoint problems with your code. What version of the product are you using? On what operating system? Maven SDK 1.1.1 with Alfresco 4.2.e on Mac OS X

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=170_

**Comment by jgoldhammer** [comment]
I will close the ticket now. Log4j.property files are integrated into each archetype, so the ticket should be solved.
