### ISSUE TITLE
Property alfresco.data.location should be configurable to be an absolute path.

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#171]
_From [m.swe...@aca-it.be](https://code.google.com/u/103056205031204277679/) on December 11, 2013 05:04:10_

The property "alfresco.data.location" is configured as a relative path today. By default this is "alf_data_dev". We would like to configure this as an absolute path (e.g. "${project.basedir}/alf_data_dev}"), but this is not possible at the moment.

This is caused by 2 flaws in the alfresco-sdk-parent-1.1.1.pom:

• The property "alfresco.db.url" is configured with the prefix "./", which prevents us to specify our absolute path in the "alfresco.data.location" property.

• The configuration of the "purge" profile configures "${project.basedir}/${alfresco.data.location}" to be purged. So no other absolute path is possible. What version of the product are you using? On what operating system? Maven SDK 1.1.1 Please provide any additional information below. I propose to remove the "./" prefix from the "alfresco.db.url" property and remove the "${project.basedir}/" prefix from the "purge" profile.
We should then set the default "alfresco.data.location" value to "${project.basedir}/alf_data_dev".

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=171_

**Comment by jgoldhammer** [comment]
The data location is now set to         <alfresco.data.location>${session.executionRootDirectory}/alf_data_dev</alfresco.data.location>

And there is no purge profile anymore.
So I will close the ticket for now.
