### ISSUE TITLE
Extensions folder proposal

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#177]
_From [javierca...@gmail.com](https://code.google.com/u/100514874968015755095/) on February 04, 2014 05:05:17_

What steps will reproduce the problem? 1. Create new AMP Maven project from alfresco-amp-archetype What is the expected output? What do you see instead? It would be great to have a boolean property when creating a project using the artifact like "createExtensionFolder" that creates the extensions folder structure: 

for example:

/config/alfresco/extension/model
/config/alfresco/extension/templates/
/config/alfresco/extension/templates/webscripts What version of the product are you using? On what operating system? alfresco-amp-archetype v1.1.1 Please provide any additional information below.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=177_

**Comment by jgoldhammer** [comment]
These folders are contained in newer generated repo projects. So I will close the ticket now.
