### ISSUE TITLE
maven sdk  + mmt : Warning reported when runnin alfresco amp

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#183]
_From [alexis.t...@gmail.com](https://code.google.com/u/102853092632226139085/) on April 08, 2014 08:53:08_
## When running  an amp (mvn install -Pamp-to-war) in all-in-one project type, mmt report some warning :

[INFO] --- alfresco-maven-plugin:1.1.1:install (amps-to-war-overlay) @ my-amp ---
##    - WARNING: The file '/WEB-INF/classes/alfresco/module/mymodule-amp/context/a-service-context.xml' is being overwritten by this module. The original has been backed-up to '/WEB-INF/classes/alfresco/module/backup/342f3273-bf1a-11e3-8690-49e0d19a4f9a.bin'

In fact, before alfresco-maven-plugin execution , maven resource plugin do a copy of amp files into target warfolder :

 <execution>
            <id>copy-alfresco-test-resources</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>/home/altha/Projets/Alfresco-Panier/sources/my/my-amp/target/my-amp-war</outputDirectory>

Then mmt override the files, and log WARNING for each file.

Ok, it's just a Warning, but at first, before investigating, you can think it's an issue.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=183_

**Comment by jgoldhammer** [comment]
I will close the ticket now. I have not seen any similar warning in newer idk-versions...
