### ISSUE TITLE
module.version values for SNAPSHOT project versions don't respect MMT's version order requirements

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#184]
_From [peter.mo...@alfresco.com](https://code.google.com/u/110332035736028049406/) on May 21, 2014 13:49:56_

When constructing an AMP from a SNAPSHOT version of a project, the alfresco-maven-plugin replaces the -SNAPSHOT suffix with an auto-generated timestamp (since MMT doesn't support non-numeric version numbers - see https://issues.alfresco.com/jira/browse/ENH-1232 for more details on this bug in MMT).  So for example, a project version of 1.1.0-SNAPSHOT might result in a module version of 1.1.0.1405201742 (or similar - the final version number component varies as its an auto-generated timestamp).

When the developer is preparing a non-snapshot build, they will remove the -SNAPSHOT suffix from the project version, and the alfresco-maven-plugin will no longer append a timestamp.  So for example, a project version of 1.1.0 results in a module version of 1.1.0 (no change).

The problem comes about when that non-SNAPSHOT build is deployed to a server that already has the SNAPSHOT build installed.  By default, MMT will block installation of an AMP that has a numerically lower version (reading left to right) version than the currently installed version.

Using the examples above, we can see that the SNAPSHOT build has a module version of 1.1.0.1405201742, but the released version (which is, in fact, newer) has a module version of 1.1.0, which MMT considers to be older (1.1.0 is numerically less than 1.1.0.1405201742, reading the digits left to right).

A solution must ensure that the numerical ordering requirement of the current shipping versions of MMT are met, across both SNAPSHOT and non-SNAPSHOT project versions.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=184_

**Comment by pmonks** [comment]
Looks like this bug is starting to come home to roost: https://issues.alfresco.com/jira/browse/ACE-5006 ...

**Comment by gravitonian** [comment]
Fixed
