### ISSUE TITLE
Integrated Alfresco Technical Validation tool in the SDK 'verify' phase

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#188]
_From [gabriele...@alfresco.com](https://code.google.com/u/110568675915341555904/) on June 10, 2014 08:33:04_

In order to ensure the development of best practice driven extensions and to avoid unsupportable developments we want to integrate the ATV in the SDK.

This is blocked on https://github.com/AlfrescoLabs/technical-validation/issues/33 (i.e. having a Java API for the ATV).

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=188_

**Comment by ohej** [comment]
Not much progress has been made on the ATV tool. I will close this issue and open a new one if we go back and revisit the tool
