### ISSUE TITLE
Remove (find a better way to manage)  unit tests / sample classes from amp archetype

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#191]
_From [colum...@gmail.com](https://code.google.com/u/100251676538566683892/) on June 16, 2014 12:28:33_

After creating the archetype once, having to remove unit tests and sample classes can become tedious and error prone for Alfresco expert developers.

We need to:
- either remove unit tests and provide a separate sample / archetype
- or make the archetype parametric / configurable at creation timme

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=191_

**Comment by jgoldhammer** [comment]
@binduwavell , @gravitonian and @ohej : what are your thoughts here?
IMHO, an working example is not bad from my perspective, but I don´t think that archetype can be configured to leave classes, right?

**Comment by ohej** [comment]
All in one still contains tests, but we have removed tests from the JAR archetypes. The "infrastructure" is still in place, but the test classes are still there.

We do however still include a sample content model, web script, workflow and other demo content. I feel strongly that we keep this as it really gives a great starting point for new developers.
