### ISSUE TITLE
Improving the overall "out-of-the-box" experience 

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-sdk#199]
@mindthegab mentioned we should focus on having the best possible "out-of-the-box" experience with the SDK.

Right now I'm trying to gather the most asked questions/issues from IRC and the forums, this should give us some idea about the areas that could be improved.

We can probably not expect to fix these issues within the SDK, but rather improving the documentation, adding howto's, guides etc.

Please feel free to add the problems you've encountered or tried to help/answer the most.
- Where can I put jar files (that are not available as artifacts, I just have them as compiled versions)?
- How can I setup my Maven AMP project in Eclipse?
- I get this error when running "mvn integration-test -Pamp-to-war": "Non-resolvable parent POM… Non-resolvable parent POM"
- Anyone tried building a jar from alfresco amp maven archetype?
- How can I overwrite web.xml in alfresco/share.war using Alfresco Maven SDK?
- How can I download the sources/javadoc when using the SDK?

Overall areas/observations:
- Setting up debugging (both from Eclipse/IntelliJ IDEA)
- Confusion if Share extensions should be packaged as JAR or AMP. There's a lot of blogs/examples (even on the alfresco blogs) where code is being shipped off as jars
- I still see a lot of people thinking the way to go is to checkout the community code in Eclipse and launch it up against a tomcat..

**Comment by mischkl** [comment]
The biggest issue we have had, not as newcomers per se, but nonetheless as part of the "out of box" experience, is the lack of a solid/supported hot-swapping solution for Java development. Before we switched to Java 8 we were using spring-loaded, but it chokes on Java 8 code like lambdas and its development seems to have completely stalled. And while it's awesome and essential that JRebel support is being worked on, there are plenty of organizations that aren't ready to pay for JRebel and/or prefer an open-source solution.

We have had decent success with [HotSwap Agent](http://hotswapagent.org) in combination with DCEVM, although it could be a lot better, as there is no support for hot-reloading in XML-based Spring contexts. There is in fact a plugin for Spring, but it doesn't grok the XML context definitions - so we have to manually specifying search paths where it should look for file changes, and completely restart the instance if anything within the context XMLs changes, which is a pain.

None of the current options for hot-reloading are ideal. Java development without hot-reloading is pure masochism, JRebel has too steep a price especially for users of Community, and forcing users to hack together a custom HotSwap Agent setup is exactly the kind of thing the SDK is supposed to avoid. If Alfresco were to commit to officially supporting a project like HotSwap Agent it would help a lot with replacing the now-defunct spring-loaded.

**Comment by ohej** [comment]
@mischkl, SDK3 offers support for Hotswap agent with a sensible default hotswap agent that picks up the essential changes. 

I do agree that hot reloading is an essential feature, but we are bound by the constraints of 3rd party tooling for this. Spring Loaded doesn't seem to be a viable option anymore. JRebel provides a superb hot reloading experience, but comes with a price tag. Hotswap agent does the basics with the exception of reloading beans. Hotswap agent does have a neat plugin structure so this could be possible in the future.

Overall I think the SDK3 offers a much better out of the box experience. I will close this issue and we can open new issues for individual improvements once the release is out.

**Comment by mischkl** [comment]
That's awesome news!! Thanks for all the hard work in getting Hotswap agent integrated into the SDK!
