### ISSUE TITLE
Use webscript for Integration Tests rather than embedded Jetty

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#203]
We (Zia Consulting) have been asked to contribute the integration testing framework we developed for our zia-alfresco-quickstart project. This framework uses a webscript to execute integration tests in the repo rather than the embedded Jetty instance that the archetypes use. 

Our runner detects if it is being run in a repo. If so it runs the tests regularly, if not it calls the webscript to run the tests in the repo. The webscript serializes the results of running the test in xml and returns them to the proxied runner (in IDE or maven command line for example.) The proxied runner then deserializes the xml and behaves as if it had whatever results were produced inside the repository.

Our contribution also includes a shell (not implemented) for a second webscript that would list any tests annotated with our runner and allow for the tests to be run interactively via a browser. Once we get the original stuff integrated, would be super cool to fill this webscript out. 

I will figure out how to attach the zip file with the contribution.

**Comment by mindthegab** [comment]
@binduwavell @ohej Can we review if the PR is still valid (and so merge) or we need to ask @binduwavell to regenerate one?

I really would like this in the next major / minor.

**Comment by binduwavell** [comment]
Ole made a bunch of progress on merging this just prior to starting the new position. I'd hate to lose all that work. Ole, do you have a fork or branch somewhere that we can collaborate on?

**Comment by ohej** [comment]
We have essentially accepted this pull request, however we didn't merge but did a manual implementation of it as the SDK3 has a slight different structure. I will close the issue and the PR. Thanks for the contribution @binduwavell!
