### ISSUE TITLE
Make sure that content models on the classpath can be dynamically reloaded with the 2.0 SDK

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#204]
We discussed this a bit during TTL 79

**Comment by mindthegab** [comment]
Could we just bootstrap the models in Data Dictionary at development time? Also, thinking about CMM functionalities do we still need this (considering there would a UI for doing that)?

**Comment by binduwavell** [comment]
While I don't know how property groups will work. I strongly suspect we will still want class path based models and associated reloading for security, consistency and possibly performance reasons. Has been a while since I looked at this, so is possible the performance comment is an overstatement ;)

**Comment by jgoldhammer** [comment]
@binduwavell :
Do you have any feedback for me here? It is currently possible? I don´t think so...

**Comment by ohej** [comment]
Without changes to the core of ACS I don't think this can be achieved. https://issues.alfresco.com/jira/browse/ALF-21064 as closed so I don't think this will done. I'm going to close the issue.
