### ISSUE TITLE
Lucene no longer available in 5.0.b

### ISSUE THREAD

**Issue by loftux** [Alfresco/alfresco-sdk#228]
Lucene as indexer has been removed from 5.0.b.
repo-amp project therefor need updating to use either noindex in alfresco-global.properties
or
Add a solr4-amp/solr4-run project that can be used to run the indexer separately.
or
Scrap the amp project support and only support allinone. But that would be unfortunate because it is quite "heavy" to run.

**Comment by gravitonian** [comment]
Fixed: see https://issues.alfresco.com/jira/browse/DEVPLAT-4
