### ISSUE TITLE
Support for alfresco-solr4 project (replaces alfresco-solr)

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#231]
Alfresco 5.0.b and 5.0.0 will use Solr4 by default.

We need to upgrade our support knowing that:
- default solr4 https://artifacts.alfresco.com/nexus/#nexus-search;gav~org.alfresco~alfresco-solr4~~~ comes with http only configugation
- there are 'ssl' and 'config-ssl' classified artifacts to run with ssl enabled (https://artifacts.alfresco.com/nexus/#nexus-search;gav~org.alfresco~alfresco-solr4~~~config-ssl)

**Comment by gravitonian** [comment]
Fixed: see https://issues.alfresco.com/jira/browse/DEVPLAT-4
