### ISSUE TITLE
maven keystorefile,keystorePass, truststoreFile,truststorePass properties are not passed through

### ISSUE THREAD

**Issue by hagak** [Alfresco/alfresco-sdk#239]
When trying to configure the keystore and truststore with an AMP build the properties do not seemed to be passed through to the tomcat plugin from the parent SDK plugin.

Note maven.tomcat.port does seem to work as expected however the others do not.
http://tomcat.apache.org/maven-plugin-2.2/tomcat7-maven-plugin/run-mojo.html

**Comment by ohej** [comment]
Could you give a bit more info on your setup? Are you using all-in-one or the AMP archetype? 

With 2.1.0 I have no issue overriding maven.tomcat.port, so I'm not sure what is going on. Are you overriding them all via command line or the pom?

We are working on adding a section to the documentation of 2.1.0 on how to configure SSL, let me know if you want to review it.

**Comment by hagak** [comment]
We are using the AMP archetype.  We have no issues setting maven.tomcat.port via the POM.  We are having issues setting other tomcat configs via the POM such as the keystore, keystorePass, truststoreFile, truststorePass.

I would like to review that documentation.  Thank you

Jeffrey Gordon
Progeny Systems
Software Engineer
jgordon@progeny.net<mailto:jgordon@progeny.net>
703.368.6107 x493

**Comment by ohej** [comment]
I've sent you an email with directions, please let me know how it works out

**Comment by mindthegab** [comment]
@ohej @hagak Did this work? can we close this?

**Comment by hagak** [comment]
This did not resolve the issue in SDK 1.2 however we are moving to SDK 2.0 so this may no longer be an issue for us.  (Not moving to 2.1 until it support Java 1.7)

**Comment by mindthegab** [comment]
Yeah we are releasing SDK 2.1.1 soon with Java 7 support. I'll close this for now.
