### ISSUE TITLE
Consider adding some documentation on how to get more out of the SDK

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#246]
Samuel mentioned on the Alfresco SDK devs channel that thumbnails were not building and Ole pointed out that he uses the installer to put those bits on his machine and copies relevant alf-global.props into his dev environment.

This is something I've seen folks ask about several times. Specifically when we spin up Alfresco via any of the maven archetypes there are pieces of the system that are missing or don't work as they would if you had used a more traditional installation method.

Our docs should probably include a page on going further with the SDK. That talks about how to plug in imagemagic and libreoffice. Other things folks might want to do is integrate SOLR with the amp archetypes. In the past some of the Activiti stuff has not worked natively with the archetypes and needs some extra setup, not sure if that's still true.

Gab pointed to the following: http://docs.alfresco.com/5.0/concepts/alfresco-sdk-tutorials-mysql-intro.html that covers how to move away from using h2, which is exactly the sort of thing I think we should be documenting.

**Comment by ohej** [comment]
Hi Bindu and Peter

I realise this is an older issue, but with 2.1.0 we made some new great docs and we have an "Advanced Topics" that covers a lot. 

Apart from testing, what other topics should we cover? I'm hoping we can do some brainstorming and open specific issues around each topic and close this one so it doesn't go on for ever ;)

/Ole

**Comment by binduwavell** [comment]
I think the new docs are great. Although certain tasks that are documented
are way harder than they should be. Like upgrading SDK version. Adding a
dependent AMP, etc.. So other than testing, I think we should focus on
improving these sorts of use cases so that we either don't need docs, or
the docs are do this 1 thing, bam, you are done! ;)

**Comment by mindthegab** [comment]
@ohej @binduwavell @gravitonian Can you review and agree on what's needed here?

**Comment by binduwavell** [comment]
I have provided several concrete examples on this thread already. 

Ole, wanna ping me on Skype next week and we can brainstorm?

**Comment by ohej** [comment]
With SDK 3.0 we improved the documentation, covering a lot of the topic listed on this issue. With SDK 4.x we also have new tutorials on debugging and much more. I will close this issue, please raise individual issues for any missing or nice-to-have topics.
