### ISSUE TITLE
Consider adding some documentation related to testing with the archetypes

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#247]
We should probably have a page on how to write and run unit and integration tests that accounts for the differences between the amp (repo and share) and AIO archetypes. 

How these tests can be triggered from the command line, from Eclipse and from a CI environment.

**Comment by jgoldhammer** [comment]
Hi @binduwavell , do you think this is already addressed by http://docs.alfresco.com/5.1/concepts/dev-for-developers.html ? Or can you specify more in detail?
