### ISSUE TITLE
Replace hardcoded profile activation strings with ${} properties

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#249]
I tested and works with Maven 3.2.5 (not with 3.2.2).

This would entail:
- Updating all file based profile activation to use say ${app.amp.folder} instead of src/main/amp, for each hardcoded activation
- Upping <prerequisites> to Maven 3.2.5
- Change Mvn version in CI server
- retesting :)

**Comment by jgoldhammer** [comment]
@mindthegab : I know you no longer are working for Alfresco, but maybe you can give us more information.

Thanks
Jens

**Comment by ohej** [comment]
We don't have any file based activations, or even any profiles anymore in SDK3 ;) Closing
