### ISSUE TITLE
Error filtering resources: Mark invalid

### ISSUE THREAD

**Issue by ceeliro** [Alfresco/alfresco-sdk#254]
[INFO] Copying 10 resources to ../share-amp
...
[DEBUG] filtering /home/ceeliro/ICMR/workspace_wks_p1/test-alf-all-in-one/share-amp/src/main/amp/web/js/example/widgets/css/TemplateWidget.css to /home/ceeliro/ICMR/workspace_wks_p1/test-alf-all-in-one/share-amp/target/classes/../share-amp/web/js/example/widgets/css/TemplateWidget.css
...
Caused by: java.io.IOException: Mark invalid
	at java.io.BufferedReader.reset(BufferedReader.java:505)
	at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:416)
	at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:205)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:181)
	at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:168)
	at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1856)
	at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1804)
	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:114)

**Comment by ceeliro** [comment]
I modified the out of the box TemplateWidget.css file, in a completely new all-in-one archetype project, to add this line at the beginning

"@media (max-width: 768px) {...}"

This error also happens to me with many other files after upgrading the all-in-one archetype project that i am currently working with from SDK 2.0.0-beta4 to 2.0.0

**Comment by ModestasM** [comment]
I have this problem too with alfresco sdk version 2.0.0
The problem can reproduced with fabric.js file taken from: http://fabricjs.com/

**Comment by ceeliro** [comment]
No clue in this regard? I have to skip filtering more of the files to be able to run the project (mostly min.js, js and css)

Thanks in advance

**Comment by ModestasM** [comment]
this helped me

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>js</nonFilteredFileExtension>
                        <nonFilteredFileExtension>css</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by ceeliro** [comment]
sure, thanks. I wanted to know if it is a known bug, if they are going to deal with it for further releases or so.  But never answered :( 

Thanks for the reply

**Comment by douglascrp** [comment]
I usually include ico on that list.

Em Fri Feb 13 2015 at 7:37:56 AM, ceeliro <notifications@github.com>
escreveu:

**Comment by kmezyaoui** [comment]
Hi,
Another file extension should be added to the list of ignored filter extensions (used in themes):

<nonFilteredFileExtension>psd</nonFilteredFileExtension>

regards.

**Comment by mindthegab** [comment]
Added js, ico and psd to nonFilteredExtensions

**Comment by jrosler** [comment]
Is there some reason that I shouldn't just turn off filtering in the runner/pom.xml file? I've got various files that are added and overwritten in the web directory. Adding nonFilteredExtensions for every new extension seems like a bad way to solve the problem. It seems like <filtering>false</filtering> in the maven-resources-plugin might be better. Why is this here in the first place?

**Comment by mrgrechkinn** [comment]
mindthegab commented "Added js, ico and psd to nonFilteredExtensions"

I do not see where you have added js to nonFilteredExtension

**Comment by ohej** [comment]
I see that we missed JS to the list. I've just committed it for 2.2, reopening and closing with the correct milestone so it shows up in the GitHub report when we release
