### ISSUE TITLE
2.0.0 SDK Repo AMP archetype is not filtering resources (like module.properties)

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#256]
Run: mvn archetype:generate -Dfilter=org.alfresco.maven.archetype:
Select repo-amp and fill in defaults
cd into project
Run: mvn clean package -DskipTests
go unzip the amp from the target directory
module.properties will include raw ${references} rather than filtered values

**Comment by mindthegab** [comment]
I can't reproduce this locally.

I'm using this stack:

Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T12:29:23-05:00)
Maven home: /Users/gabrielecolumbro/Software/Tools/apache-maven-3.2.5
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

With  Maven downloaded from official repo, as per docs.

**Comment by mindthegab** [comment]
This was an issue with running the SDK with 2.2.1 (min version 3.2.5, as per http://docs.alfresco.com/5.0/tasks/alfresco-sdk-install-maven.html), but this issue revealed https://github.com/Alfresco/alfresco-sdk/issues/257 so we'll continue work there to enforce the proper Maven version is used.
