### ISSUE TITLE
Add OS specific scripts to each module for running independently.

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#260]
Specially for the all-in-one archetype.

**Comment by dedunumax** [comment]
This is really important. All-in-one module we cannot run Repository or Share separately. Even though we are doing a tiny change to the Share we have to restart alfresco and share both.

**Comment by gravitonian** [comment]
Hi,

What changes to Share are you doing that requires restart?

**Comment by dedunumax** [comment]
Hi @gravitonian 

I didn't get your question.

**Comment by gravitonian** [comment]
Hi,

I was just wondering what customization you are doing to the Share Web App and what part of the customization that requires a restart of Tomcat.

Currently you cannot use the all-in-one project for running alfresco.war and share.war separately.

**Comment by ohej** [comment]
With all the effort of hot reloading going into the SDK we are hoping All-in-one will be the default adoption for developers. With the 2.1.0 release, we're in a much better shape than we were in 2.0.

With that being said, we do recognise that hot reloading is not perfect and you still have to bounce the server from time to time. 

You have two options:

1. Use the AMP archetypes, have one for repo, one for share and run them separately. The Share AMP archetype is by default configured to run on port 8081

2. Split all-in-one up into two projects. One with repo, repo-amp, runner and solr-config, one with share, share-amp and runner. Change the ports and you're good to go

Remember that the archetypes are suggestions on what your project layout could look like. If the AMP archetypes doesn't cover your needs and you need to run Repo and Share in separate instances, then split all-in-one up.

For all-in-one to support this natively we'd have to look into forking the processes which we'd rather not do for now. The focus right now is to get hot reloading to a state where the restarts are not even needed at all. 

I have raised https://issues.alfresco.com/jira/browse/DEVPLAT-105 to get the process into the official docs and closing the issue.
