### ISSUE TITLE
Image corrupted when I try to override the favicon.ico file

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#267]
I've solved that issue by including the section bellow on my share project:
`<build>
    <plugins>
        <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <configuration>
                <nonFilteredFileExtensions>
                    <nonFilteredFileExtension>ico</nonFilteredFileExtension>
                </nonFilteredFileExtensions>
            </configuration>
        </plugin>
    </plugins>
</build>`

**Comment by douglascrp** [comment]
Sorry, but I don't know how to make the xml keep the right format

**Comment by gravitonian** [comment]
Thanks, captured in DEVPLAT-44
