### ISSUE TITLE
[Windows] Unable to start server with hot deployments support

### ISSUE THREAD

**Issue by yregaieg** [Alfresco/alfresco-sdk#268]
The project skeleton generated with maven anly contain a run.sh startup script.
I tried to create one for windows :
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
set springloadedfile=%HOMEPATH%\.m2\repository\org\springframework\springloaded\1.2.0.RELEASE\springloaded-1.2.0.RELEASE.jar

if not exist %springloadedfile% (
mvn validate -Psetup
)
set MAVEN_OPTS="-javaagent:%springloadedfile% -noverify -Xms256m -Xmx2G -XX:PermSize=300m"
mvn install -Prun -nsu
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
but it doesn't work

any help is apreciated !

**Comment by gravitonian** [comment]
Hi,

As far as I can see you are missing -noverify as a parameter to turn off byte code verification, the java agent (Spring Loaded) could produce invalide code during instrumentation.

Can you also show the following:

>java -version
>mvn -version

and what logs you are getting when you try and start it up?

**Comment by yregaieg** [comment]
Hi gravitonian,

Thank you for your quick reply, here is a pastebin as you requested: http://pastebin.com/uge4wKgq
please note that I already executed <code>mvn validate -Psetup</code> and have the necessary files in my local maven repo
![image](https://cloud.githubusercontent.com/assets/11628365/6805690/9da237e0-d244-11e4-9700-35e4c3c22914.png)

**Comment by gravitonian** [comment]
Hi,

There is some error when the Spring Loaded Jar is to be loaded:

c:\tmp\aio> mvn install -Prun
Error opening zip file or JAR manifest missing : c:\Users\YOR\.m2\repository\org\springframework\springloaded\1.2.0.RELEASE\springloaded-1.2.0.RELEASE.jar -noverify -Xms256m -Xmx2G -XX:PermSize

Download newest from http://repo.spring.io/simple/libs-release-local/org/springframework/springloaded/1.2.3.RELEASE/springloaded-1.2.3.RELEASE.jar and put in some directory such as C:\Downloads. Then change your Spring loaded path. Try again.

**Comment by gravitonian** [comment]
Also, this path: "-javaagent:c:\Users\YOR\.m2\repository\org\springframework......"

Does not seem to match where the maven repo is according to screenshot. The YOR directory is called something else.

**Comment by yregaieg** [comment]
Hi there,

The url is correct: My user name corresponds to the C:\Users\YOR folder; I also added a test in the batch file for that matter !
here is the new pastebin : http://pastebin.com/94SZpQuM

**Comment by gravitonian** [comment]
Hi,

Can you try setting MAVEN_OPTS as follows:

set MAVEN_OPTS=-javaagent:"C:\Users\YOR\Downloads\springloaded-1.2.3.RELEASE.jar" -noverify -Xms256m -Xmx2G -XX:PermSize=300m

**Comment by yregaieg** [comment]
Hey,
That works !
Please add the new batch file to the project's skeleton so other windows developers would find it easier to use.
http://pastebin.com/7jFJNShq
Thank you again gravitonian for your valuable help !

**Comment by gravitonian** [comment]
Cool that it works, I have made a note of the script for windows.
