### ISSUE TITLE
Attempting to mvn:install Alfresco/alfresco-sdk stalls in tests without -DskipTests=true

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#272]
Either default to not running tests or fix the tests. I don't really care which approach we take :)

**Comment by gravitonian** [comment]
Hi,

Just did a clone of the project followed by mvn install. Build was successful.

Here are my environment settings:

martin@gravitonian:~/src/alfresco-sdk-verify$ env |grep MAV
MAVEN_OPTS=-Xms256m -Xmx1G -XX:PermSize=500m -javaagent:/home/martin/libs/springloaded-1.2.3.RELEASE.jar -noverify
martin@gravitonian:~/src/alfresco-sdk-verify$ env |grep JAVA
JAVA_HOME=/usr/lib/jvm/java-7-oracle
martin@gravitonian:~/src/alfresco-sdk-verify$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/apache-maven-3.2.5
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-48-generic", arch: "amd64", family: "unix"

I also have the Alfresco Enterprise repo credentials configured in settings.xml

So it would probably be necessary with a bit more specifics around this problem. Where is it actually stall?

**Comment by binduwavell** [comment]
I don't have any MAV prefixed environment variables. I just noticed that alfresco-enterprise.war is being downloaded. Is that expected? I don't have the enterprise stuff setup in my settings.xml.

If I mvn install from an all-in-one project generated from this checkout, the tests do complete.

-> % mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T14:58:10-06:00)
Maven home: /usr/local/Cellar/maven/3.2.3/libexec
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: US-ASCII
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"

I've run "mvn install" three times and had it stall 3 places. The most recent attempt was here:

[INFO] [INFO] --- tomcat7-maven-plugin:2.2:run (run-embedded) @ repoAmpTestRun ---
...
[INFO] 2015-04-13 09:40:53,386  INFO  [alfresco.repo.admin] [localhost-startStop-1] Using database URL 'jdbc:h2:./alf_data_dev/h2_data/alf_dev;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;MVCC=FALSE;LOCK_MODE=0' with user 'alfresco'.
[INFO]  2015-04-13 09:40:53,856  INFO  [alfresco.repo.admin] [localhost-startStop-1] Connected to database H2 version 1.4.185 (2015-01-16)
[INFO]  2015-04-13 09:41:04,871  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Starting 'sysAdmin' subsystem, ID: [sysAdmin, default]
[INFO]  2015-04-13 09:41:04,927  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Startup of 'sysAdmin' subsystem, ID: [sysAdmin, default] complete
[INFO]  2015-04-13 09:41:04,969  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Ignoring script patch (post-Hibernate): patch.db-V4.2-metadata-query-indexes
[INFO] 2015-04-13 09:41:14.141 java[33899:1790685] IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_attributesForCharacterIndex:reply:) block performed very slowly (1.16 secs)

I tried setting the following in the environment and the test passed:
MAVEN_OPTS=-Xms256m -Xmx1G -XX:PermSize=500m

Maybe there is a todo to make sure sufficient memory is allocated for the mvn instance? Or maybe when folks are dumb like I was here we just point and laugh? :)

**Comment by mindthegab** [comment]
Yep there's a doc page (both in the maven site and docs) mentioning that you need memory.

We could add it to the README as well I guess.

And yes, if you run mvn clean install, it will also run all the integration tests, which include enterprise tests, so it's expected.

Though I'd be ok, for the spirit of the community, to maybe externalize those in an 'enterprise-test' profile that only can be ran in CI or by Devs having enterprise access.

**Comment by gravitonian** [comment]
Captured in DEVPLAT-48.
