### ISSUE TITLE
Make the Maven plugin log when it installs an AMP

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#274]
The `install` goal of the Maven plugin does not log anything, which is not very standard and confused me a few times:

    [INFO] --- alfresco-maven-plugin:2.0.0:install (install-amps) @ alfresco-enterprise ---
    [INFO]

It would be nice to have at least a line with level `[INFO]` telling which AMP file is installed and where. That especially makes sense since you can pass a folder of AMPs to have all of them installed. The log could be something like:

    [INFO] --- alfresco-maven-plugin:2.0.0:install (install-amps) @ alfresco-enterprise ---
    [INFO] Installing /blabla/toto.amp into /foo/bar/target/alfresco.war
    [INFO]

Additionally, if it's not too complicated, it would be even nicer to display the id and version from the `module.properties`, if available:

    [INFO] --- alfresco-maven-plugin:2.0.0:install (install-amps) @ alfresco-enterprise ---    [INFO] Installing AMP files into /foo/bar/target/alfresco.war
    [INFO] /blabla/alfresco-share-services.amp (alfresco-share-services version 5.1.0)
    [INFO] /blibli/alfresco-rm-2.3.amp (org_alfresco_module_rm  version 2.3)
    [INFO]

**Comment by gravitonian** [comment]
Linked to https://issues.alfresco.com/jira/browse/DEVPLAT-57

**Comment by mindthegab** [comment]
I have added an initial logging, you can test in 2.1.1-SNAPSHOT.

**Comment by mindthegab** [comment]
@slanglois Can you test if this works for you (with 2.1.1-SNAPSHOT)? Assigning the issue to you.

Thanks!

**Comment by slanglois** [comment]
[INFO] --- alfresco-maven-plugin:2.1.1-SNAPSHOT:install (install-amps) @ alfresco ---
    [INFO] Installing all AMPs from directory d:\work\web-apps\Share\branches\RA-SPRINT6\alfresco\target\amps into WAR/exploded webapp at d:\work\web-apps\Share\branches\RA-SPRINT6\alfresco\target\alfresco.war
    [INFO] AMPs installed successfully

OK, that will do!
Thanks
