### ISSUE TITLE
Classpath import for repo webscript not hot reloading

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#276]
I have a javascript Web Script that includes a library as follows:

<import resource="classpath:/alfresco/extension/templates/webscripts/com/ziaconsulting/example/upload/upload-utils.js">

Changes to upload-utils.js are not reflected after running

mvn compile -Pclear-caches-refresh-ws

normally I would run this in the repo-amp module. However, I also tried running from the parent folder. No dice either way.

If I explicitly edit the upload-utils.js script under runner/target changes are reflected right away.

I'm running with 2.0.1-SNAPSHOT from a few hours ago.

**Comment by ohej** [comment]
Discussed this on skype. Same issue as https://issues.alfresco.com/jira/browse/DEVPLAT-28
Solution: Remove leading slash in the import statement.

**Comment by binduwavell** [comment]
Ole pointed me to: https://issues.alfresco.com/jira/browse/DEVPLAT-28. I confirmed that the workaround there also worked in this repo webscript case.
