### ISSUE TITLE
We should generate unique module names for the repo-amp and share-amp

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#278]
I have a concern with the SDK as it is today. Specifically the way it works right now and especially for AIO, the repo-amp and share-amp modules/artifacts/moduleIds care essentially static. 

As such if two devs (or hopefully 100's) possibly at different companies attempt to use the archetype to create a project they will both end up with repo-amp.amp and share-amp.amp. 

If they publish their work to add ons, now it is not possible to utilize both of these add ons at the same time in a single alfresco install. 

With the work we did recently to generalize the source code path based on prompting for package, I was hoping that we'd also end up with something like ${artifactId}-repo-amp and ${artifactId)-share-amp with appropriate moduleIds, etc.

**Comment by binduwavell** [comment]
I saw the note here: http://docs.alfresco.com/5.0/concepts/alfresco-sdk-archetypes-aio.html

Indicating AIO should not be used for addons. For now, we should probably explain why we are suggesting that. 

In the medium term we should remove this restriction at least.

**Comment by gravitonian** [comment]
Duplicate to #311
