### ISSUE TITLE
Rename repo module in the AIO archetype to alfresco (at least make sure the output war is alfresco.war)

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#279]
I think the repo module should be renamed to alfresco so that the generated war is called alfresco. If we want to build wars using the AIO archetype and deliver these to environments it will be much simpler if the war has the expected name.

**Comment by mindthegab** [comment]
This is how it was called in the past, but made it quite unclear to understand it was just a WAR overlay and alfresco is a very overloaded word :)

The build finalName is in fact alfresco.war (for ease of local running), but I think you can change the artifactId yourself if you feel this is best of your process.

**Comment by binduwavell** [comment]
OK, I get the rational.

As far as I can tell, the AIO archetype is generating a war called repo.war in 2.0.0 and in master versions of the SDK.
