### ISSUE TITLE
AIO archetype in master is currently failing to build

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#280]
```shell
git clone git@github.com:Alfresco/alfresco-sdk.git
cd alfresco-sdk.git
mvn install -DskipTests
cd ..
mvn archetype:generate -DinteractiveMode=false -DarchetypeGroupId=org.alfresco.maven.archetype -DarchetypeArtifactId=alfresco-allinone-archetype -DarchetypeVersion=2.0.1-SNAPSHOT -DgroupId=com.company.project -DartifactId=alfresco -Dversion=1.0.0-SNAPSHOT -DarchetypeCatalog=local -Dpackage=com.company.project.alfresco
cd alfresco
chmod 755 run.sh
./run.sh
```

```
... SNIP ...
[WARNING] The POM for com.googlecode.javacpp:javacpp:jar:0.1 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar
... SNIP ...
[ERROR] Failed to execute goal on project share-amp: Could not resolve dependencies for project com.company.project:share-amp:amp:1.0.0-SNAPSHOT: Failure to find com.googlecode.javacpp:javacpp:jar:0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

Looking at the output of ```mvn dependency:tree -X```, which fails... but with the -X, we find the issue:

```
[DEBUG]    org.alfresco:share-po:jar:5.1-SNAPSHOT:test
[DEBUG]       org.alfresco:webdrone:jar:2.9:test
.... SNIP ...
[DEBUG]          org.sikuli:sikuli-api:jar:1.1.0:test
[DEBUG]             org.sikuli:sikuli-core:jar:1.1.3:test
[DEBUG]                com.googlecode.javacpp:javacpp:jar:0.1:test
```

**Comment by binduwavell** [comment]
When I say we find the issue... What I mean is we find how we end up relying on ```com.googlecode.javacpp:javacpp:jar:0.1```. This jar is not available in maven central (or artifacts.alfresco.com for that matter.) I believe that 0.4 is the oldest version of this jar on maven central:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.googlecode.javacpp%22%20AND%20a%3A%22javacpp%22

**Comment by binduwavell** [comment]
I sure love being wrong... :)

These files ARE available on artifacts.alfresco.com under the 3rd party repository which is in the Public Releases Repositories (GA) group which is included by the alfresco-sdk-aggregator. It is also available in the Alfresco Enterprise and Public releases aggregated for Customers and Partners group used for enterprise.

More details from the error:

Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
Downloading: https://repo.maven.apache.org/maven2/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
[WARNING] The POM for com.googlecode.javacpp:javacpp:jar:0.1 is missing, no dependency information available
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar
Downloading: https://repo.maven.apache.org/maven2/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar

Notice the path: ...com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
The path on artifacts.alfresco.com ...com/googlecode/javacpp/0.1/javacpp-0.1.pom

If we go look at the official location for this asset: http://maven2.javacpp.googlecode.com/git/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom

Notice the path is: ...com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom as expected by the build.

So the issue is that the javacpp:0.1 asset has been deployed to the wrong path on artifacts.alfresco.com.

Also, I'm not clear why we didn't just pickup the googlecode repository transitively...

**Comment by ohej** [comment]
I've tried this in a few different ways and I can't seem to get the same error as you do. I've wiped out ~/.m2/repository to make sure that wouldn't be the issue but I don't see it. Could you re-try and see if you still get the error?

**Comment by binduwavell** [comment]
Sure, will do when I get to the office.

**Comment by gravitonian** [comment]
Hi, the version was recently updated to 2.1.0-beta-1, use:
```
$ mvn archetype:generate -DinteractiveMode=false -DarchetypeGroupId=org.alfresco.maven.archetype -DarchetypeArtifactId=alfresco-allinone-archetype -DarchetypeVersion=2.1.0-beta-1 -DgroupId=com.company.project -DartifactId=alfresco -Dversion=1.0.0-SNAPSHOT -DarchetypeCatalog=local -Dpackage=com.company.project.alfresco
```
You would not see this if you did:
```
$ mvn archetype:generate -DarchetypeCatalog=local
```

**Comment by binduwavell** [comment]
So I'm still seeing this on master (2.1.0-SNAPSHOT form about 15 minutes ago.) Should I be working off some other branch?

**Comment by mrksjs** [comment]
applied to me as well.
i had to increase the version of the artifact in the parent pom
```
<dependency>
    <groupId>com.googlecode.javacpp</groupId>
    <artifactId>javacpp</artifactId>
    <version>0.4</version>
</dependency>
```

**Comment by slanglois** [comment]
Getting interested in this case, because we just had a customer encountering it...

This javacpp:0.1 is a dependency of sikuli-core, as you can see in its POM : https://repo1.maven.org/maven2/org/sikuli/sikuli-core/1.1.3/sikuli-core-1.1.3.pom
It is not in Alfresco Maven repo, nor in Maven Central, but in a repo which is declared in the sikuli-core POM: 

     <repository>
       <id>JavaCV Maven</id>
       <url>http://maven2.javacv.googlecode.com/git/</url>
     </repository>

Is there any reason why you wouldn't be able to download artifacts from this repository? A filtering proxy of some sort? I can see it working fine on my machine:

    Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
    Downloading: https://repo.maven.apache.org/maven2/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
    Downloading: http://maven2.javacv.googlecode.com/git/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom
    Downloaded: http://maven2.javacv.googlecode.com/git/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.pom (4 KB at 5.0 KB/sec)
    Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar
    Downloading: https://repo.maven.apache.org/maven2/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar
    Downloading: http://maven2.javacv.googlecode.com/git/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar
    Downloaded: http://maven2.javacv.googlecode.com/git/com/googlecode/javacpp/javacpp/0.1/javacpp-0.1.jar (97 KB at 145.7 KB/sec)
