### ISSUE TITLE
Updgrade SDK to Java8

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#282]
Both 5.0.d and 5.0.1 uses it, and those are the versions we have set in the SDK now.

Most allocations for the class metadata are now allocated out of native memory. This means that we won’t have to set the “XX:PermSize” options anymore (they don’t exist).

Don't forget to update related docs.

**Comment by ohej** [comment]
I've accepted the pull request (https://github.com/Alfresco/alfresco-sdk/pull/277) and bumped the version to 1.8 by default. It's easy to reconfigure it back to 1.7 by setting the ``maven.compiler.target`` and ``maven.compiler.source`` properties.
