### ISSUE TITLE
Error with java 8u40 and springloaded 1.2.0 RELEASE

### ISSUE THREAD

**Issue by jtalfresco** [Alfresco/alfresco-sdk#285]
Executing run.sh with the following:
* SDK 2.0.0
* Java 8
* Alfresco 5.0.1
* maven 3.3.3

Generates the following error:
  * ```org.springsource.loaded.jvm.JVM copyConstructor
SEVERE: Problems copying constructor. Incompatible JVM?```
  * ```Caused by: java.lang.IllegalArgumentException: Can not copy a non-root Constructor```

This issue is identified in this issue in the springloaded project:
https://github.com/spring-projects/spring-loaded/issues/108

This issue is fixed in springloaded 1.2.2 and later. Please update the project to springloaded 1.2.2+.

**Comment by mindthegab** [comment]
SDK 2.1.0 ships by default with Spring Loaded 1.2.3, closing.

Also each archetype or projects using the alfresco-sdk-parent can override the spring-loaded version on their pom.xml by setting:

<springloaded.version>1.2.3.RELEASE</springloaded.version>
