### ISSUE TITLE
Plugin generated properties in finalName break the amp generation

### ISSUE THREAD

**Issue by skopf** [Alfresco/alfresco-sdk#286]
You can choose a custom name for the amp artifact and even use properties in this name by setting the `<finalName>` for the build:
`<finalName>${project.artifactId}-custom</finalName>`
But if the final name contains properties that are generated  by a plugin like the `noSnapshotVersion` or the `parsedVersion.*` properties provided by the build-helper, then the amp generation is broken.

The Alfresco SDK generates two folders in `/target`, one with this property resolved and another folder where this property has not been resolved. The generated jar and the configuration are placed into different folders, and only one of them is packed into the amp.

The problem is that the Alfresco SDK does not handle these properties consistently. Some parts of the Alfresco SDK properly resolve this property (the amp generation and the target of the jar generation), while other parts of the SDK do not (copying the `/config` folder)

**Comment by mindthegab** [comment]
Most of this logic will go away with the JAR support, I don't think we'll be able to fix this in a SP, rather fix it properly in the new version.

**Comment by gravitonian** [comment]
Tracked by: https://issues.alfresco.com/jira/browse/DEVPLAT-445

**Comment by gravitonian** [comment]
fixed
