### ISSUE TITLE
Cannot run tests on successfully completed build.

### ISSUE THREAD

**Issue by docterwatson** [Alfresco/alfresco-sdk#287]
Building a new project, version 5.0.c. Running into the same issue as [#227](https://github.com/Alfresco/alfresco-sdk/issues/227) preventing me from running the embedded tomcat/H2. 

Cause: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/ibatis/#resource.dialect#/activities-insert-SqlMap.xml

Searching the project I cannot locate this file anywhere in the built environment.

Stack:
OS X 10.10.3
javac 1.7.0_51
sdk version 2.0.0

**Comment by docterwatson** [comment]
Confirmed this works fine in v. 2.1.0.

**Comment by mindthegab** [comment]
Thanks closing with 2.1.0 milestone.
