### ISSUE TITLE
All-in-one archetype generates incorrect module names in parent pom

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#292]
Example
```
  <modules>
    <module>se.loftux.extensions.kanban.repo-amp</module>
    <module>share-amp</module>
    <module>se.loftux.extensions.kanban.repo</module>
    <module>solr-config</module>
    <module>share</module>
    <module>runner</module>
  </modules>
```

**Comment by ohej** [comment]
What values did you enter when generating the project?

**Comment by bhagyas** [comment]
groupId: se.loftux.extensions.kanban
artifactId: kanban-waitara

**Comment by ohej** [comment]
I can't reproduce this issue. Just created an AIO  Could you provide more info? 
Tried both entering the values manually and in the command line like this:
``mvn archetype:generate -DarchetypeGroupId=org.alfresco.maven.archetype -DarchetypeArtifactId=alfresco-allinone-archetype -DarchetypeVersion=2.1.0 -DinteractiveMode=false -DgroupId=se.loftux.extensions.kanban -DartifactId=waitara-kanban``

Did you use 2.1.0? Which version of Maven are you using?

**Comment by ohej** [comment]
After some discussion on IRC we are still unable to reproduce the issue. Please reopen or open a new issue if it happens again. Next time please include the full output from the generation of the project and environment details like JDK, Maven and OS.
