### ISSUE TITLE
Deprecate noSnapshotVersion logic, as upstream https://issues.alfresco.com/jira/browse/ACE-2269 was fixed

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#294]
https://issues.alfresco.com/jira/browse/ACE-2269 was fixed in 5.0.0. This means Alfresco will accept -SNAPSHOT as a module version.

This will allow to remove the "hack" we currently do in the SDK to produce a noSnapshotVersion of the module.

I suggest we just use -SNAPSHOT during module development, with maybe an option to append / replace with an incremental version number (i.e. maybe leave the current logic in place, but make -SNAPSHOT the default and instead allow people to manually configure if they want moduleIncrementalSnapshotVersioning)

**Comment by rgauss** [comment]
Is support of 4.2 still a goal of the alfresco-sdk?

**Comment by mindthegab** [comment]
@rgauss Yes, as per http://docstest.alfresco.com/5.0/concepts/alfresco-sdk-compatibility.html and, 1.1.1 is compatible with 4.2, while 2.0.0 and 2.1.0 with 5.x.

And, per http://www.alfresco.com/services/subscription/technical-support/product-support-status, 4.2.Latest is still in full support, so yes we need to provide an SDK for it.

1.1.1. is what works with 4.2, but obviously it has no hot reloading support. @ohej had started working on backporting 2.0.0 features into a 1.2.0, and did some work at DevCon hackathon last year that resulted in a 1.2.0-SNAPSHOT (see https://oss.sonatype.org/#nexus-search;gav~org.alfresco.maven~~1.2.0-SNAPSHOT~~), but we never did a final release. We are picking this back up and plan to do a 1.2.0 release based off new features on 2.1.0.

Makes sense?

**Comment by rgauss** [comment]
Yes, we just need to be sure this particular issue stays only on the SDK 2.x code line as ACE-2269 does not apply to Alfresco One 4.2.x.

**Comment by gravitonian** [comment]
Tracked by: https://issues.alfresco.com/jira/browse/DEVPLAT-452

**Comment by gravitonian** [comment]
Fixed
