### ISSUE TITLE
Allow configuration of the generated jar in an amp file.

### ISSUE THREAD

**Issue by covolution** [Alfresco/alfresco-sdk#295]
How does the alfresco-maven-plugin build the amp JAR if the packaging is <packaging>amp</packaging>?  Specifically, the jar that goes in the amp.

I would like to configure the jar manifest to add some build information.  Using a maven-jar-plugin configuration in the amp pom.xml doesn't work.

Perhaps we could expose the standard "archiver" configuration somehow?

**Comment by mindthegab** [comment]
we tested this and the standard <archiver> configuration works in the alfresco:amp goal. Closing the issue.
