### ISSUE TITLE
SDK does not honour <webappDirectory> when it's redefines in the war plugin

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#297]
I have this configuration of the war plugin:

```
        <plugin>
            <artifactId>maven-war-plugin</artifactId>
            <configuration>
                <!-- Explicit overlay declaration -->
                <overlays>
                    <overlay>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>alfresco-platform-enterprise</artifactId>
                        <type>war</type>
                    </overlay>
                    <overlay>
                        <groupId>org.alfresco</groupId>
                        <artifactId>alfresco-share-services</artifactId>
                        <type>amp</type>
                    </overlay>
                </overlays>
                <webappDirectory>${project.build.directory}/alfresco-ssl</webappDirectory>
            </configuration>
```

The application of the AMP does not work, because it tries to install it in the default location of the war, as the log makes it clear:

```
[INFO] --- maven-war-plugin:2.6:war (default-war) @ alfresco-enterprise ---
[INFO] Packaging webapp
[INFO] Assembling webapp [alfresco-enterprise] in [d:\work\RA-SPRINT6\root\enterpriseprojects\overlays\alfresco\target\alfresco-ssl]

[INFO] Processing war project
[INFO] Copying webapp resources [d:\work\RA-SPRINT6\root\enterpriseprojects\overlays\alfresco\source\web]
[INFO] Processing overlay [ id org.alfresco:alfresco-platform-enterprise]
[INFO] Processing overlay [ id org.alfresco:alfresco-share-services]
[INFO] getDestDirectory ():d:\work\RA-SPRINT6\root\enterpriseprojects\overlays\alfresco\target\alfresco
```

**Comment by slanglois** [comment]
Sorry, I'm afraid that's not good enough: I tested with version `2.1.1-20150601.171558-10` and I still get the same problem.
Here is a POM file that reproduces the problem. 
Simply run `mvn package` on it. You'll see that it generates 2 wars, but only one has the AMP being applied.

**Comment by mindthegab** [comment]
Samuel can you post the POM again? it did not come through with the email...

**Comment by slanglois** [comment]
That's because I forgot to put the link... Sorry about that!
https://gist.github.com/slanglois/c76d449dc9fab3645e1a

**Comment by gravitonian** [comment]
Had a chat with Sam to clarify a bit. The whole thing is about being able to produce different versions of the alfresco.war. If we test so it works with the following customization then we should be good: add another execution to the existing repo/pom.xlm maven-war-plugin that produces a different war and then add another completely new maven-war-plugin configuration that produces a third war, maybe with some other AMPs applied.

**Comment by mindthegab** [comment]
@slanglois you OK for this *not* to be a blocker for 2.1.1? We'd like to release in the next days.

**Comment by slanglois** [comment]
This is definitely not a blocker.
Few people will encounter this bug, it is a weird setup.
Plus, there is a simple enough workaround, which is to explicitely call the `alfresco-maven-plugin:install` goal, to apply the AMP on the non-standard location of the war. This is what we are using currently.

Don't spend time on this and release 2.1.1 :-)

**Comment by ohej** [comment]
Since we don't use overlays anymore this problem goes away in SDK3. Closing
