### ISSUE TITLE
Define argLine property rather than setting it in surefire, to ease integration with other plugins

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#298]
The parent pom of the SDK currently defines this:

           <plugin>
             <groupId>org.apache.maven.plugins</groupId>
             <artifactId>maven-surefire-plugin</artifactId>
             <version>${maven.surefire.version}</version>
             <configuration>
                 <argLine>${app.testing.jvm.args}</argLine>
             </configuration>
           </plugin>

This makes it impossible for other plugins to redefine this argLine setting. 
My use case is the [maven-jacoco-plugin](http://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html), which adds a java agent on the command line to generate some code coverage. 
The warning at the beginning of that page explains it very well. 
It would be much more convenient not to configure this in the surefire plugin, but just defining the `argLine` property:

    <argLine>-Xms256m -Xmx1524m -XX:MaxPermSize=256m -Duser.language=en</argLine>

(And by the way, this could be a nicer way to add the spring-loaded argument on the command line too...)

**Comment by mindthegab** [comment]
I am not clear about this one.

Can <argLine> be added at maven top level in the pom? i.e. applies to the JVM that runs maven or to a forked JVM?

Or you mean surefire.argLine?

Re spring-loaded, we tried a lot but since tomcat is not forked we were not able to pass parameters via Maven but we had to call maven with the agent. C

Can you elaborate a bit on this issue?

Moving to enhancement and post 2.1.1.

**Comment by slanglois** [comment]
I mean that the argLine parameter should be defined as a property of the pom, rather than a configuration of surefire.

     <properties>
       <argLine>-Xms256m -Xmx1524m -XX:MaxPermSize=256m -Duser.language=en</argLine>
     </properties>
     ...
     <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-surefire-plugin</artifactId>
       <configuration>
         
       </configuration>
     </plugin>

This has the same effect, but allows other plugins - such as JaCoCo - to alter this value.
