### ISSUE TITLE
share-config-custom.xml changes are not loaded on all-in-one archetype

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#299]
Everytime I change the share-config-custom.xml, I have to purge the project in order to have my changes applied on share-amp project.

I'm using the 2.1.0 version

**Comment by Tybion** [comment]
I can confirm this.  I have the same problem.
Seems that share-config-custom.xml ends up in share-amp.jar, but this is not being applied to the runner tomcat process.
I have to ..
stop tomcat
mvn clean
./run.sh

**Comment by Tybion** [comment]
More info - when I edit /share-amp/src/main/resources/META-INF/share-config-custom.xml, the following lines are displayed by the runner tomcat process, but the change is not applied to the tomcat process.

`Jun 21, 2015 8:26:08 AM org.springframework.extensions.webscripts.DeclarativeRegistry reset
INFO: Registered 369 Web Scripts (+0 failed), 383 URLs
Jun 21, 2015 8:26:08 AM org.springframework.extensions.webscripts.DeclarativeRegistry reset
INFO: Registered 8 Package Description Documents (+0 failed) 
Jun 21, 2015 8:26:08 AM org.springframework.extensions.webscripts.DeclarativeRegistry reset
INFO: Registered 0 Schema Description Documents (+0 failed) 
Jun 21, 2015 8:26:08 AM org.springframework.extensions.webscripts.AbstractRuntimeContainer reset
INFO: Initialised Spring Surf Container Web Script Container (in 4897.183ms)`

**Comment by mindthegab** [comment]
This needs to be fixed and verified for 2.1.1. @ohej assigned to you, can you work with @gravitonian to ensure this is fixed (and the related DEVPLAT issue closed)?

Thanks!

**Comment by marcoaltieri** [comment]
Is this bug fixed? I can still replicate it in SDK 2.2.

**Comment by mits2013** [comment]
Just now bumped into this issue. Seems like not fixed in 2.1.1. Not sure about 2.2.
