### ISSUE TITLE
Support Java 7

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#301]
Alfresco SDK 2.1.0 has dropped support for Java 7.
I know it's been deprecated and all, but we still have to support it. (For instance, IBM WebSphere has no version supporting Java 8, and we have customers using it.) 
This prevents us from upgrading, and we're stuck on 2.0.0.

Moreover, using the <overlay> of AMPs in Java7 does not appear to break the build - you just get a warning:

    [WARNING] Skip unpacking dependency file [/Users/gcornwell/.m2/repository/bla/bla.amp with unknown extension [amp]

It took us a while to figure out what was wrong...

Please revert the build of the Alfresco SDK to Java 7!
Thanks

**Comment by mindthegab** [comment]
I added 

       <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>

to the SDK build.

The next 2.1.1-SNAPSHOT should be OK having 1.7 as a target.

See commit 3116123800d60869713beecc24c8a923040c3ec6

**Comment by mindthegab** [comment]
This is now fixed, reverted to Java7 and removed the enforcer flag.

**Comment by mindthegab** [comment]
@slanglois do you think this can be closed?

**Comment by ohej** [comment]
We're back to JDK7, verified that it works on both JDK7 and JDK8 closing
