### ISSUE TITLE
Need a profile for community

### ISSUE THREAD

**Issue by pmonks** [Alfresco/alfresco-sdk#304]
There needs to be a profile for community, so that projects that wish to have enterprise as the default build target can do so, without completely losing the ability to build against Community.

Today, if a project's pom sets the enterprise profile as the default, there's no way to choose to build against community without editing the pom.

**Comment by binduwavell** [comment]
-P -enterprise ?

**Comment by Sheldor5** [comment]
No @binduwavell , @pmonks means that if you set the enterprise profile as default in the pom (so you don't have to run maven with the `-Penterprise` profile) you have no way back to the community edition than editing the pom again. A profile like `-Pcommunity` is requested.

**Comment by mindthegab** [comment]
I don't understand this issue.

One between Community and Enterprise should be the default and for obvious reasons (it's a community project and it can just work without any credentials/additional settings) Community is the default.

Now if you set <activeByDefault> for your enterprise profile, either in POM or settings.xml, then Enterprise becomes the default.

At that poinr, Albeit the syntax was wrong, @binduwavell suggestion was right and you can run your build with:

-P!enterprise

(Notice the !) 

Which will disable the manually defaulted enterprise profile and get you back to community.

does this solve your issue? If so I think this can be closed.

**Comment by binduwavell** [comment]
For what it's worth I did not know about the ! syntax and I prefer it, but the - syntax is also valid:

Starting with Maven 2.0.10, one or more profiles can be deactivated using the command line by prefixing their identifier with either the character '!' or '-' 

From: http://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by pmonks** [comment]
I wasn't aware of the ! or - syntax either, but *don't* prefer it, for reasons of symmetry.  Community and Enterprise are "peers", and should be handled as such by the SDK.

**Comment by binduwavell** [comment]
For what it's worth, we want the archetypes to work right away given that folks have appropriate java and maven. 

To me that is a key reason for community to be default. 

If you enable the enterprise profile in your settings.xml or your top level pom, then you would expect enterprise to always be enabled (because you made this change.) Assuming -P!enterprise works in these cases, I'd propose that we close this ticket.

**Comment by pmonks** [comment]
I agree, and you can mark any profile you like as "activated by default", which both meets the requirement you describe while still meeting mine (i.e. being able to explicitly pick any profile, without relying on little-known command line syntax).

**Comment by mindthegab** [comment]
Closing as per previous comments

**Comment by pmonks** [comment]
I think my comment was misunderstood. What I was saying us that having a dedicated profile for Community meets Bindu's requirement of being the default default, while also meeting my requirement of being able to select enterprise as my projects default, while still being able to easily switch between the two.

**Comment by jgoldhammer** [comment]
The new version allows to switch via maven property.
`<alfrescoEdition>community</alfrescoEdition>`

So I will close the ticket for now. If anybody sees this different, please reopen the ticket here.
