### ISSUE TITLE
Add localisation examples to generated archetype example code

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#306]

**Comment by mindthegab** [comment]
You mean a sample of messages in multiple languages?

Seems like a low hanging easy add-on. @ohej @gravitonian WDYT?

**Comment by bhagyas** [comment]
Yeah.

**Comment by mindthegab** [comment]
@ohej can you check with Richard / Gloria what a meaningful example would be?

@bhagyas do you have a chance send a PR for this one, seems pretty easy / low blast radius one?

**Comment by ohej** [comment]
SDK3 contains i18n examples
