### ISSUE TITLE
Repo amp archetype with amp-to-war brings in test dependencies

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-sdk#307]
Running a AMP archetype project with `amp-to-war` will bring in alfresco-rad, which will bring in jetty, args4j and spring-test into the project. These dependencies should be fine with going in the `<scope>test</scope>`, but doing so could potentially break the remote unit test runner. 

If you, by mistake, do a `mvn install` after running with `amp-to-war`, or for some reason activate `amp-to-war` you end up with these test dependencies in your AMP. However, a clean should always be performed before packaging and deploying, but still, these are clearly test dependencies and should be in the test scope.

Need to investigate further, and may depend on finishing off the contributions from Bindu with the new web script runner.

**Comment by manoswerts** [comment]
I also mentioned this on issue #300. @mindthegab, any further update on this and my comment on the other issue?

**Comment by mindthegab** [comment]
Let's please keep this bug (wrong scope) and the request for a new / different behavior (i.e. making the amp-to-war produced artifact pristine) separate issues.

This one needs to be fixed for 2.1.1, assigning to you @ohej to work with @gravitonian to ensure it's fixed. I suggest we instead use #300 to keep the discussion on a cleaner "amp-to-war" profile.

@ohej can you update the issues to reflect his spearation?

**Comment by manoswerts** [comment]
Indeed, those are 2 different issues. Sorry for mixing them up.

So like I said before, we use the amp-to-war profile to run automated integration tests against the embedded Tomcat server. Our build server makes sure that the build is successful (therefore running the integration tests) and then releases the artifact.

This seems like a common use case to me.
