### ISSUE TITLE
Custom dependency overlays not available when running using run.sh

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#308]
1. Add a custom share module dependency.
2. Run the project using run.sh (all-in-one archetype)
3. Observe if the module has loaded.

Step 3 results in nothing.

**Comment by bhagyas** [comment]
Purged the entire project using `mvn clean -Ppurge` and now it seems to work.

Possibly related to #299

**Comment by mindthegab** [comment]
This is a dupe of #299, closing.
