### ISSUE TITLE
Add support for generating deployable WAR files to the server

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#310]

**Comment by mindthegab** [comment]
No Sure what this means really. Can you elaborate? Is this deploying to an existing server? Shouldn't this be just a tomcat7:deploy? BTW which server, only tomcat?

**Comment by bhagyas** [comment]
Yes. This should be support for tomcat7:deploy at first or at all. This really helps with continuous integration deployments  and automated testing.

We were able to get it working with some configuration which we might be able to share.

At the moment, probably due to some memory leaks, the deployment becomes unusable after a few deployments using the command.

**Comment by mindthegab** [comment]
Cool, would be great if you can send a pull request. Seems quite little config around tomcat7:deploy so hopefully you can just share that.

I would have guessed your problems were around the infamous permGen (gone in java8 but unluckily we are still stuck on Java7 because of websphere).
