### ISSUE TITLE
Incorrect naming for generated amp modules

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#311]
1. Generate a project using the archetype.
2. Compile the project.
3. Check module name in target/repo/WEB-INF/classes/alfresco/module

In step 3, module name says repo-amp.

This introduces issues when creating a combined project with two or more maven archetype generated projects.

**Comment by bhagyas** [comment]
Related to #312

**Comment by mindthegab** [comment]
Is this also a dupe of #278 ?

@ohej Can you please make some clarity between #278 , #312 , #311 and the pull request #316 ?

**Comment by ohej** [comment]
We had to revert the change since we can't have this substantial changes in a minor release. When we want the change to go in, we simply have to "revert the revert" like this:
`git revert b2afebed09befcbbe1214d056b6f976da5303968`

**Comment by ohej** [comment]
I have reverted the revert so this will be in the next release
