### ISSUE TITLE
Incorrect Module ID for generated submodules

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#312]
1. Generate project using the all-in-one archetype
2. Look into module.properties files generated after compiling.
3. Observe the module.id property in module.properties.

`module.id` property displays `repo-amp`.

**Comment by mindthegab** [comment]
Since repo-amp is incorrect, would you mind telling us in your view, what is correct?

Given the little description, I am assuming this is just a dupe of #311 (also as #316 fixed both), so closing this one.
