### ISSUE TITLE
Add tests for archetype RAD functionality

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#313]
Add unit tests for archetype generation.

**Comment by bhagyas** [comment]
Add tests for RAD capabilities.

**Comment by mindthegab** [comment]
Hey @bhagyas that's a very good idea. 

Any idea / contribution on how this could be done? Would you be able to suggest / send a pull request?

For now we do this manually.

**Comment by ohej** [comment]
There is no easy way for us to automate testing of this. If you have ideas on how to do it, we would welcome a contribution. Archetype tests are already in place. Closing

**Comment by bhagyas** [comment]
@ohej Are you closing the issue because it didn't meet the milestone? 

Would be glad to share any updates in this issue if there are any coming up. I'd prefer to have it open as a point of conversation for future improvements.

**Comment by ohej** [comment]
I don't see us adding these tests so I closed it. Gab requested you to help contribute back in 2015 and you never replied. If you have ideas or contributions feel free to reopen.
