### ISSUE TITLE
Tests for enterprise profile should be runnable without private access to the enterprise repository.

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#314]
Running tests with -Penterprise fails.

**Comment by mindthegab** [comment]
No, enterprise artifacts are private and this is not going to change any soon.

Closing.

For the future: if you can actually also explain WHY you require something or even give us an idea of the business value, that would help.

**Comment by bhagyas** [comment]
Maven SDK being an open source project, an open source contributor who does not have access to the enterprise repository will not be able to test against enterprise profile. I faced this issue when contributing and testing the improved module naming.

Being a technical open source contributor for a technical project, business value would not, and should not be something contributors would have to bring up. I and anyone else would find the above comment to be discouraging to any open source  contributor and anyone who do not have access to the enterprise artefacts. If Maven SDK was something that makes technical decisions based on business value alone, I would very much have liked it to be closed source and away from being something that anyone can contribute.

An option would be to remove the enterprise test profile from the **default** test configuration for the Maven SDK open source project.

**Comment by mindthegab** [comment]
Given the very short description, I had no idea what you meant. But @ohej helped me figured it out, and yes this last comment explains it. 

I am about to commit a fix that by default doesn't run enterprise tests but if you run with -Penterprise-tests it then will (which we will configure in CI).

Can you give it a whirl when I commit?"

**Comment by mindthegab** [comment]
Fixed the issue by introducing an 'enterprise-tests' profile that needs to be activated manually.

By default mvn clean install works.

Can you give it a spin just to double check @bhagyas ? Thanks for reporting this!

**Comment by bhagyas** [comment]
Sure.

**Comment by binduwavell** [comment]
wonder if this could just hang off the enterprise profile?

**Comment by mindthegab** [comment]
I called it enterprise-tests.

I don't want to overload the 'enterprise' profile, since this is for the SDK project, not for the projects generated with the SDK.

**Comment by binduwavell** [comment]
Doh, sorry was reading the bazillions of updates yesterday and going too fast ;) completely makes sense!
