### ISSUE TITLE
context-solr.xml in runner uses wrong path variables for SOLR directories

### ISSUE THREAD

**Issue by igorbga** [Alfresco/alfresco-sdk#317]
The runner's context-solr.xml is assuming that everyone will use the default directories for solr config and data instead of using the already existing solr dir properties. Environment lines should be change to this:

```
    <Environment name="solr/home"        type="java.lang.String" value="${alfresco.solr.home.dir}/" override="true"/>
    <Environment name="solr/model/dir"   type="java.lang.String" value="${alfresco.solr.home.dir}/alfrescoModels/" override="true"/>
    <Environment name="solr/content/dir" type="java.lang.String" value="${alfresco.solr.data.dir}/content/" override="true"/>

```

**Comment by mindthegab** [comment]
Hey @igorbga thanks for the report.

I think this make sense to me.

Being a small and localize change, If you could send us a pull request soon, this might make it in the upcoming 2.1.1 (assigned to that milestone).

Let us know, thx!

**Comment by igorbga** [comment]
Hi @mindthegab,
Pull requested, thanks.

**Comment by ohej** [comment]
I've accepted and merged the pull request. Everything looks good!
