### ISSUE TITLE
Provide a default .gitignore file

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#318]
Either as a part of the archetype or an independently downloadable file.

**Comment by binduwavell** [comment]
Bhagyas, I'd appreciate your feedback on the work we are doing with yeoman to wrap the all in one archetype. We do offer to create a .gitignore file. If you have suggestions for other items to add to this file, I'd greatly appreciate your feedback!

**Comment by mindthegab** [comment]
Not sure this should be in the SDK. Meaning: what if you are using any other VCS?

Not sure I want to clutter the generated projects with stuff that really isn't general (albeit I agree widely used).

**Comment by mindthegab** [comment]
Also github maintains a list of generic .gitignores (e.g. maven.gitignore see https://github.com/github/gitignore/blob/master/Maven.gitignore), so I think that's where this should be taken.

I will close this issue.

**Comment by bhagyas** [comment]
A .gitignore would help a lot of developers who use Git as a primary source control. Support for major source control systems can be included additionally added.

It's quite common for new open source code generator/archetype projects to provide these.

An example would be a rule to ignore anything such as alf_data_dev from being committed to the source control.
