### ISSUE TITLE
Host external dependencies that are not available without a repository configuration

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#319]
Some of the dependencies are not available when you are running a fresh build on a new server.

Example: com.google.guava:guava:jar:11.0.2

Suggestion: Proxy or host the dependencies from artifacts.alfresco.com server.

**Comment by slanglois** [comment]
I don't understand your issue. 
Guava is provided by Maven Central : http://search.maven.org/#artifactdetails|com.google.guava|guava|11.0.2|jar
These artifacts should always be accessible. Alfresco is not going to proxy Maven Central, that would be a huge waste of efforts...
Did you configure your Maven settings in a way that artifacts.alfresco.com is a proxy of Central?

**Comment by bhagyas** [comment]
@slanglois Thank you for the response, looks like it have been a connectivity issue.
