### ISSUE TITLE
Unable to read the metadata file for artifact 'com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar':

### ISSUE THREAD

**Issue by mxc** [Alfresco/alfresco-sdk#325]
Hi there,

We are getting the following error when building an application created with  the Alfresco Repository AMP achetype. Verion 2.0.0. We have tried imported the library directly but no luck.

<code>
Unable to get dependency information: Unable to read the metadata file for artifact 'com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar': Cannot find parent: org.sonatype.oss:oss-parent for project: com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.2 for project com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.2
  com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.2

from the specified remote repositories:
  central (https://repo1.maven.org/maven2),
  sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/),
  sonatype-nexus-releases (https://oss.sonatype.org/content/repositories/releases),
  alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public),
  alfresco-public-snapshots (https://artifacts.alfresco.com/nexus/content/groups/public-snapshots),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)

Path to dependency: 
	1) za.co.jumpingbean:demo:amp:1.0-SNAPSHOT
	2) org.alfresco:alfresco-repository:jar:5.0.c

</code>

**Comment by slanglois** [comment]
That's weird. Both concurrentlinkedhashmap-lru and org.sonatype.oss:oss-parent can be found on Maven Central, and have nothing to do with Alfresco. There is no reason why it couldn't download them.
Would you have connection problems maybe?
Can you try deleting the corresponding folders in your local Maven repo, so that they are re-downloaded properly, hopefully? 
Looking at the full log will help, because it will show which URLs it tries to downoad from, and one of them should look like https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/3/oss-parent-3.pom

**Comment by mxc** [comment]
Hi slanglois,

Thanks for the reply. I have deleted the org.sonatype.oss folder and get the same error. I have tried deleting the entire .m2 repository with no luck. I also try to manually install the com.google.com.concurrentlinkedhasmap:concurrentlinkedhashmap-lru:jar:1.2 jar but no luck.

Here is what I get above the error when I delete and then attempt to download again.

<code>
Downloading: http://oss.sonatype.org/content/groups/sourceforge//org/sonatype/oss/oss-parent/3/oss-parent-3.pom
178b downloaded  (oss-parent-3.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://oss.sonatype.org/content/groups/sourceforge//org/sonatype/oss/oss-parent/3/oss-parent-3.pom
178b downloaded  (oss-parent-3.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING
</code>

I have been searching for ways to disable checksum checking just to see if ti would work but haven't found a way to do that yet. I get a similar error if I try 2.1.0, except its for the maven plugin.

<code>
Downloading: http://oss.sonatype.org/content/groups/public/org/alfresco/maven/plugin/alfresco-maven-plugin/2.1.0/alfresco-maven-plugin-2.1.0.pom
178b downloaded  (alfresco-maven-plugin-2.1.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://oss.sonatype.org/content/groups/public/org/alfresco/maven/plugin/alfresco-maven-plugin/2.1.0/alfresco-maven-plugin-2.1.0.pom
178b downloaded  (alfresco-maven-plugin-2.1.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING
</code>

Any help appreciated. Even a work-around would be great :)

**Comment by mxc** [comment]
I have been searching for ways to disable checksum checking just to see if ti would work but haven't found a way to do that yet. I get a similar error if I try 2.1.0, except its for the maven plugin.

Downloading: http://oss.sonatype.org/content/groups/public/org/alfresco/maven/plugin/alfresco-maven-plugin/2.1.0/alfresco-maven-plugin-2.1.0.pom
178b downloaded  (alfresco-maven-plugin-2.1.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://oss.sonatype.org/content/groups/public/org/alfresco/maven/plugin/alfresco-maven-plugin/2.1.0/alfresco-maven-plugin-2.1.0.pom
178b downloaded  (alfresco-maven-plugin-2.1.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING


Any help appreciated. Even a work-around would be great :)

**Comment by mxc** [comment]
Ok after some more research it appears to be a bug in maven2 with redirects. I have switched to maven3 and it appears to be working. 

thanks

**Comment by slanglois** [comment]
Wow! OK, thanks for letting us know.
We'll keep that in mind the next time it happens :-)
