### ISSUE TITLE
Potentially unwanted settings inherited in SDK projects

### ISSUE THREAD

**Issue by skopf** [Alfresco/alfresco-sdk#328]
There is an inheritance chain as follows:
alfresco-sdk-aggregator -> alfresco-sdk-parent -> Your custom alfresco-sdk based project

There are a couple of settings in the alfresco-sdk-aggregator pom, that should not be inherited into every custom project and that are better moved into the release profile.

These settings are:
- &lt;url&gt;
- &lt;licenses&gt;
- &lt;issueManagement&gt;
- &lt;scm&gt;
- &lt;developers&gt;
- &lt;contributors&gt;

**Comment by mindthegab** [comment]
This is correct. we should move this stuff in the sdk-release profile https://github.com/Alfresco/alfresco-sdk/blob/master/pom.xml#L216

**Comment by gravitonian** [comment]
This one will not be fixed as you cannot put the elements anywhere else than under project elemet, the following can be put in a profile:
<profile>
<id>test</id>
<activation>...</activation>
<build>...</build>
<modules>...</modules>
<repositories>...</repositories>
<pluginRepositories>...</pluginRepositories>
<dependencies>...</dependencies>
<reporting>...</reporting>
<dependencyManagement>...</dependencyManagement>
<distributionManagement>...</distributionManagement>
</profile>

**Comment by mindthegab** [comment]
Not sure why this was closed?  We need to move the "impacting" properties in the SDK release profile so that they don't get inherited. Make sense?

Reopening /cc @skopf

**Comment by gravitonian** [comment]
If you got any idea of where we could put the properties, then I can fix it?

**Comment by skopf** [comment]
Why does the alfresco-sdk-parent inherit from this file anyway ?

**Comment by gravitonian** [comment]
There are some common properties there such as community and enterprise versions used throughout

**Comment by mindthegab** [comment]
As mentioned above, maybe those props can just be moved in the profile with id 'sdk-release' to be found in the sdk-aggregator pom.

**Comment by ohej** [comment]
Since we no longer use a parent pom we can close this issue
