### ISSUE TITLE
Repository WAR Aggregator Failure

### ISSUE THREAD

**Issue by ESWBitto** [Alfresco/alfresco-sdk#329]
Hello,

I'm trying to setup a new instance of Alfresco in the sdk to begin developing for 5.1 CE.

I followed the instructions here:
https://github.com/Alfresco/alfresco-sdk/wiki/Developer-Wiki
and
http://docs.alfresco.com/community/tasks/alfresco-sdk-tutorials-all-in-one-archetype.html

Initial installation procedure:
Step 1:
Command: git clone https://github.com/Alfresco/alfresco-sdk.git
Command: cd alfresco-sdk
Command: mvn clean install -Dmaven.test.skip=true
http://pastebin.com/5JUB30Fb

Step 2:
Command: mvn archetype:generate -Dfilter=org.alfresco:
http://pastebin.com/E1ww6xD7

Step 3:
Command: mvn install
http://pastebin.com/HwZwZ57Z

I'm getting a build failure for the Repository WAR Aggregator and I don't know what I need to do to fix this. 

I've been able to run sdk with the previous version for developing. I wanted to be able to look at 5.1 and start making changes I need to it for production.

**Comment by ESWBitto** [comment]
Never Mind...

I ran out of disk space...issue resolved.

**Comment by ESWBitto** [comment]
I just noticed after successfully installing that this version is NOT for 5.1.

How do I go about obtaining it? Is it available on the SDK in github?

**Comment by ohej** [comment]
We are in the final rounds of testing, but in the mean time it is simply a matter of setting 
`<alfresco.version>5.1.a-EA</alfresco.version>` in your project. 

I have opened #330 to track the default setting for 5.1.a-EA and will close this one.

**Comment by ESWBitto** [comment]
Where do I set this at?

**Comment by ohej** [comment]
http://docs.alfresco.com/community/tasks/alfresco-sdk-upgrading-alfresco-version.html

**Comment by ESWBitto** [comment]
Coolbeans thanks!

**Comment by ESWBitto** [comment]
So I followed the instructions about changing the version and doing the clean ppurge. Everything went ok until I ran run.sh to start the project. I get a build Failure at Alfresoc Share AMP Module.
