### ISSUE TITLE
Set default version to 5.1.a-EA

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-sdk#330]
`alfresco.community.default.version` needs to be set to 5.1.a-EA if all tests proves to be successful. Otherwise we keep it on 5.0.d for 2.1.1

**Comment by gravitonian** [comment]
Updating to Community version 5.1.b-EA and Enterprise version 5.0.2.1

**Comment by gravitonian** [comment]
Tracked by: https://issues.alfresco.com/jira/browse/DEVPLAT-333
