### ISSUE TITLE
Using Netbeans IDE

### ISSUE THREAD

**Issue by ESWBitto** [Alfresco/alfresco-sdk#333]
Is there a way to use Netbeans instead of eclipse for the Alfresco-sdk project? 

Personal Preference is really what it comes down to and also if there has been any issues with using springloaded on netbeans.

**Comment by ohej** [comment]
In theory it should just work - NetBeans has decent support for Maven, but we have not tested it

**Comment by ESWBitto** [comment]
The reason I ask is because when I go to create a maven project the Repository url defaults to http://repo.maven.apache.org/maven2/

Instead of the url of http://repo1.maven.org/maven2/archetype-catalog.xml

I don't know if there is a difference, but when I load the project in netbeans using the default url I get a bunch of extra stuff I don't know if it would work the same as the 2nd url.

**Comment by ohej** [comment]
I would suggest you create the project from the command line, both Eclipse, IntelliJ and NetBeans seems to have some weirdness connected to creating new projects from archetypes. Examples that comes to mind:
Eclipse needs to either refresh the whole archetype catalog, or have it spoon fed directly
NetBeans had some weird issues last time I tried where it would abandon the process in the middle of creation, leaving you with half a project
IntelliJ needs to have the groupId, artifactId AND repository url entered for the archetype before you can create a project

All in all, it should work once you know the right recipe for the specific IDE, but it takes 20 seconds to do it from a terminal so it's usually not worth the trouble ;)

``mvn archetype:generate -Dfilter=org.alfresco:`` is your friend :)

**Comment by ESWBitto** [comment]
Thank you for the information. I have been using this link to always start a project. 
https://www.youtube.com/watch?v=utYZaVe9Nd0
(Which I think you made)

So going forward I'll just do it via command line. Since I have the repository already downloaded in /root/.m2/repository

Now to see if springloaded works :D

**Comment by ohej** [comment]
I usually recommend doing the creation from the command line, I've seen both Eclipse and IntelliJ crash or hang because it needs to download a lot of artifacts. In the official documentation (http://docs.alfresco.com/community/concepts/alfresco-sdk-getting-started.html) we recommend creating and starting the project from the command line first, then move on to import it into your IDE. This way you make sure that all the underlying stuff is working correctly. 

In any case, are we good to close this issue?

**Comment by ESWBitto** [comment]
Yes
