### ISSUE TITLE
Unable to run automation with the latest firefox browser 

### ISSUE THREAD

**Issue by cabaceira** [Alfresco/alfresco-sdk#334]
Hi, i'm trying to use the share-po integrated tests but i have an issue with the firefox version i'm using (40.0.3). 

The only way i could run my automated tests was by removing the grid from the build.

 mvn -Dtest=TestPlan1 test -Dwebdrone.local.grid=false -Dwebdrone.browser=FireFox

I've checked this with Michael Suzuki and this should be checked.

**Comment by michaelsuzukisagi** [comment]
We will need to update to the latest webdrone 2.10, which uses the latest selenium library (2.47.1).

**Comment by ohej** [comment]
We don't bundle the PO tests with the SDK anymore, so I'm closing this one.
