### ISSUE TITLE
Preserve the manifests provided in the Wars.

### ISSUE THREAD

**Issue by covolution** [Alfresco/alfresco-sdk#335]
The Share Manifest.mf includes version and library information.  We need to ensure the SDK uses the one supplied in the War and doesn't generate its own one. See ACE-4325

**Comment by mindthegab** [comment]
Especially for Alfresco 5.1 (whose Share module system and logic relies on a proper MANIFEST.MF) we should make sure we never change it in the SDK.

Ideally this should be much easier in the 3.0.0 branch since we'll move away completely from dev time WAR overlay.

**Comment by ohej** [comment]
Since we don't do overlays anymore (leveraging MMT in the plugin to install AMPs) this issue is fixed in 3.0
