### ISSUE TITLE
Location of License files in archetype genertaed projects

### ISSUE THREAD

**Issue by skopf** [Alfresco/alfresco-sdk#337]
According to this wiki page
https://wiki.alfresco.com/wiki/AMP_Files
and this documentation
http://docs.alfresco.com/5.0/concepts/dev-extensions-modules-amp-mapping.html
the default mapping for license files is

```
/licenses=/WEB-INF/licenses
```

This is also backed by the comment in the readme file that is placed in the `licenses` folder:

```
This folder (root in the AMP) gets mapped automagically in WEB-INF/licenses
```

**EXPECTED**
The archetype generated project structure looks like this

```
src
 |
 +-- amp
      |
      +-- licenses
      |
      +-- web
           |
           +-- images
           |
           +-- css
```

and the content of the AMP is this:

```
/
|
+-- licenses
|
+-- web
     |
     +-- images
     |
     +-- css
```

**HOWEVER**
The folder `licebses` is **underneath** the folder `web` and thus does not get installed correctly:

```
src
 |
 +-- amp
      |
      +-- web
           |
           +-- licenses
           |
           +-- images
           |
           +-- css
```

**Comment by jgoldhammer** [comment]
Hi @skopf ,

please tell us more about the used SDK version and the type of project (amp based, aio)!
In SDK 3, the license can be placed under <project>/src/main/resources/alfresco/extension/license...

Thanks
Jens

**Comment by skopf** [comment]
Hi @jgoldhammer,
This applies to all project types of the 2.x line of the SDK.
I have not been working with the SDK3 yet.
Important:
licenses != license
license == where the alfresco license file (.lic file) goes to
licenses == where you place text documents that contain the written license terms (e.g. apache-license.txt)

**Comment by ohej** [comment]
With SDK3 AMPs are now an assembly so it is easy to customize the layout of your AMP. Closing
