### ISSUE TITLE
Skipping Tests is not working?

### ISSUE THREAD

**Issue by ruria** [Alfresco/alfresco-sdk#341]
I´m using Repository AMP archetype with eclipse. When I check "Skip Tests" from my configuration, server doesn´t start. It tries to connect to mysql instead of using h2. Is this the intended behaivour?

It took me a long time to note it!

**Comment by gravitonian** [comment]
Hi,

If I run $ mvn clean install -DskipTests=true, it skips tests in both repo-amp project and AIO project.

Please provide detailed step on how to reproduce this on command line.
