### ISSUE TITLE
Upgrade documentation for 2.1.0 to 2.1.1 is wrong

### ISSUE THREAD

**Issue by jrosler** [Alfresco/alfresco-sdk#342]
The doc at http://docs.alfresco.com/5.0/tasks/alfresco-sdk-upgrading-sdkversion-210-211.html states that you can upgrade current sdk 2.1.0 to 2.1.1 by changing the version to the parent sdk in your base project pom. This is not correct. There is a problem with runner/pom.xml.

The 2.1.0 runner/pom.xml alfresco.data.dir was set to
<alfresco.solr.dir>${project.parent.basedir}/${alfresco.data.location}/solr4</alfresco.solr.dir>
and the 2.1.1 runner/pom.xml
<alfresco.solr.dir>${alfresco.data.location}/solr4</alfresco.solr.dir>

the alfresco.data.location in alfresco-sdk-parent-2.1.0.pom
<alfresco.data.location>alf_data_dev</alfresco.data.location>
and the 2.1.1 in alfresco-sdk-parent-2.1.1.pom
<alfresco.data.location>${session.executionRootDirectory}/alf_data_dev</alfresco.data.location>

This causes the alfresco.solr.dir to get set incorrectly to your base directory path twice as it is combined incorrectly.

<alfresco.data.location>${session.executionRootDirectory}/alf_data_dev</alfresco.data.location>
<alfresco.solr.dir>${project.parent.basedir}/${alfresco.data.location}/solr4</alfresco.solr.dir>

You can see the problem if you install an AIO with SDK 2.1.0 and then before running a build updating your project pom.xml to version 2.1.1 and running ./run.sh. solr won't start up because it's config files didn't get copied to the right directory. If you already had already run once with the SDK 2.1.0 before, you can see this by running a purge and then changing the version to 2.1.1.

**Comment by ahmedowian** [comment]
What are you seeing in the logs?

**Comment by ahmedowian** [comment]
What did you do to get around this, @jrosler ?

**Comment by gravitonian** [comment]
See https://issues.alfresco.com/jira/browse/DEVPLAT-380, list what you need to do

**Comment by gravitonian** [comment]
Fixed in 5.0 and 5.1 doc branch
