### ISSUE TITLE
AIO share-amp resource loading bean ID should be dynamic

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#344]
Use the 2.1.0 or 2.1.1 AIO archetype to generate a project accepting all default parameters.

**Expect** the bean for loading resources in ```.../share-amp/src/main/amp/config/alfresco/web-extension/custom-slingshot-application-context.xml``` to have the following id:  ```${project.artifactId}.resources```

**Actually** it has the expanded name: ```org.alfresco.share-amp.resources```.

**Rational** for this is that it helps make renaming the generated share-amp modules easier. Also it is consistent with how similar things are done elsewhere in the AIO archetype.

Here is a copy of what is currently generated:
```xml
   <bean id="org.alfresco.share-amp.resources"
         class="org.springframework.extensions.surf.util.ResourceBundleBootstrapComponent">
      <property name="resourceBundles">
         <list>
            <value>alfresco.web-extension.messages.custom</value>
         </list>
      </property>
   </bean>
```

**Comment by binduwavell** [comment]
I should have mentioned that custom-slingshot-application-context.xml in AIO 2.1.0 was renamed to ${project.artifactId}-slingshot-application-context.xml in AIO 2.1.1. I think the comments about the bean id still hold :)

**Comment by gravitonian** [comment]
Tracked by: https://issues.alfresco.com/jira/browse/DEVPLAT-444

**Comment by gravitonian** [comment]
Fixed, all bean ids in repo and share amps now have standard ${artifactId}. prefix.
