### ISSUE TITLE
Oracle JDK 1.8.0_66  EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by lello1978** [Alfresco/alfresco-sdk#347]
I'm using Eclipse Mars 4.5.1
Maven 3.3.3
Alfresco SDK 2.1.1 from latest artifact

If i try to use 64bit Oracle JDK version 1.8.0_66 or version 1.8.0_65 i receive EXCEPTION_ACCESS_VIOLATION only if the parameter -javaagent:"C:\Users\MARCELLO MODICA\Downloads\springloaded-1.2.3.RELEASE.jar" -noverify is setted up.

[hs_err_pid8152.txt](https://github.com/Alfresco/alfresco-sdk/files/39970/hs_err_pid8152.txt)
[replay_pid8152.txt](https://github.com/Alfresco/alfresco-sdk/files/39971/replay_pid8152.txt)

Without springloaded parameter i can do the integration-test and amp-to-war.

Searching for solutions, I added the -XInit parameter but it is too slow for me. With -Xinit, amp-to-war, start without problem in 64bit mode!!!. 
In order to use springloaded , the only solution i found is to use 32bit JDK (same version), and set 1GB in -Xmx JVM parameters. I'm new to alfresco developmnet and i need springloaded to speedup dev. I search in spring repo for different version of JAR springloaded library but the issue appear again.

I did not found any docs about spingloaded JVM compatibility. 

Regards

**Comment by jgoldhammer** [comment]
I am not recommending springloaded at all. It was not working for me until JDK 8.
I am using JRebel in the last weeks and it just works great.

**Comment by lello1978** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}Thanks for response ...I'm try to use it with jdk 1.8.0u66 x64....but it work perfectly with x86 version. Have someone try the latest alfresco sdk with jdk 1.8.0u66 x64?
Regards
Jens Goldhammer --- Re: [alfresco-sdk] Oracle JDK 1.8.0_66  EXCEPTION_ACCESS_VIOLATION (#347) --- Da:"Jens Goldhammer" <notifications@github.com>A:"Alfresco/alfresco-sdk" <alfresco-sdk@noreply.github.com>Cc:"lello1978" <marcello.modica@logconsulting.it>Data:ven, 20/nov/2015 21:59Oggetto:Re: [alfresco-sdk] Oracle JDK 1.8.0_66  EXCEPTION_ACCESS_VIOLATION (#347)I am not recommending springloaded at all. It was not working for me until JDK 8.
I am using JRebel in the last weeks and it just works great.

**Comment by tom-vandepoele** [comment]
This error occurs when you're trying to run the project using Eclipse's **embedded** maven. 

Go to windows -> preferences -> maven -> installations and define an external maven installation. In your runtime configuration, scroll to the bottom of the main tab and select the external maven as your maven runtime.

Works like a charm. Springloaded is great, but grab the latest version from https://github.com/spring-projects/spring-loaded as some of the earlier versions had some problems and didn't auto-reload all resources you'd expect.

**Comment by tanmoybanerjee2003** [comment]
Thank you so much tom-vandepoele for saving my debugging effort. Your suggestion, indeed, worked like a charm !

I was getting "EXCEPTION_ACCESS_VIOLATION" with 64-bit Oracle JDK 1.8. After I changed from embedded Maven to my external Maven 3.3.3, the error vanished.

**Comment by gravitonian** [comment]
Updated the SDK 2.1 Docs (Alfresco 5.0) and the SDK 2.2 Docs (Alfresco 5.1) with information on how to configure and use the external Maven installation in Eclipse.
