### ISSUE TITLE
Wrong order of resource loading in RAD Tomcat

### ISSUE THREAD

**Issue by skopf** [Alfresco/alfresco-sdk#350]
Resources in the AMP overwrite resources with the same name in the WAR.

But this does not work in the Tomcat RAD environment that we start. In this environment, we use the file `/tomcat/context.xml` to define an `extraResourcePaths`. But these paths are searched *after* the docBase. So resources in the amp can never overwrite resources in the `docBase`.

Instead, we should point the `docBase` to an empty directory and list the docBase in `extraResourcePaths` *after* the resources of the amp:
```
<Context docBase="${project.basedir}/tomcat/empty_doc_base" path="${alfresco.client.contextPath}">

    <Resources className="org.apache.naming.resources.VirtualDirContext" extraResourcePaths="/=${project.build.directory}/${project.build.finalName}/web,/=${alfresco.client.war.folder}" />
    ...
```

**Comment by gravitonian** [comment]
Tracked by https://issues.alfresco.com/jira/browse/DEVPLAT-442

**Comment by gravitonian** [comment]
Fixed
