### ISSUE TITLE
Alfresco 5.0.3: missing artifact 'alfresco-authorised-users', unable to build

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-sdk#357]
Could not find artifact org.alfresco.authorization:alfresco-authorised-users:jar:5.0.0.2

I can see the 4.2.5.1 and 4.2.5.3 in the alfresco maven nexus (https://artifacts.alfresco.com), but not this version.

Could you ensure the required artifact ends up where it should?

Thanks.

**Comment by ohej** [comment]
The artifact should now be available, can you please re-test and let me know if this is sorted out?

The artifact might not show up if you search for it manually via the web interface (it takes a little before it gets indexed), but Maven should be able to pull the dependency down now.

**Comment by tom-vandepoele** [comment]
I can confirm the artifact is now available, managed to download it. The indexes are indeed out-of-sync, but I'm sure they'll catch up.

Thank you. I can build the 5.0.3 project now.
