### ISSUE TITLE
Alfresco 5.0.3: missing authorization-select-SqlMap.xml

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-sdk#358]
While trying to run a 5.0.3 project I'm getting the error: 

Failed to get resource: alfresco/ibatis/#resource.dialect#/authorization-select-SqlMap.xml

The resource exists for the other dialects, but not for **org.hibernate.dialect.H2Dialect**.

I'll use a manual workaround by copying them over for now, but this should really be fixed in the corresponding alfresco jar.

**Comment by ohej** [comment]
Which version of the SDK are you using?

**Comment by tom-vandepoele** [comment]
2.1.1

**Comment by ohej** [comment]
Yes, that's a known bug since we added a table in 5.0.2/5.0.3/4.2.5. As a result we have produced a new jar called alfresco-repository.jar:h2scripts. 

However, the downside is that you will have to go and include this artifact manually for the tomcat plugin. We've fixed this in the upcoming SDK 2.2 release, but for now you can address this by adding:

                        <dependencies>
                            <dependency>
                                <groupId>org.alfresco</groupId>
                                <artifactId>alfresco-repository</artifactId>
                                <version>${alfresco.version}</version>
                                <classifier>h2scripts</classifier>
                                <exclusions>
                                    <exclusion>
                                        <groupId>*</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                        </dependencies>

To `runner/pom.xml` (if you're using all-in-one).

If you're using the AMP archetype, you can add this to the pom.xml:

	<build>
	      <plugins>
	        <plugin>
	            <groupId>org.apache.tomcat.maven</groupId>
	            <artifactId>tomcat7-maven-plugin</artifactId>
	            <version>${maven.tomcat.version}</version>
	            <dependencies>
	                <dependency>
	                    <groupId>org.alfresco</groupId>
	                    <artifactId>alfresco-repository</artifactId>
	                    <version>${alfresco.version}</version>
	                    <classifier>h2scripts</classifier>
	                    <exclusions>
	                        <exclusion>
	                            <groupId>*</groupId>
	                            <artifactId>*</artifactId>
	                        </exclusion>
	                    </exclusions>
	                </dependency>
	            </dependencies>
	        </plugin>
	      </plugins>
	</build>


You can see complete examples here: https://github.com/Alfresco/alfresco-sdk/blob/master/archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/runner/pom.xml#L69 and here https://github.com/Alfresco/alfresco-sdk/blob/master/archetypes/alfresco-amp-archetype/src/main/resources/archetype-resources/pom.xml#L69

**Comment by tom-vandepoele** [comment]
Ok, that now works, I'm getting the following error:

"Bootstrap failed: org.apache.commons.collections.functors.* unsafe serialization classes found in classpath."

Seems the problem is related to springloaded, if I start up without the java agent alfresco starts normally.

**Comment by toonconvents** [comment]
Same problem here, Tom.

Ole, Google cache found the following issue: https://webcache.googleusercontent.com/search?q=cache:MWNs4q4-i3UJ:https://issues.alfresco.com/jira/browse/ACE-5004+&cd=1&hl=en&ct=clnk&gl=au

Seems to be related but this is in 5.1... Any news on when this will be fixed for 5.0.3?
We will not be moving to 5.0.3 before this is fixed.

**Comment by gravitonian** [comment]
The "Bootstrap failed: org.apache.commons.collections.functors.* unsafe serialization classes found in classpath." problem can be fixed by not running with Spring Loaded in MAVEN_OPTS. See also http://docs.alfresco.com/5.1/tasks/alfresco-sdk-install-maven-opts.html

**Comment by tom-vandepoele** [comment]
I found an easy workaround for the unsafe serialization bug, see https://github.com/Alfresco/alfresco-sdk/issues/369

**Comment by patriciay-appno** [comment]
Hi, I have recently upgraded from 5.0.2 to 5.0.3 and I'm having this issue.

I have added the dependency to the runner/pom.xml as I'm running the all-in-one archetype, but I'm still getting the same error.

Any suggestions? thanks

**Comment by gravitonian** [comment]
See: http://docs.alfresco.com/5.1/tasks/alfresco-sdk-upgrading-alfresco-version-SDK-211-501-or-502-to-503.html

**Comment by patriciay-appno** [comment]
Hi @gravitonian , thanks for the quick response.

I have followed that steps but still getting the following error when I run mvn package

 org.alfresco.error.AlfrescoRuntimeException: 06190000 Script [ classpath:alfresco/dbscripts/create/${db.script.dialect}/AlfrescoCreate-AuthorizationTables.sql ] can't be found for class org.hibernate.dialect.H2Dialect

Thanks
