### ISSUE TITLE
Add dependency to alfresco-share-services for repository modules

### ISSUE THREAD

**Issue by loftux** [Alfresco/alfresco-sdk#361]
From 5.1 you will need the alfresco-share-services as a dependency. 
Possibly the amp version for embedding, but also the "classes" version.

If you are unaware of this, it just happens to works since the alfresco-share-services is embedded in the alfresco.war by default, but I'm not sure that is the intention. See https://issues.alfresco.com/jira/browse/ALF-21558
 
    <dependency>
            <groupId>org.alfresco</groupId>
            <artifactId>alfresco-share-services</artifactId>
            <version>${alfresco.version}</version>
            <classifier>classes</classifier>
            <scope>compile</scope>
    </dependency>

**Comment by gravitonian** [comment]
Not a bug as per https://issues.alfresco.com/jira/browse/ALF-21558 resolution.

**Comment by loftux** [comment]
In this case you actually should ad it as a dependency, but as provided/compile since this will ease development. Else it will not show up in dependency tree. Please re-open.

**Comment by douglascrp** [comment]
Is there anything Alfresco can do about this issue?
Please, check this issue https://github.com/Alfresco/alfresco-sdk/issues/382
