### ISSUE TITLE
Themes for Enterprise SDK overlay

### ISSUE THREAD

**Issue by alex4u2nv** [Alfresco/alfresco-sdk#363]
Looks like the themes for the Enterprise SDK overlay contains community images and possibly styles.

share/overlays/org.alfresco.share-5.0.1/themes/*/images/logo.png is currently "Alfresco Community"
![logo](https://cloud.githubusercontent.com/assets/40564/13206281/9b7aabc4-d8c8-11e5-92ba-78a85d26ccc5.png)

**Comment by jgoldhammer** [comment]
@alex4u2nv ,

can you please add more information here?
Please use the new template in https://github.com/Alfresco/alfresco-sdk/blob/master/ISSUE_TEMPLATE.md.

If you do not react after 7 days, this ticket will be closed

**Comment by ohej** [comment]
I have not been able to reproduce this with SDK3, closing
