### ISSUE TITLE
Update service-context.xml to use filterable property for moduleId rather than bare reference

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#364]
When creating an AIO project from the 2.2.0-SNAPSHOT SDK, demo-repo-amp/src/main/amp/config/alfresco/module/demo-repo-amp/context/service-context.xml has a bare value for moduleId rather than a filterable property like ${project.artifactId}, which is what we have in module.properties.

Since part of the 2.2.0 SDK is create clearer artifactIds for our projects, we likely should reference the filterable property so that we reduce the number of steps required to rename the artifactId manually after the project is created.

**Comment by gravitonian** [comment]
Fixed
