### ISSUE TITLE
sdk-2.2.0 generated AIO fails to build with -Penterprise

### ISSUE THREAD

**Issue by tullo** [Alfresco/alfresco-sdk#368]
1. Generate an all-in-one project based on sdk-2.2.0
2. Run `mvn install`
3. SUCCESS

But building with enterprise artefacts fails: (works for me with previous sdk)
`mvn clean install -Penterprise,purge`

[ERROR] Failed to execute goal on project alfresco-nukidoc-repo-amp: Could not resolve dependencies for project com.redpill-linpro:alfresco-nukidoc-repo-amp:amp:1.0-SNAPSHOT: Failed to collect dependencies at org.alfresco:alfresco-enterprise-repository:jar:5.1 -> org.alfresco.authorization:alfresco-authorised-users:jar:5.1.0.2: Failed to read artifact descriptor for org.alfresco.authorization:alfresco-authorised-users:jar:5.1.0.2: Could not transfer artifact org.alfresco.authorization:alfresco-authorised-users:pom:5.1.0.2 from/to alfresco-internal (https://artifacts.alfresco.com/nexus/content/groups/internal): Access denied to: https://artifacts.alfresco.com/nexus/content/groups/internal/org/alfresco/authorization/alfresco-authorised-users/5.1.0.2/alfresco-authorised-users-5.1.0.2.pom , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by ohej** [comment]
It seems the org.alfresco.authorization:alfresco-authorised-users:jar:5.1.0.2 wasn't released into the private repository, I've asked our build team to make sure it's available ASAP. I'll report back once it's available. Apologies for the inconvenience!

**Comment by ohej** [comment]
The artifact should now be available. You might need to use the -U flag in maven (i.e `MAVEN_OPTS="-Xms256m -Xmx1524m -XX:PermSize=300m" mvn install -Prun,enterprise -U`) to force Maven to update and have a second look for the artifact. Let me know if this works.

**Comment by tullo** [comment]
The Enterprise build works now too! Thanks
