### ISSUE TITLE
5.1.e - SDK - springloaded - unsafe serialization classes found in classpath

### ISSUE THREAD

**Issue by loftux** [Alfresco/alfresco-sdk#369]
With the 5.1.e the RAD is broken.  I could not find any other issue here open to track this even if it seem to be known (references in run.sh).
I opened an issue https://issues.alfresco.com/jira/browse/ALF-21568 since this seem to be related to changes in Alfresco. With this issue it can be cross referenced.

**Comment by tom-vandepoele** [comment]
Was mentioned in https://github.com/Alfresco/alfresco-sdk/issues/358
See the documentation here: http://docs.alfresco.com/5.1/tasks/alfresco-sdk-install-maven-opts.html

Currently springloaded only works for the Share AMP archetype, not the Repo or the all-in-one.

**Comment by ohej** [comment]
We're investigating this further, we'll update as we go along. 
Thanks for the workaround, it would be better to put this context file in `src/test/resources/alfresco/extension` - this way the workaround doesn't make it into the final artifacts and won't get deployed into production

**Comment by tom-vandepoele** [comment]
Ah, yes, for the repo-amp this is correct. For the all-in-one archetype, if you put it in the repo war project next to the dev-log4j.properties it only gets included if you use the 'run' profile. (I've tested this)

**Comment by infiniti2510** [comment]
I tried this workaround and I am getting errors on startup. I have overridden  the "unserializerValidatorBootstrap" bean and have spring loaded added "C:\Program Files\Java\jdk1.8.0_45\bin\java" -Xms1024m -Xmx4096m -XX:PermSize=1024m -javaagent:C:\Development\libs\springloaded-1.2.3.RELEASE.jar -noverify -Dmaven.home=C:\Development\apache-maven-3.2.5"


On startup, I get the following:

 2016-03-30 10:07:13,141  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Starting 'Search' subsystem, ID: [Search, managed, solr4]
 2016-03-30 10:07:13,467  WARN  [management.subsystems.ChildApplicationContextFactory$ChildApplicationContext] [localhost-startStop-1] Exception encountered during context initialization - cancelling refresh attempt
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'search.solrTrackingComponent' defined in URL [jar:file:/C:/Development/IntelliJ%20Space/ncaoc/ncaoc/runner/target/tomcat/webapps/repo/WEB-INF/lib/alfresco-enterprise-repository-5.1.jar!/alfresco/subsystems/Search/common-search-enterprise-context.xml]: Cannot resolve reference to bean 'search.solrShardRegistry' while setting bean property 'shardRegistry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'search.solrShardRegistry' defined in URL [jar:file:/C:/Development/IntelliJ%20Space/ncaoc/ncaoc/runner/target/tomcat/webapps/repo/WEB-INF/lib/alfresco-enterprise-repository-5.1.jar!/alfresco/subsystems/Search/common-search-enterprise-context.xml]: Invocation of init method failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.alfresco.ibatis.SerializableTypeHandler$DeserializationException: java.lang.ClassNotFoundException: org.alfresco.service.cmr.repository.StoreRef

**Comment by tom-vandepoele** [comment]
Starting up the run twice in a row gets me the same error with the 2.2.0 SDK.
Haven't had the time to report this yet. (Should be a new ticket)

My workaround for that is to always do a purge before you run.

**Comment by toonconvents** [comment]
Hi @ohej and @tom-vandepoele , any news on a workable workaround as purging before every run is not realistic (huge overhead) for us...

**Comment by gravitonian** [comment]
Hi,

We had a problem a year ago similar to not being able to restart after an initial start. It was not possible to upgrade the H2 driver. This is from SDK 2.1.1:

`        
        <h2.version>1.4.185</h2.version>
`
We now use:
`
<h2.version>1.4.190</h2.version>
`
Maybe this new version also got problems.

Try using 1.4.185 in parent POM for AIO or POM for Repo AMP.

**Comment by toonconvents** [comment]
Hi @gravitonian , I tried using that version of H2 but the same error occurs unfortunately...

**Comment by gravitonian** [comment]
Must be some other error then (kind of make sense as we tested quite a lot with multiple restarts without purge). I assume you did purge, then tried restart multiple times? 

Can you provide exact steps to reproduce? Similar to:

1) Generate a 2.2.0 SDK AIO project
2) do this
3) and this
3) expected this, got this....

And do a print of mvn --version

**Comment by ohej** [comment]
I fear this is spring loaded related. I encountered this issue previously but at some point the error went away and I haven't been able to reproduce it ever since (even with spring loaded enabled). 

Can you see if this error reproduces without spring loaded?
We'll need some details about your environment, java version, maven, spring loaded version.. running from terminal? Eclipse? IntelliJ? Please provide as much info as possible so we can try to reproduce

**Comment by toonconvents** [comment]
@gravitonian and @ohej 
I just created a brand new 2.2.0 SDK AIO project.
Changed the run.sh to be as follows:
`springloadedfile=~/.m2/repository/org/springframework/springloaded/1.2.3.RELEASE/springloaded-1.2.3.RELEASE.jar

if [ ! -f $springloadedfile ]; then
mvn validate -Psetup
fi
MAVEN_OPTS="$MAVEN_OPTS -javaagent:$springloadedfile -noverify -Xms1G -Xmx3G" mvn clean install -Prun,enterprise`

Added the fix for the serialisation error by adding the file bootstrap-context.xml under repo/src/main/resources/alfresco/extension with the following content:
`<?xml version='1.0' encoding='UTF-8'?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd">
    
    <bean id="unserializerValidatorBootstrap" abstract="true"/>
</beans>`

And on second run I have the java.lang.ClassNotFoundException again...

**Comment by tom-vandepoele** [comment]
After further investigation, I can state with certainty that the issue only occurs if you use the '**enterprise**' profile. If you leave that out, you can restart as many times as you'd like without ever seeing the issue.

I'm going to see if I can get some sort of workaround operational so I can continue using the enterprise profile.

**Comment by toonconvents** [comment]
Hi Guys, any progress on this?
Cheers,
Toon

**Comment by giuseppeurso-eu** [comment]
Hi all,
the suggested workaround works for me.
My development environment does not include the alfresco SDK but only a standalone tomcat+alfresco+springloaded+ide).

1) Create bootstrap-context.xml under tomcat/shared/classes/alfresco/extension/bootstrap/  with the following content:
```
<?xml version='1.0' encoding='UTF-8'?>
<beans xmlns="http://www.springframework.org/schema/beans" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd">
 
<bean id="unserializerValidatorBootstrap" abstract="true"/>
</beans>
```
2) Add the springloaded javaagent opt in the tomcat/bin/setenv.sh 
`JAVA_OPTS="${JAVA_OPTS} -javaagent:/some/path/springloaded-1.2.6.RELEASE.jar"`
3) In tomcat/webapps/alfresco/WEB-INF/classes/ create a symlink to your project classpath (i.e my-project/target/classes) 
4) Start tomcat

Here is my stack:
- Fedora 24 x86_64
- Alfresco Enterprise 5.1.0.1
- Springloaded 1.2.6.RELEASE
- JDK 1.8.0_25 Oracle
- Maven 3.2.3

Note: after Tomcat is started, sometimes you might see a numbers of deserialization tries in the stacktrace:
`org.springframework.extensions.webscripts.WebScriptException: 07040000 Wrapped Exception (with status template): 07040000 Failed to deserialize`

**Comment by toonconvents** [comment]
@tom-vandepoele Did you find a workable solution in the end?

Cheers,
Toon

**Comment by tom-vandepoele** [comment]
@toonconvents No, not for enterprise. Since springloaded only reloads java classes I'm no longer using it for 5.1 projects.

**Comment by giuseppeurso-eu** [comment]
@tom-vandepoele @toonconvents 
The dummy bootstrap bean works for me with alfresco enterprise 5.1.0.1 but only if I start Tomcat with the -Xdebug and -Xrunjdwp in the java options  (see my comment above).

**Comment by jgoldhammer** [comment]
@ohej 
What do you think? Springprofile is not supported anymore in SDK 3, right?
If yes, we can close the ticket and should write a hint in the documentation.

Thanks
Jens

**Comment by ohej** [comment]
We have not had any updates on these issues in a long time. With SDK3 we have support for Hotswap Agent and JRebel which does not suffer from this issue.

As much as I'd love to continue supporting Spring Loaded, there is simply too many issues with it:
Unsafe serialisation, issues with multiple values in content model (for example tags) and we have seen too many H2 DB corruption.

Overall I will close all Spring Loaded related issues and refer to Hotswap Agent as a free alternative and JRebel for a commercial alternative.
