### ISSUE TITLE
Can you add a profile for reindex?

### ISSUE THREAD

**Issue by jrosler** [Alfresco/alfresco-sdk#372]
This is an enhancement request.

Can you add a profile for causing the AIO local solr to reindex? Using -Ppurge kills all the content. I'd like a simple way to cause a reindex like -Preindex rather than manually removing the local index.

**Comment by tom-vandepoele** [comment]
This should do it for you in the 2.2.0 SDK:

Copy the alfresco.solr.dir, alfresco.solr.data.dir and alfresco.solr.home.dir properties from the solr-config to the main project pom.xml, add profile below to the build profiles, then execute a mvn clean with the "re-index" profile on any of the projects.

```
<profile>
	<id>re-index</id>
	<build>
    	<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
	            	<filesets>
	            		<!--  solr: clean out the indexes, the models and the internal db -->
						<fileset>
							<directory>${alfresco.solr.data.dir}/index/workspace/SpacesStore/</directory>
							<includes>
								<include>**/*</include>
							</includes>
						</fileset>
						<fileset>
							<directory>${alfresco.solr.data.dir}/index/archive/SpacesStore/</directory>
							<includes>
								<include>**/*</include>
							</includes>
		  				</fileset>
		  				<fileset>
		    				<directory>${alfresco.solr.home.dir}/alfrescoModels/</directory>
		    				<includes>
	                    		<include>**/*</include>
	                       	</includes>
		  				</fileset>
		  				<fileset>
		    			<directory>${alfresco.solr.data.dir}/content/</directory>
		    			<includes>
	                    	<include>**/*</include>
	                    </includes>
		  				</fileset>
	                </filesets>
				</configuration>
			</plugin>
		</plugins>
	</build>
</profile>
```

**Comment by gravitonian** [comment]
Hi,

It might go even quicker to re-build if you don't delete the cached content store on the Solr side. So basically don't delete /content. See: https://docs.google.com/document/d/1DMNeMmZf6r4tKB0zYjWBx84OMWfINfR0UpVsPzyop9Q/pub#h.6x85kkuxz3wp

**Comment by jrosler** [comment]
Thanks.
