### ISSUE TITLE
All-In-One Runner: Spring context loaded multiple times

### ISSUE THREAD

**Issue by rpiccoli** [Alfresco/alfresco-sdk#373]
When deploying Alfresco to a regular Tomcat, it works as expected.

When starting using the SDK runner (even with Spring Loaded disabled), the spring context is loaded multiple times.

By doing that some problems happens, for example, if using Spring Integration, channel subscribers are registered more than once and the dispatchers start to use failover strategies, while failing fast on real deployment.

**Comment by ohej** [comment]
This is due the fact that SDK2 copies all resources into both `target/classes` and `target/test-classes`. On top of that we use the virtual class paths in Tomcat to load up resources from both locations. The result is that all beans and classes are actually loaded twice.

There is no obvious way to address this in the SDK2.x context, but with the new approach we have in SDK3 this is no longer an issue.
