### ISSUE TITLE
Alfresco API endpoint not configured

### ISSUE THREAD

**Issue by alex4u2nv** [Alfresco/alfresco-sdk#377]
The Alfresco API endpoint configuration override is missing in the shareamp 2.2.0 archetype generation of src/test/resources/alfresco/web-extension/share-config-custom.xml
This also affects the All-In-One share configurations; although correct configurations are in the packaged share-config-custom.xml.sample.

```
 <endpoint>
                <id>alfresco-api</id>
                <parent-id>alfresco</parent-id>
                <name>Alfresco Public API - user access</name>
                <description>Access to Alfresco Repository Public API that require user authentication.
                    This makes use of the authentication that is provided by parent 'alfresco' endpoint.</description>
                <connector-id>alfresco</connector-id>
                <endpoint-url>${alfresco.repo.url}/alfresco/api</endpoint-url>
                <identity>user</identity>
            </endpoint>
```

**Comment by jgoldhammer** [comment]
@alex4u2nv thanks for the info. I can reproduce that the entry is missing in the share-config-custom.xml, but I cannot see this configuration in the sample file (share-config-custom.xml.sample)...

Thanks
Jens

Thanks,
Jens

**Comment by ohej** [comment]
The endpoint is included in SDK3
