### ISSUE TITLE
Alfresco 5.1 Maven build fails when including AOS overlay

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-sdk#380]
SDK 2.2, AOS 1.1

For reference, see https://issues.alfresco.com/jira/browse/MNT-15861

Temporary workaround is to manually edit your local m2repo copy (m2repo\org\alfresco\aos-module\alfresco-aos-module\1.1) of the alfresco-aos-module-1.1.pom and change

`<alfresco.version>5.1-SNAPSHOT</alfresco.version>`

to 

`<alfresco.version>5.1</alfresco.version>`

Or you could wait for alfresco-aos-module 1.1.1

**Comment by jgoldhammer** [comment]
@tom-vandepoele , can you verify with the updated information from the ticket https://issues.alfresco.com/jira/browse/MNT-15861 
Thanks

**Comment by jgoldhammer** [comment]
In Alfresco SDK 3 you can integrate the alfresco-sos-module 1.1.3 by using following addition:

```
 <moduleDependency>
            <groupId>org.alfresco.aos-module</groupId>
            <artifactId>alfresco-aos-module</artifactId>
            <version>1.1.3</version>
            <type>amp</type>
 </moduleDependency>
```

So I will close the issue for now
