### ISSUE TITLE
Using searchService for integration tests

### ISSUE THREAD

**Issue by magp3** [Alfresco/alfresco-sdk#383]
I can't figure out how to do this, help needed!

**Comment by magp3** [comment]
I get connection refused errors. I'm assuming solr is not running..

**Comment by jgoldhammer** [comment]
Do you run a repo amp project? If yes, you can only use lucene as build only variant... In the new sdk version 3, it will be possible to run solr with a Repo amp project...

**Comment by magp3** [comment]
@jgoldhammer I'm running a all-in-one project.. The solution is to wait for version 3? When will that be?

**Comment by jgoldhammer** [comment]
All in One should work. Please post environment Infos here, logfiles etc. and check your running processes...

**Comment by jgoldhammer** [comment]
And please use stackoverflow or alfresco Forum to get help...

**Comment by magp3** [comment]
@jgoldhammer The issue is that solr is not started when I run integration tests.. Is this something I can fix with configuration?

**Comment by jgoldhammer** [comment]
in your case, solr should be started out of the box, but I have no details from you... Please check logfiles, maybe there is an error why it has not been started...

**Comment by gravitonian** [comment]
If you are running a test such as the sample one here: aio-220/aio-220-repo-amp/src/test/java/org/alfresco/tutorial/demoamp/test/DemoComponentTest.java

Then this is loading the Alfresco Spring context and then the test is run. So there is no Tomcat server running, and then no Solr running.

For SDK 3 we are looking at different alternatives for Spring Context tests and Remote Tests (what you need). I am playing with a project here (so you can have an idea): https://github.com/gravitonian/integration-test-runner-sdk3

**Comment by magp3** [comment]
@gravitonian Thanks, that explains things!

**Comment by magp3** [comment]
Is there an estimate for when SDK 3 is ready?

**Comment by gravitonian** [comment]
Still a couple of months to go I think

**Comment by ohej** [comment]
We have previously floated October around as a potential time, but I think November is more realistic. There are still a few things we need to implement and get feedback on.
