### ISSUE TITLE
Authentication Bearer

### ISSUE THREAD

**Issue by falcon-friend** [Alfresco/alfresco-sdk#384]
Hello everyone,

I started using Alfresck SDK the latest version. I am trying customise authentication in Alfresco. I configured a new authentication using documentation: [http://docs.alfresco.com/5.1/references/dev-extension-points-authentication.html](url) but I want to provide JWT Token base authentication. 
When I try to pass in a http header: Authorization: Bearer token it is cought by BasicHttpAuthenticatorFactory that it is not authorized.
How to pass my own bearer token and then invoke: public Authentication authenticate(Authentication authentication) throws AuthenticationException method?

**Comment by jgoldhammer** [comment]
I think, this is a question for the alfresco forum or stackoverflow.
Please close the ticket here.
Thanks.
