### ISSUE TITLE
How to replace share files, like favicon.ico, when using the share archetype version 3.0 beta 1

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#389]
With 2.2.0 and older versions, using AMPs, it was easy to replace files inside the share.war, like favicon.ico

How can I do the same when using the new archetype, generation JARs instead of AMPs?

**Comment by gravitonian** [comment]
Added support for overriding out-of-the-box web resources, such as the favicon.ico, see the src/main/assembly dir for more info. Specifically have a look at the /web/README.md file for more information. To test this you will need to pull latest SNAPSHOT and build the SDK and run with 3.0-SNAPSHOT.

Let me know if it works as you expected, and we can then close the issue

**Comment by douglascrp** [comment]
He @gravitonian 

I've just tried it and it works as described.
Thank you so much for taking the time to fix this.
This can be closed.

But now I have another question (maybe for another issue? I'm not sure)
If I have this requirement to replace OOTB files, I won't be able to use jar modules, right?
Are AMPs the only way to go in this case?

**Comment by gravitonian** [comment]
Hi,

You are right, JAR modules cannot be used by themselves. However, the project will be packaged up as a JAR and live inside the AMP, except for the stuff that you override. So you get the benefits of JARs anyway. What I mean is that you will not have the /config directory exploded over the WAR, possibly overwriting files, and making uninstalls more difficult.
