### ISSUE TITLE
alfresco-global.properties from repo module is packaged in released WAR

### ISSUE THREAD

**Issue by manoswerts** [Alfresco/alfresco-sdk#397]
# Expected
Using the SDK 2.2.0, in the `repo` module, you can find `src/main/properties/local/alfresco-global.properties`. This file should be loaded only when running Alfresco with the embedded Tomcat (i.e. it should not be packaged in the WAR, nor should it be active when running tests).

# Actual
The file *IS* packaged in the WAR and therefore automatically released to our clients.

# Workaround
1. Move the file to `src/test/properties/local/alfresco-global.properties` in the `repo` module. It will not be packaged in the WAR anymore.
2. Add the line `${project.parent.basedir}/repo/target/test-classes;` to the virtual classpath in `context-repo.xml` to ensure that it is available when running in the embedded Tomcat:
```
    <Loader className="org.apache.catalina.loader.VirtualWebappLoader"
            searchVirtualFirst="true"
            virtualClasspath="${project.parent.basedir}/repo/target/test-classes;
                                ${project.parent.basedir}/wiley-dcm-repo-ext/target/classes;
                                ${project.parent.basedir}/wiley-dcm-repo-ext/target/amp/config;
                                ${project.parent.basedir}/wiley-dcm-repo-ext/target/test-classes" />
```

**Comment by gravitonian** [comment]
http://docs.alfresco.com/5.1/tasks/alfresco-sdk-advanced-deploying-to-external-environments.html
