### ISSUE TITLE
Rename share-config-custom.xml for testing to share-config-custom-dev.xml (SDK 2.2.0)

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#398]
The share-config-custom.xml located in the src/test/resources/alfresco/web-extension directory will clash with any AMP/JAR project using share-config-custom.xml in web-extension. It will work when deployed to stand-alone Alfresco installation but not from SDK AIO project.

**Comment by jgoldhammer** [comment]
@gravitonian: Is this also valid for Alfresco SDK 3?

**Comment by ohej** [comment]
This should not be an issue in SDK 3.0 as the module specific configs are in JARs by default
