### ISSUE TITLE
Staging repository for SDK 3.0.0-beta-2 disappeared 

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-sdk#399]
Seems https://oss.sonatype.org/content/repositories/orgalfresco-1038/ has been dropped. We need to figure out a way to keep these staging repositories open until we feel good about the release.

Maybe the best approach would be to deploy the betas to our own nexus rather than Maven Central? Needs to be sorted out ASAP.

**Comment by ohej** [comment]
We've released beta-3 on Maven central now.
It turns out that Maven central deleted closed staging repositories after 7 days of inactivity. We have requested they keep them alive a bit longer than that. 

Meanwhile SDK 3.0.0-beta-3 can be found here: https://oss.sonatype.org/content/repositories/orgalfresco-1039/

@zhihailiu can you verify that this works for you?

**Comment by zhihailiu** [comment]
@ohej It works. Thank you!

**Comment by marsv024** [comment]
404 - Repository with ID="orgalfresco-1039" not found... Are they gone again?

**Comment by badluck1024** [comment]
Anyone know where is gone the new orgalfresco repo?

**Comment by ohej** [comment]
Copied from #411

Since Maven Central deletes the staging repositories we have changed our build setup for the SDK.

Releases are now done by default to our own repository (artifacts.alfresco.com) rather than Maven central.

The idea is that we now put all betas and release candidates on our own internal one - the final releases are put on Maven Central.

You can now access 3.0.0-beta-4 using this command:
mvn archetype:generate -DarchetypeCatalog=https://artifacts.alfresco.com/nexus/content/groups/public/archetype-catalog.xml -Dfilter=org.alfresco.maven.archetype:

Please make sure to use the full command.

**Comment by badluck1024** [comment]
@ohej Thank you... Now everything works as expected
