### ISSUE TITLE
Make it possible to inject Tomcat Dependencies from the project

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#400]
Currently the H2 database dependency is hard coded in the Run Mojo. So if you wanted to run with for example MySQL or PostgreSQL it would not be possible.
Add an extra configuration section for the plugin where you can specify tomcat plugin dependencies:

` <plugin>
                <groupId>org.alfresco.maven.plugin</groupId>
                <artifactId>alfresco-maven-plugin</artifactId>

```
            <configuration>
                <enableH2>false</enableH2>
                <tomcatDependencies>
                    <tomcatDependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.32</version>
                    </tomcatDependency>
                <tomcatDependencies>
```

`

**Comment by ohej** [comment]
Ideally we should make it easy to configure the most common external databases via configuration. My idea would be to have `<enableMySQL/>` and `<enablePostgreSQL/>` (or similar naming) in addition to h2. This would hit a lot of use cases.

On top of that, we should support tomcat dependencies as @gravitonian mentioned above. This would allow people who wish to use other databases to still succeed.

**Comment by gravitonian** [comment]
Agree

**Comment by jgoldhammer** [comment]
+1

**Comment by gravitonian** [comment]
FIxed, you can now use the following config to support MySQL;

```
...
 <plugin>
                <groupId>org.alfresco.maven.plugin</groupId>
                <artifactId>alfresco-maven-plugin</artifactId>
                <version>${alfresco.sdk.version}</version>
                <configuration>
                    <alfrescoEdition>community</alfrescoEdition>

                    <enableMySQL>true</enableMySQL>

                    <enablePlatform>true</enablePlatform>
                    <enableSolr>true</enableSolr>
                    <enableShare>true</enableShare>
			...
```

The following has the same effect, using the tomcat dependencies config:

```
...<plugin>
                <groupId>org.alfresco.maven.plugin</groupId>
                <artifactId>alfresco-maven-plugin</artifactId>
                <version>${alfresco.sdk.version}</version>
                <configuration>
                    <alfrescoEdition>community</alfrescoEdition>

                    <!-- We need the flat file H2 database to run the Repo
                    <enableMySQL>true</enableMySQL>
		    -->

                    <tomcatDependencies>
                        <tomcatDependency>
                            <groupId>mysql</groupId>
                            <artifactId>mysql-connector-java</artifactId>
                            <version>5.1.32</version>
                        </tomcatDependency>
                    </tomcatDependencies>

                    <enablePlatform>true</enablePlatform>
                    <enableSolr>true</enableSolr>
                    <enableShare>true</enableShare>...
```

See the following docs for more info on how to set up MySQL etc: http://docs.alfresco.com/5.1/concepts/alfresco-sdk-tutorials-mysql-intro.html

**Comment by jgoldhammer** [comment]
Nice idea to add dependencies this way. 
When reading the configuration names, I have doubt that the configuration option will be understood correctly... Why? It sounds like you can enable mysql for the repository, but you will only add the mysql driver jar file. This will not change the configuration option of the alfresco-global.properties, right?

Nevertheless I would always enable all database jars from mysql, postgres and h2 at all - does it matter to have them on the classpath? This way a SDK user/developer has to configure the pom.xml and the alfresco-global.properties to change to the database he wants. Sounds like configuration over convention...

Current code allows only to "enable" one database jar (https://github.com/Alfresco/alfresco-sdk/commit/04fe0678d75283bdae36efb22d7bafdebcebbbb7#diff-b409191d33de95e7e38b95760e6d7ba8R775)

What do you think?

**Comment by gravitonian** [comment]
Reworked the database configuration bit. It is now much easier to switch between databases. And the database properties section is gone from the POM, making it smaller and more comprehensible. See: https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.iudxolbixreg

**Comment by jgoldhammer** [comment]
Hmm, thx for your work. Like the approach of having preconfigured settings. I would Like to see it in the pom.xml. One alfresco-global.properties for all settings and One pom.xml with preconfigured db settings for all databases- the Mojo injects the correct preconfigured db settings into the alfresco-global.properties file depending on enableMysql, enableH2 in the pom... The new approach is a little bit confusing- How should a user now see  where to put settings into? There are too much files. Or do you have another intention? Maybe my last comment was not clear enough, sorry for that...

**Comment by gravitonian** [comment]
Hi,

The idea is to:

1. Have as little environment specific configuration in the POMs as possible (i.e. the database connection information is not used to/does not impact the build of the modules)
2. Keep the POMs as small as possible
3. Make database configuration easy, now you can specify <enableH2>, <enableMySQL>, or <enablePostgreSQL> with no further configuration required in the project (you need to of course create the database as usual)
4. Prepare for Enterprise database configuration via <enableEnterpriseDb>
5. Make it easy to keep multiple database configurations simultaneously

**Comment by jgoldhammer** [comment]
Ok, makes sense. Nevertheless it could be confusing of having multiple Alfresco global properties. Where to put settings for testing?

**Comment by gravitonian** [comment]
The settings you use during testing should go into the alfresco-global that correspond to the database you are using. So by default you would put test config in alfresco-global-h2.properties. If you were always using MySQL then put test config in alfresco-global-mysql.properties etc.

**Comment by ohej** [comment]
Since we both have `<tomcatDependencies/>` and the convenience properties to enable H2, MySQL, PostgreSQL and "enterpriseDB" I think we're good here
