### ISSUE TITLE
Integration Test Requirements (Context and Remote) SDK 3

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#401]
This issue summarises some requirements around Integration Testing in SDK 3.0. 
- Be able to convert 2.1 and 2.2 Spring context tests to run in SDK 3 projects
- Choose between having a separate IT project generated or having test dependencies and tests as part of the Artifact project. For example, IT Spring context tests for the platform might be in each Artifact JAR, but UI tests for a number of Share JARs might be in a separate UI automation test project. If a Yeoman generator is used it would be easy to generate the desired project(s).
- When generating a Platform JAR project with IT tests, only dependencies related to Spring context tests should be included.
- Some Spring Context Tests might need the webapps running, such as one that uses the SearchService, which would need Solr running
- Optionally support BDD driven tests such as with Spock and Geb (UI)

**Comment by jgoldhammer** [comment]
Any progress here? Just waiting for it because I want to fully convert an OSS project to SDK3 and want to execute unit-tests...

Thanks,
Jens

**Comment by gravitonian** [comment]
We have discussed and going with the following approach:

1) Use maven standard lifecycle phases, such as integration-test	
2) If running mvn integration-test, and no server is running, then the container(Tomcat) will be started for each extension sub-project, test run, and container taken down
3) If running mvn integration-test, and a server is running (i.e. mvn clean install alfresco:run from other command line window), then all integration tests will be executed remotely on that instance

**Comment by gravitonian** [comment]
Changed approach to go with Bindu's (Zia Consulting) Alfresco Test Runner framework pull request. Initial version of this is now checked in. Generate all-in-one project and do "mvn clean install alfresco:it" to check it out.

**Comment by ohej** [comment]
The approach we've taken is quite in-depth to explain. Here is the high level way it works:
In All-in-one there is now a `integration-tests` module. In here you'll find integration tests which will be run as remote tests against a running repository.

In the repository we have a web script (part of the `alfresco-rad` module) that is being applied to the platform war. In here the web script can execute a test and give the output back if the test passed or failed.

When you run `mvn install` it will do the usual maven stuff, build/compile and run *unit tests*. Unit tests have no play in here. Later it comes to the integration-test phase where it does several things:
1) Check if the repository is already running 
2) If not, start it up
3) Execute tests against the running repository
4) If the integration-tests started up the tomcat plugin, it will shut it down again

The end result is that you can now run your project `./run.sh`, open another terminal and run `mvn integration-test` - or `mvn verify`. This will execute the tests and give near instant feedback.

If you are using an IDE for example IntelliJ or Eclipse, you can right click the test (or the entire directory) and run them as JUnit tests. The results will come almost instant back to your IDE.

If you add in hotswap agent or JRebel you will be able to change the tests and see the results directly in the ide.

This also means that part of the normal lifecycle of your build, your integration tests WILL be executed against the full webapp (which also means that Solr is available).
