### ISSUE TITLE
Not existing configuration option <alfresco.platform.war.artifactId> to change for enterprise mentioned in sdk 3 guide 

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#403]
Steps to reproduce:
- Generate a new sdk repo project with beta 3
- open the pom.xml and try to change the config option `<alfresco.platform.war.artifactId>` according the guide https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.g8ulc75vtjb7

- The configuration option does not exist.
Documentation bug or archetype bug that the option is not included?

Documentation says:

Configure Enterprise version in pom.xml, let’s use Platform version 5.1.1. The platform artifactId changes for Enterprise edition:
```
<alfresco.platform.war.artifactId>alfresco-enterprise</alfresco.platform.war.artifactId>
<alfresco.platform.version>5.1.1</alfresco.platform.version>
<alfresco.share.version>5.1.1</alfresco.share.version>
```

**Comment by gravitonian** [comment]
Fixed

**Comment by jgoldhammer** [comment]
Thanks for adding this.
