### ISSUE TITLE
SDK 3 - No file-mapping.properties in amp archetype

### ISSUE THREAD

**Issue by wrighting** [Alfresco/alfresco-sdk#409]
It's not that hard to work out how to add it (by changing src/main/assembly/amp.xml) but it would be useful to have it there by default.

**Comment by gravitonian** [comment]
It has been added, and more stuff around AMPs, see for example: https://github.com/Alfresco/alfresco-sdk/tree/sdk-3.0/archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-jar/src/main/assembly

Please close the issue If it is satisfactory.

**Comment by wrighting** [comment]
That was quick! - thanks Martin

**Comment by wrighting** [comment]
Just to say that you probably should have filtered true in the fileSet - with the caveat about file types

**Comment by gravitonian** [comment]
Do you mean that we should filter:

  ```
<file>
            <source>src/main/assembly/file-mapping.properties</source>
            <filtered>false</filtered>
        </file>
```

**Comment by wrighting** [comment]
No. I mean that you should filter the files that are going to be included in the amp.
In my case I need to insert property values into web.xml for CAS filters.

**Comment by gravitonian** [comment]
Ok, I see. And then we should have the usual filter excludes, such as FTL and JS?

**Comment by wrighting** [comment]
I would think so

**Comment by gravitonian** [comment]
Fixed, close if sufficient
