### ISSUE TITLE
Add an Activiti Maven Archetype to SDK 3

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#410]
The Activiti project template will be similar structured as the All-In-One project.
It will have one parent project with one sub-project module extension JAR.
There will be a new Alfresco Maven Plugin property:
       `<enableActiviti>true</enableActiviti>`
that will be used to enable the Activiti WAR file.
It will also use the H2 database but the Platform, Share, and Api Explorer apps 
will be disabled by default.

The Extension Module JAR should contain a sample workflow with a sample task action.

**Comment by douglascrp** [comment]
@gravitonian it seems Alfresco is trying to stop using the embeded activiti engine and trying to move to the stand alone engine.
Is that right?

**Comment by gravitonian** [comment]
Not really, we are trying to consolidate around a common SDK for all products. So the Alfresco SDK will provide an Activiti project template moving forward. 

And, as we go along, we will build up a list of Activiti Samples to go along with the SDK, similar to what we have now for Alfresco One extensions: https://github.com/Alfresco/alfresco-sdk-samples/tree/alfresco-51/all-in-one

**Comment by ohej** [comment]
@douglascrp there are no current plans to discontinue the embedded engine. As Martin said this is to consolidate the developer experience across our products.

**Comment by gravitonian** [comment]
See: https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.vitddzojeqvo

**Comment by jgoldhammer** [comment]
@gravitonian : I think, you have provided basic support for development. 
I will close the issue for now. If there are other additional requirements, we should open a new issue.
