### ISSUE TITLE
Feature Request: Passing system properties to tomcat maven plugin

### ISSUE THREAD

**Issue by toonconvents** [Alfresco/alfresco-sdk#413]
Enable the developer to pass system properties to the tomcat maven plugin for running the project locally. Pre-v3 this is done in the `<systemProperties>` block in the tomcat maven plugin configuration. This is an extension of issue #412 .

Thanks.

**Comment by gravitonian** [comment]
This is now available if building latest SNAPSHOT, then define a sysprop as follows in plugin config:

`
<plugin>
                <groupId>org.alfresco.maven.plugin</groupId>
                <artifactId>alfresco-maven-plugin</artifactId>
                <version>${alfresco.sdk.version}</version>
                <configuration>
...
                    <tomcatSystemProperties>
                        <propName>PropVal</propName>
                    </tomcatSystemProperties>
`

**Comment by ohej** [comment]
Fixed in a07219e6e6a5a9ccfa03d06b081da21434430aef
