### ISSUE TITLE
SDK should fail if alfresco-global-<database>.properties cannot be found

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#416]
Just upgraded the beta-3 to beta-4 and found following error in the log file that the alfresco-global-h2.properties cannot be found:

```
INFO] Renaming alfresco-global-h2.properties to alfresco-global.properties
Downloading: https://oss.sonatype.org/content/repositories/orgalfresco-1039/com/coderplus/maven/plugins/copy-rename-maven-plugin/1.0/copy-rename-maven-plugin-1.0.pom
Downloading: https://repo1.maven.org/maven2/com/coderplus/maven/plugins/copy-rename-maven-plugin/1.0/copy-rename-maven-plugin-1.0.pom
Downloaded: https://repo1.maven.org/maven2/com/coderplus/maven/plugins/copy-rename-maven-plugin/1.0/copy-rename-maven-plugin-1.0.pom (5 KB at 4.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/orgalfresco-1039/com/coderplus/maven/plugins/copy-rename-maven-plugin/1.0/copy-rename-maven-plugin-1.0.jar
Downloading: https://repo1.maven.org/maven2/com/coderplus/maven/plugins/copy-rename-maven-plugin/1.0/copy-rename-maven-plugin-1.0.jar
Downloaded: https://repo1.maven.org/maven2/com/coderplus/maven/plugins/copy-rename-maven-plugin/1.0/copy-rename-maven-plugin-1.0.jar (11 KB at 64.4 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/orgalfresco-1039/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar
Downloading: https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar
Downloaded: https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar (10 KB at 67.7 KB/sec)
[ERROR] sourceFile /Users/jgoldhammer/development/sources/alfresco-jscript-extensions/target/test-classes/alfresco-global-h2.properties does not exist
[INFO] Configured Artifact: org.alfresco:alfresco-platform:5.2.a-EA:war
```

The SDK does not stop here - it continues the process.
It should stop the process when the file cannot be found.

Thanks
Jens

**Comment by gravitonian** [comment]
You would have to generate a project from beta-4 and then copy over the alfresco-global-*.properties files to your beta-3 project

**Comment by jgoldhammer** [comment]
Thanks for the suggestion- I have done that. 
My wish here is that Maven stopps the process when no correct property file has been found.

Thanks,
Jens

**Comment by gravitonian** [comment]
Build will now be immediately stopped with the following error message when config file is missing:

`[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0-SNAPSHOT:run (default-cli) on project aio-customcontext: Missing file: /home/martin/src/sdk3/alfresco-sdk-tests/aio-customcontext/target/test-classes/alfresco-global-h2.properties, when converting from older SDK versions generate an SDK 3 AIO or Platform JAR project and copy alfresco-global-*.properties files from it. Then configure any custom settings from old SDK project repo/src/main/properties/local/alfresco-global.properties file in the new alfresco-global-h2.properties file, or other config file corresponding to the database you are using. -> [Help 1]
`
