### ISSUE TITLE
SDK3 log4j properties for share

### ISSUE THREAD

**Issue by wrighting** [Alfresco/alfresco-sdk#418]
Related to #392.

The approach outlined in the docs/previous issue doesn't work for logging in share components
i.e. add the share class defn to the end of the named file and it's not applied

**Comment by gravitonian** [comment]
See: https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.yx7qvt6z70pf
If you want to try with an existing project then copy in a log4j.properties file from the share/WEB-INF/classes directory into aio/src/test/resources/share/log4j.properties

**Comment by ohej** [comment]
This was fixed in 3031b401a2994f3c466c5bd31d5e315567920f66
