### ISSUE TITLE
Alfresco 4.2.6.4 - h2scripts issue

### ISSUE THREAD

**Issue by OpenPj** [Alfresco/alfresco-sdk#419]
Trying to create a new project from scratch on Alfresco One 4.2.6.4 and configuring h2scripts on pom.xml for the runner module, it returns the following error:

> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.1:run-war-only (run-wars) on project alfresco-common: Execution run-wars of goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.1:run-war-only failed: Plugin org.apache.tomcat.maven:tomcat7-maven-plugin:2.1 or one of its dependencies could not be resolved: Could not find artifact org.alfresco:alfresco-repository:jar:h2scripts:4.2.6.4 in alfresco-plugin-public (https://artifacts.alfresco.com/nexus/content/groups/public)

I have solved adding the following snippet for extending the pluginRepository element:

```
<pluginRepositories>
        <pluginRepository>
            <id>alfresco-private-repository</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/private</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by ohej** [comment]
Which version of the SDK did you use?

**Comment by OpenPj** [comment]
1.1.1

**Comment by jgoldhammer** [comment]
Alfresco SDK 1.1.1 is not supported anymore. Please try it with Alfresco SDK 3 beta 6 and report if this does not work for you.

Thanks
Jens
