### ISSUE TITLE
Make it possible to generate WARs without alfresco:run in SDK 3.0

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#420]
Some users use the WARs as final artifacts for deployments. Today you cannot create the WARs without running the system with alfresco:run.

Provide something like alfresco:build-war that can be used by for example a CI server to create the WARs before deployment.

**Comment by sujaypillai** [comment]
+1 for that .... I am one of that user :)

**Comment by toonconvents** [comment]
+1 Same here

**Comment by jgoldhammer** [comment]
@gravitonian 
Have you started on this already?
I would like to discuss how the implementation should look like. Any ideas? I could jump on the train to implement it...

Thanks,
Jens

**Comment by gravitonian** [comment]
I would probably create a new AbstractRunMojo class and then have the RunMojo (alfresco:run) and BuildWarsMojo (alfresco:build-wars) extend this base class. You would have to just keep a variant of the execute() method in the AbstractRunMojo class that builds the WARs, it would basically do everything except kicking off tomcat, something like:

 ```
public void execute() throws MojoExecutionException {
        execEnv = executionEnvironment(
                project,
                session,
                pluginManager
        );

        if (enableSolr) {
            unpackSolrConfig();
            fixSolrHomePath();
            replaceSolrConfigProperties();
            installSolr10InLocalRepo();
        }

        if (enableTestProperties && enablePlatform) {
            copyAlfrescoGlobalProperties();
            renameAlfrescoGlobalProperties();
        }

        if (enablePlatform) {
            buildPlatformWar();
        }

        if (enableShare) {
            buildShareWar();
        }

        if (enableActivitiApp) {
            buildActivitiAppWar();
        }

      //  if (startTomcat) {
        //    checkDatabaseConfig();
          //  startTomcat();
       // }
    }
```

The BuildWarsMojo would basically just use what is in the AbstractRunMojo class.

**Comment by jgoldhammer** [comment]
I just started to implement it, but got an weird error after the build process is success.
I will publish code tomorrow in a PR, but it is basically the same from your comment- everything without starting tomcat...

Exception:
```
[INFO] Configured Artifact: de.jgoldhammer:testing-sdk-beta6:1.0-SNAPSHOT:jar
[INFO] Copying testing-sdk-beta6-1.0-SNAPSHOT.jar to /Users/jgoldhammer/development/sources/alfresco-sdk/testing-sdk-beta6/target/platform-war/WEB-INF/lib/testing-sdk-beta6-1.0-SNAPSHOT.jar
[INFO] NOT copying Alfresco Enterprise license, running Community edition
[INFO] Installing /Users/jgoldhammer/development/sources/alfresco-sdk/testing-sdk-beta6/target/platform.war to /Users/jgoldhammer/development/maven/de/jgoldhammer/testing-sdk-beta6-platform/1.0-SNAPSHOT/testing-sdk-beta6-platform-1.0-SNAPSHOT.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.900 s
[INFO] Finished at: 2016-11-30T22:20:05+01:00
[INFO] Final Memory: 44M/473M
[INFO] ------------------------------------------------------------------------
java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsLockController$1Sync
	at de.schlichtherle.truezip.fs.FsLockController.sync(FsLockController.java:240)
	at de.schlichtherle.truezip.fs.archive.zip.KeyController.sync(KeyController.java:128)
	at de.schlichtherle.truezip.fs.FsDecoratingController.sync(FsDecoratingController.java:131)
	at de.schlichtherle.truezip.fs.FsFalsePositiveArchiveController.sync(FsFalsePositiveArchiveController.java:480)
	at de.schlichtherle.truezip.fs.FsManager.sync(FsManager.java:105)
	at de.schlichtherle.truezip.fs.FsDefaultManager.sync(FsDefaultManager.java:190)
	at de.schlichtherle.truezip.fs.FsSyncShutdownHook$Hook.run(FsSyncShutdownHook.java:93)
Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsLockController$1Sync
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 7 more
```

@gravitonian : Any ideas?

**Comment by gravitonian** [comment]
Have you mixed running stuff as root at one point and then as a standard user? What I mean is, could there be files in local Maven repo or /target that are owned by the root user?

**Comment by ohej** [comment]
De-scoping for 3.0

**Comment by karthickmani1** [comment]
+1 For this. Any timelines around this?

**Comment by archimadhu** [comment]
+1 for this. Can we have any ETA for this?

**Comment by eyaroslavtsev** [comment]
+1 for that

**Comment by jonfrink** [comment]
+1

**Comment by binduwavell** [comment]
+1

**Comment by gravitonian** [comment]
Hi,

A simple workaround that might be suitable for most use-cases is to include the following profile in the parent POM in an All-In-One (AIO) project:

 ```
<profiles>
        <profile>
            <!-- Invoke your build with -Pgenerate-wars to run the system, but only to the point
                 where the wars are generated, skip starting Tomcat.
             -->
            <id>generate-wars-only</id>
            <properties>
                <maven.alfresco.startTomcat>false</maven.alfresco.startTomcat>
            </properties>
        </profile>
    </profiles>
```
Include the `<profiles>` section after for example the `<build>` section.

Then what you need to do is as follows to just generate the WARs without running Tomcat:

`$ mvn clean install alfresco:run -Pgenerate-wars-only`

You will find the WARs in the target directory:

```
target martin$ ls -l
total 447592
drwxr-xr-x   5 martin  staff        170  7 Jun 09:17 dependency-maven-plugin-markers
drwxr-xr-x   3 martin  staff        102  7 Jun 09:17 modules
drwxr-xr-x  12 martin  staff        408  7 Jun 09:17 platform-war
-rw-r--r--   1 martin  staff  155090333  7 Jun 09:17 **platform.war**
drwxr-xr-x  18 martin  staff        612  7 Jun 09:17 share-war
-rw-r--r--   1 martin  staff   74072640  7 Jun 09:17 **share.war**
drwxr-xr-x   9 martin  staff        306  7 Jun 09:17 test-classes
```

**Comment by jrosler** [comment]
+1

**Comment by davidabad** [comment]
At this time, built wars includes changes that isn't suitable for deployment on production or integration environment e.i. platform web.xml is updated, properties for hotswaping are injected etc..

At least "org.alfresco.maven.plugin.AbstractRunMojo.buildPlatformWar()" and 
"org.alfresco.maven.plugin.AbstractRunMojo.buildShareWar()" methods should test the "startTomcat" flag to avoid unwanted modifications.

**Comment by toonconvents** [comment]
Any update on this guys? Or a viable workaround?

**Comment by toonconvents** [comment]
For anyone who is interested: I have forked the SDK and introduced some minor changes to able to build clean WARS using the alfresco-maven-plugin for deployment to a production system.
https://github.com/toonconvents/alfresco-sdk

**Comment by trycoon** [comment]
+1

**Comment by ikaygorodov** [comment]
+1

**Comment by ikaygorodov** [comment]
BTW
mvn clean deploy alfresco:run -Pgenerate-wars-only
Maven SDK deploys AMPs and Jars but only installs WARs to local ~/.m2 folder.
This is not great.

**Comment by mauro1855** [comment]
+1 It would be great if I can get just the wars so I can deploy on my own tomcat.

**Comment by abhinavmishra14** [comment]
+1 It would be great if I can get the wars. It makes easy deployment process.

**Comment by Yogesh102** [comment]
Does is this work - generate war files - https://github.com/toonconvents/alfresco-sdk ?
I have tried in my local but it does not make any change. It still generates the jars.

**Comment by dhaval1671** [comment]
Hi Yogesh102, you can use https://github.com/dhaval1671/SDK-3.0.1-alfresco-plugin 
this project which will generate alfresco.war and share.war instead of platform.war add same into your maven dependency

**Comment by DEEPAK-KESWANI** [comment]
> When I try this, I get a No class def found error. Any thoughts?
> 
> java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsLockController$1Sync
> at de.schlichtherle.truezip.fs.FsLockController.sync(FsLockController.java:240)
> at de.schlichtherle.truezip.fs.archive.zip.KeyController.sync(KeyController.java:128)
> at de.schlichtherle.truezip.fs.FsDecoratingController.sync(FsDecoratingController.java:131)
> at de.schlichtherle.truezip.fs.FsFalsePositiveArchiveController.sync(FsFalsePositiveArchiveController.java:480)
> at de.schlichtherle.truezip.fs.FsManager.sync(FsManager.java:105)
> at de.schlichtherle.truezip.fs.FsDefaultManager.sync(FsDefaultManager.java:190)
> at de.schlichtherle.truezip.fs.FsSyncShutdownHook$Hook.run(FsSyncShutdownHook.java:93)
> Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsLockController$1Sync
> at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
> at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
> at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
> at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

The below command solved my problem
`mvn dependency:resolve`

**Comment by ohej** [comment]
SDK 3.1 will include a new goal to produce the WAR file. We're also investigating an approach to attach the WAR to the build so it can be deployed to a repository along with the JAR/AMPs when doing stuff like `mvn deploy`.

**Comment by trycoon** [comment]
@ohej I see no info about 3.1, there is a 4.0-beta though. Do you mean 4.0? Or when could we expect 3.1?

**Comment by mishraa12018** [comment]
> SDK 3.1 will include a new goal to produce the WAR file. We're also investigating an approach to attach the WAR to the build so it can be deployed to a repository along with the JAR/AMPs when doing stuff like `mvn deploy`.

Took latest sdk3.1 archetype sample, What is the option to generate the war files ? Is their any additional plugin or project which we need to configure ?

**Comment by ikaygorodov** [comment]
> Took latest sdk3.1 archetype sample, What is the option to generate the war files ? Is their any additional plugin or project which we need to configure ?

Try to use mvn alfresco:build-wars

**Comment by mishraa12018** [comment]
Thanks @ikaygorodov for your response. I tried "mvn alfresco:build-wars" but it doesn't work. I am executing this goal against the parent pom which contains the list of modules.

I get this error when i run the build-wars goal. I am using All In One archetype. 

[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3
.1.0:build-wars (default-cli) on project alfresco-project-sdk31: Unable to execute mojo:
