### ISSUE TITLE
SDK3 No minification

### ISSUE THREAD

**Issue by wrighting** [Alfresco/alfresco-sdk#423]
You used to get myfile-min.js etc, you don't now

**Comment by jgoldhammer** [comment]
Please describe in detail what does not work. Do you want to say that the SDK 3 does not minify your javascript files when building an war-file? Or anything else?

Thanks
Jens

**Comment by gravitonian** [comment]
I think it might be that we just have to add the maven plugin for it, like in SDK 2.2.0 projects:

` 
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>yuicompressor-maven-plugin</artifactId>
            </plugin>`

**Comment by wrighting** [comment]
@gravitonian @jgoldhammer - you're both right.
The SDK3 does not minify the js or css files when building the war file, as you would expect it to.
Adding the plugin should fix in.
The thing to be careful about is to ensure that the correct filetypes are minified - not too many, and not too few.

**Comment by ohej** [comment]
To avoid bloating the default `pom.xml` we ship out of the box, I would prefer to have this as a documentation feature. It is really about adding the plugin with the correct configuration.

**Comment by shazada** [comment]
Sorry to bump into this again, but I'm not really positive that it isn't there any more by default.
Then at least it should be commented in the generated share pom.xml so it's quite obvious.

We stumbled upon this out of the blue and in the mean time a lot of jar's were build and release without their minified versions.

Then again the Alfresco's own jars supplied in for example 5.1 have a difference on minified as well.
E.g. Aikau- versions supplied in  5.1 community aren't minified!
alfresco-googledocs-share*.jar is minified.

**Comment by douglascrp** [comment]
@shazada Hello.
Have you found any solution for this?

@ohej How about the documentation on this topic?
Is it really going to be added anytime?

**Comment by douglascrp** [comment]
My workaround for this, https://douglascrp.blogspot.com.br/2017/11/how-to-add-missing-minification-of.html

**Comment by ohej** [comment]
SDK 3.1 we've added back minification.
