### ISSUE TITLE
Support for Solr 6 in SDK 3

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#424]
Solr6 is going to be available as an optional replacement for solr 4 in 5.2. Solr6 runs with its own jetty.  Its independent of Alfresco repo and comes in its own zip.  A solr6 subsystem was added, which is just for the config. So we need to work out what to set in alfresco-global.properties and how to start up an independent process.

**Comment by jgoldhammer** [comment]
Any ideas here how to do that?

**Comment by gravitonian** [comment]
This Jira has more information on how to use Solr6 with Alfresco: https://issues.alfresco.com/jira/browse/SEARCH-231, maybe we can somehow fork the Jetty process from the maven alfresco:run process

**Comment by covolution** [comment]
We should really try to avoid mentioning jetty and solr 6 together.  The solr project is now an independent executable, the use of jetty is an implementation detail. Perhaps maven-exec-plugin might do the trick or just have an independent task to start it?

**Comment by gravitonian** [comment]
My suggestion here is to:

1) Install Solr6 separately, as per https://community.alfresco.com/community/ecm/blog/2017/01/04/installing-the-new-alfresco-search-services-with-solr-6
2) Then have a new Alfresco Maven Plugin attribute called <solrVersion>6</solrVersion> (defaults to version 4 if not specified), which brings in the needed Solr 6 property settings in alfresco-global.properties, and makes sure the solr4 webapp and config is not deployed

**Comment by covolution** [comment]
Actually, for point 1 above, if you are just using solr 6 on the same host as alfresco, the installation on the solr side is basically download a zip and start it.  That could potentially be done by maven.

**Comment by ohej** [comment]
Pushing this out of scope for SDK 3.0 initial release. @covolution, let's see if we can work on this during the upcoming hackathon at BeeCon.

**Comment by toonconvents** [comment]
@gravitonian, it's been a while. Any update on this?

**Comment by ohej** [comment]
It has indeed been a while. I've found my old notes for the work required to make Solr6 work on SDK 3.0:

Solr start command:
solr/bin/solr start -a "-Ddata.dir.root=/Users/ohejlskov/work/platform-jar/alf_data_dev/solr6 -Dcreate.alfresco.defaults=alfresco,archive -Dalfresco.port=8080"
(use solr.cmd for windows)


Steps to do:
1) Download dependency:
```
<dependency>
  <groupId>org.alfresco</groupId>
  <artifactId>alfresco-search-services</artifactId>
  <version>1.0.0</version>
  <type>zip</type>
</dependency>
```

2) Make a property to enableSearchServices (enableSolr6??) 

3) Make a property for defining the version of alfresco-search-services

4) Alfresco properties needs to change dynamically:
index.subsystem.name=solr6
solr.port=8983

5) Figure out the exec plugin
```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>target/ass/solr/bin/solr</executable>
                    <async>true</async>
                    <arguments>
                        <argument>-a</argument>
                        <argument>-Ddata.dir.root=/Users/ohejlskov/work/platform-jar/alf_data_dev/solr6 -Dcreate.alfresco.defaults=alfresco,archive -Dalfresco.port=8080</argument>
                        <argument>-f</argument>
                    </arguments>
                    <successCodes>
                        <successCode>130</successCode>
                        <successCode>0</successCode>
                    </successCodes>
                </configuration>
            </plugin>
```



6) Figure out shut down
  solr/bin/solr stop -all
  - How do we invoke it? Is there a shut down handler or similar?

**Comment by ohej** [comment]
Reviewing the options, it will be difficult for us to fully support Solr6 / Alfresco Search Services in SDK 3.1. The amount of logic required would only add even more complexity to the archetypes or the SDK itself. 

With SDK 4.0 leveraging Docker it's baked in and easy to do, but reviewing our options for SDK 3.x, we will recommend starting Solr6 / Alfresco Search Services as a separate process - or leverage the notes above as inspiration.
