### ISSUE TITLE
add support for custom contextFile

### ISSUE THREAD

**Issue by pzrinscak** [Alfresco/alfresco-sdk#425]
We need an option to define JNDI resources to platform tomcat. I see that it could be easily done since 

Open Declaration Element org.alfresco.maven.plugin.RunMojo.createWebAppElement(String groupId, String artifactId, String version, String contextPath, String contextFile)

already supports it.

It can be added as a parameter to RunMojo

**Comment by jgoldhammer** [comment]
Hi @pzrinscak ,

please tell us more about the motivation to add jndi resources to platform tomcat. Which services do you want to add during development via JNDI?

Thanks
Jens

**Comment by pzrinscak** [comment]
I have data-sources on my tomcat environments defined through jndi. I'm loading them as JNDI lookup beans in my alfresco/spring context. I need to mock them on my local development environment somehow.

**Comment by ohej** [comment]
Unfortunately this didn't make it in time for the initial 3.0 release. However this is something we can add in a minor release later on.

**Comment by mtwallach** [comment]
was this ever addressed/resolved? I'm working with someone with same/similar issue

**Comment by n4nikky** [comment]
I need the same solution for our project. Any solution provided for this in the earlier releases? if not any workaround for this?

**Comment by ohej** [comment]
Fixed in #524 and will be included in SDK 3.1
