### ISSUE TITLE
SOLR with Alfresco 4.2 and SDK-3-BETA-4 creates index in directory @@ALFRESCO_SOLR_DIR@@

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#426]
Steps to reproduce:
* Generate a new project with following command
`mvn archetype:generate -DarchetypeCatalog=https://artifacts.alfresco.com/nexus/content/groups/public/archetype-catalog.xml -Dfilter=org.alfresco.maven.archetype:`
 (Use beta 4             <alfresco.sdk.version>3.0.0-beta-4</alfresco.sdk.version>)

* Change pom.xml according the docs
  * remove the alfresco-share-services
  * change version to 4.2.f

* Execute run.sh

Result:
Solr creates the directory in @@ALFRESCO_SOLR_DIR@@

![image](https://cloud.githubusercontent.com/assets/3872101/20040853/8c71e8f0-a45f-11e6-88fc-db3f9dfceb45.png)

**Comment by jgoldhammer** [comment]
Any idea, @gravitonian ?

**Comment by ohej** [comment]
Full support for 4.2 was fixed in 245a51402d1a428041e6f125d7c7766286827067. There was a lot of fixes and edge cases but is all now handled by the plugin.
