### ISSUE TITLE
Feature request: Usage of nightly builds in sdk projects

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#427]
It would be nice when the sdk 3 introduces support for using nightly builds.
Nightly builds currently can be downloaded here: http://alf-community-nightly.s3-website-eu-west-1.amazonaws.com

It would help me to test my addons in the newest version (by using CI) 
What do you think?

**Comment by jgoldhammer** [comment]
@ohej and @gravitonian:
Do you think this is possible? Nightly builds are not published in artifacts.alfresco.com, right?
Might it be possible to think about adding SNAPSHOT builds?

Thanks
Jens

**Comment by ohej** [comment]
We have the infrastructure in place to push beta versions on our own Nexus. On top of that we actually already publish snapshots to Maven central on every successful build. Closing
