### ISSUE TITLE
Replace DTD declaration with xmlns element

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [Alfresco/alfresco-sdk#429]
When project generated by achetype `service-context.xml` has the following header:

```
<!DOCTYPE beans PUBLIC '-//SPRING//DTD BEAN//EN' 'http://www.springframework.org/dtd/spring-beans.dtd'>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
```

So when custome element prefix is added Intellij Idea highlights it as error, event if `xmlns:context` (for context prefix) and `xsi:schemaLocation` is added:

```
<!DOCTYPE beans PUBLIC '-//SPRING//DTD BEAN//EN' 'http://www.springframework.org/dtd/spring-beans.dtd'>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd">
    <!-- error here -->
    <context:component-scan base-package="com.mypackage" />
```

So default header of  `service-context.xml`  should be changed to:

```
<beans  xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
```

Parsing seems to work anyway, but without `xmlns` we loose autocomplete for elements with prefix.

**P.S.**

I show only `service-context.xml`  as example, but I think all spring context files should be changed.

**Comment by jgoldhammer** [comment]
@C-h-e-r-r-y , can you check if my PR adresses your report?
Thanks,
Jens

**Comment by ohej** [comment]
Merged @jgoldhammer pull request, tested locally with IntelliJ seems to check out
