### ISSUE TITLE
Problems trying to include client side resources with SDK 3 beta 5

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#430]
I'm trying to use the SDK3 beta 5 in a project I'm working on, and I'm facing some problems with client side resources.
The first one is that for new client side files, I'm trying to put them inside the <project>/src/main/resources/META-INF/resources/<module>, but my files are not available when I try to access them.

I have configured the moduleDependency type as amp, as described at https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.b4by66les1tp

As this didn't work, I then tried to put the same files inside <project>/src/main/assembly/web
By doing this, I got the files deployed correctly.
Javascript files are ok, but PNG files got corrupted.

The pom files says 
```
<nonFilteredFileExtensions> <!-- jpg, jpeg, gif, bmp and png are added automatically -->
```
but it seems that is not true.
I even tried to add png into the list, but that also didn't help.
The png files are going to be used as indicators in the document library.

I hope you can replicate the issues.

**Comment by douglascrp** [comment]
I was able to make it work by setting the filtered option as false in the section bellow inside the amp.xml file:
```
<fileSet>
    <directory>src/main/assembly/web</directory>
    <outputDirectory>web</outputDirectory>
    <filtered>false</filtered> <!-- Will filter files and substitute POM props such as for example ${project.name} -->
    <excludes>
        <exclude>README.md</exclude>
    </excludes>
</fileSet>
```
Thanks @wrighting for the tip.

Wouldn't it be possible to add the maven-resources-plugin nonFilteredFileExtensions option in this file also?

**Comment by marsv024** [comment]
Just as a comment, I was able to access a css-file which I added under META-INF/resources/css/test.css

This did map to localhost:8080/share/css/test.css for me.

**Comment by douglascrp** [comment]
@marsv024 Odd. It didn't work at all for me.
Well, let's wait to see if they can find something about this issue.
Thank you for your test.

**Comment by douglascrp** [comment]
@ohej 
I have just tested this agains 3.0.0 (and also with 3.0.1-SNAPSHOT build locally) and the same problem happens.
The only way to get rid of it is by changing the filtered property inside the amp.xml file as described in my comment previously.

**Comment by eyaroslavtsev** [comment]
@marsv024 It works for me, thanks.
There is not the clear solution (for src/main/assembly/web directory), but in my sample project I used to the following `maven-assembly-plugin` config:
`<fileSets>
        
        <fileSet>
            <directory>src/main/assembly/web</directory>
            <outputDirectory>web</outputDirectory>
            <filtered>true</filtered> 
            <includes>
                <include>**/*.*</include>
            </includes>
            <excludes>
                <exclude>README.md</exclude>
                <exclude>**/*.jpg</exclude>
                <exclude>**/*.jpeg</exclude>
                <exclude>**/*.gif</exclude>
                <exclude>**/*.bmp</exclude>
                <exclude>**/*.ftl</exclude>
                <exclude>**/*.acp</exclude>
                <exclude>**/*.svg</exclude>
                <exclude>**/*.pdf</exclude>
                <exclude>**/*.doc</exclude>
                <exclude>**/*.docx</exclude>
                <exclude>**/*.xls</exclude>
                <exclude>**/*.xlsx</exclude>
                <exclude>**/*.png</exclude>
                <exclude>**/*.ppt</exclude>
                <exclude>**/*.pptx</exclude>
                <exclude>**/*.bin</exclude>
                <exclude>**/*.lic</exclude>
                <exclude>**/*.swf</exclude>
                <exclude>**/*.zip</exclude>
                <exclude>**/*.msg</exclude>
                <exclude>**/*.jar</exclude>
                <exclude>**/*.ttf</exclude>
                <exclude>**/*.eot</exclude>
                <exclude>**/*.woff</exclude>
                <exclude>**/*.woff2</exclude>
                <exclude>**/*.ico</exclude>
                <exclude>**/*.psd</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/main/assembly/web</directory>
            <outputDirectory>web</outputDirectory>
            <filtered>false</filtered>
            <includes>
                <include>**/*.jpg</include>
                <include>**/*.jpeg</include>
                <include>**/*.gif</include>
                <include>**/*.bmp</include>
                <include>**/*.ftl</include>
                <include>**/*.acp</include>
                <include>**/*.svg</include>
                <include>**/*.pdf</include>
                <include>**/*.doc</include>
                <include>**/*.docx</include>
                <include>**/*.xls</include>
                <include>**/*.xlsx</include>
                <include>**/*.png</include>
                <include>**/*.ppt</include>
                <include>**/*.pptx</include>
                <include>**/*.bin</include>
                <include>**/*.lic</include>
                <include>**/*.swf</include>
                <include>**/*.zip</include>
                <include>**/*.msg</include>
                <include>**/*.jar</include>
                <include>**/*.ttf</include>
                <include>**/*.eot</include>
                <include>**/*.woff</include>
                <include>**/*.woff2</include>
                <include>**/*.ico</include>
                <include>**/*.psd</include>
            </includes>
        </fileSet>
    </fileSets>`
Does anyone have a clear solution?
