### ISSUE TITLE
Enable CORS for platform ?

### ISSUE THREAD

**Issue by ycoulon** [Alfresco/alfresco-sdk#432]
Hi,

Is there any way to enable CORS for Alfresco from the SDK ? Platform jar or All In One ?

It would be usefull to work on Alfresco module and UI using the ADF.

**Comment by ohej** [comment]
We provide a JAR that contains a webfragment with CORS enabled, see here: https://artifacts.alfresco.com/nexus/#nexus-search;quick~enablecors

I haven't tested it out, but you should be able to add the module in as a dependency and it should work, i.e 

```
<dependency>
  <groupId>org.alfresco</groupId>
  <artifactId>enablecors</artifactId>
  <version>1.0</version>
</dependency>
```

Let me know if this works or not

**Comment by ycoulon** [comment]
Hi,
Thanks Ohej for the link.

Just need to add the following dependencies :
```
<dependency>
    <groupId>com.thetransactioncompany</groupId>
    <artifactId>cors-filter</artifactId>
    <version>2.5</version>
</dependency>
```
And it works.

**Comment by kodermax** [comment]
How can I enable cors filter in SDK?

**Comment by luistrigueiros** [comment]
Hi,

I found that we need to include both the enablecors and the cors-filter dependencies in the SDK generated project the enablecors should just have a transitive dependency on cors-filter.

**Comment by covolution** [comment]
The Alfresco repository ships with cors-filter-2.5.jar so the enablecors dependency is purely for configuring the existing classes.  You would need the cors-filter dependency if the cors-filter-2.5.jar isn't already in the the WEB-INF/lib.
