### ISSUE TITLE
SDK 2.2.0 not compatible with maven-war-plugin 3.0.0

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#433]
There seems to be an incompatibility between an API that the SDK uses and the maven-war-plugin version 3.0.0. 
The error I get is:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.0.0:war (default-war) on project repo: 
Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:3.0.0:war failed: 
An API incompatibility was encountered while executing org.apache.maven.plugins:maven-war-plugin:3.0.0:war: 
java.lang.NoSuchMethodError:
org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.addRawArchiveEntry(Lorg/apache/commons/compress/archivers/zip/ZipArchiveEntry;Ljava/io/InputStream;)V
```

How to reproduce: 
* Generate a project from the all-in-one archetype
`mvn archetype:generate -DarchetypeGroupId=org.alfresco.maven.archetype -DarchetypeArtifactId=alfresco-allinone-archetype -DarchetypeVersion=2.2.0`
* Add the following in the parent pom, in the `<build> <plugins>` section: 
```
         <!-- Set maven-war-plugin to version 3.0.0 -->
         <plugin>
             <artifactId>maven-war-plugin</artifactId>
             <version>3.0.0</version>
         </plugin>
```
* Run `mvn clean install`
The build will fail in the Alfresco Repository WAR Aggregator, when the alfresco-maven-plugin will try to apply the AMP to the WAR.

I could reproduce this on Linux and Windows, with Maven 3.2 and 3.4

**Comment by jgoldhammer** [comment]
Hi @slanglois ,

I tried it to reproduce, but don´t have all steps. Please create a step by step description...
And please update the description with alfresco sdk version, maven version, os etc.

Thanks!
Jens

**Comment by jgoldhammer** [comment]
Ping, @slanglois! :-)

**Comment by slanglois** [comment]
Sorry @jgoldhammer and thanks for your patience :-)
I updated the steps to reproduce, so hopefully it's clearer now. 
Also, here is the modified project based on the all-in-one archetype, so you can just build it if you prefer: 
[issue-433.zip](https://github.com/Alfresco/alfresco-sdk/files/624959/issue-433.zip)

Thanks!

**Comment by ohej** [comment]
@slanglois since we don't use the war overlays anymore in SDK3 is this still an issue?

**Comment by slanglois** [comment]
It's not an issue any more, indeed...
Closing it.
Thanks!
