### ISSUE TITLE
Tomcat context path should default to / 

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-sdk#434]
If you are running multiple apps (repo, solr, share etc) at the same time, it's valuable to have the index.html file that just give links to the various apps. However, since we haven't defined a path for the default Tomcat configuration (outside the `webapps` section) the index file will be deployed to `/${artifactId}`. We should default to `/` and make this configurable via the plugin

**Comment by jgoldhammer** [comment]
Ole, please explain a little bit more.
Do you want to run the repository and share under path `/`? If so, this would need to change the share configs for another endpoint... Or I am wrong here?

Thanks
Jens

**Comment by ohej** [comment]
Fixed in 93dde46f513c468f8e9bffd7ecf8d1888b7fb991

The idea was not to run the repository on /, but if you are running in All-in-one, you can now have an index.html file in src/main/webapp (in the root of the project) which links into the services (api-explorer, alfresco, share etc) so when you go to http://localhost:8080/ you don't just get a blank page
