### ISSUE TITLE
Always use the right alfresco-api-explorer version

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#436]
## I'm submitting a ...   (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
```

## Expected Behavior

As user, I want to use the newest version of api-explorer.

## Current Behavior

Currently, api-explorer 1.0 is used.

## Possible Solution

Not clear yet - each alfresco version supports another api-explorer version because the REST API evolve with the latest versions... We could maintain the correct alfresco-api-explorer version with each alfresco version?!

## Steps to Reproduce (for bugs)

1. Create a new amp project
2. Start alfresco with mvn alfresco:run
3. Use the alfresco-api-explorer

## Your Environment

* Alfresco SDK version used: 3.0beta6
* Alfresco version used: every supported alfresco version
* Output of command 'mvn -version': 
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```
* Link to your project: no project yet

**Comment by gravitonian** [comment]
Fixed

**Comment by ohej** [comment]
SDK3 takes the latest API Explorer, but if you want a specific one it can be configured via the
`<alfresco.api.explorer.version />` property

**Comment by billerby** [comment]
When running latest Alfresco 5.2.3 there is no groups API in API-explorer. Its stated in the online version that this was added in Alfresco 5.2.1. I am not sure whats the problem here? Is it the SDK or Alfresco 5.2.3 that lacks the new groups API?
