### ISSUE TITLE
Alfresco-SDK is not building without access to activiti-private-repository

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#437]
## I'm submitting a ...   (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior

Building the sdk3.0 branch should work should work without access to an enterprise maven repository.

## Current Behavior

Currently the build fails with following exception.
```
 [ERROR] Failed to execute goal on project activitiJARTestRun: Could not resolve dependencies for project archetype.it:activitiJARTestRun:jar:0.1-SNAPSHOT: Failed to collect dependencies at com.activiti:activiti-app-logic:jar:1.5.1: Failed to read artifact descriptor for com.activiti:activiti-app-logic:jar:1.5.1: Could not transfer artifact com.activiti:activiti-app-logic:pom:1.5.1 from/to activiti-private-repository (https://artifacts.alfresco.com/nexus/content/repositories/activiti-enterprise-releases): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project activitiJARTestRun: Could not resolve dependencies for project archetype.it:activitiJARTestRun:jar:0.1-SNAPSHOT: Failed to collect dependencies at com.activiti:activiti-app-logic:jar:1.5.1
```

## Possible Solution

The alfresco-sdk build should not depend on enterprise artifacts.

## Steps to Reproduce (for bugs)

1. Clone the alfresco-idk
2. git checkout sdk-3.0
3. mvn clean install

## Your Environment

* Output of command 'mvn -version': 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

**Comment by gravitonian** [comment]
The build have to be done without tests:

alfresco-sdk$ mvn clean install -DskipTests=true

**Comment by jgoldhammer** [comment]
Hi, 

this is not what I was expecting. I never would leave tests when making changes, so I can check if everything is fine. I think, we have to put activiti-testing in a separate profile.
What do you think?

Thanks
Jens

**Comment by gravitonian** [comment]
We have built without the SDK tests for all archetype for a while now. We need to put the tests back for all archetypes if possible

**Comment by ohej** [comment]
When building the SDK it will now exclude all archetype tests that contains `enterprise`. To build with the enterprise tests you need to activate the `enterprise-tests` profile.

**Comment by zhihailiu** [comment]
I noticed that the bug is closed, but I run into the same issue even with "-DskipTests=true". Is there a way to avoid dependency on activiti-private-repository?

**Comment by savicprvoslav** [comment]
It worked for me.
```
mvn clean install alfresco:run -DskipTests=true
```
