### ISSUE TITLE
SDK 3.0 Integration tests - platform-jar-archetype

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-sdk#450]
## I'm submitting a ...   
```
[x] bug report
[ ] feature request
```

## Expected Behavior
I start from the platform-jar-archetype, I've yet to verify if the same problem persists in the AIO archetype.

- The org.alfresco.util.test.junitrules.ApplicationContextInit class is available in the test scope.
I can initialize the application context and get whatever (service) bean I require for integration tests.

- If I start a build with **mvn clean install** the integration test(s) initialize the application context and run correctly using internal H2 database.

- If I start a build with **mvn clean install alfresco-run** the integration tests either run, or are skipped and alfresco platform starts directly.

## Current Behavior

- org.alfresco.util.test.junitrules.ApplicationContextInit is unavailable, due to missing dependency:

`<!-- Bring in Alfresco Repository tests so we get access to integration tests -->`
`<dependency>`
`<groupId>${alfresco.groupId}</groupId>`
`<artifactId>alfresco-repository</artifactId>`
`<version>${alfresco.platform.version}</version>`
`<classifier>tests</classifier>`
`<scope>test</scope>`
`</dependency>`

- If I start a build with **mvn clean install** the build fails with 

> Cannot load JDBC driver class 'org.h2.jdbcx.JdbcDataSource'
> java.lang.ClassNotFoundException: org.h2.jdbcx.JdbcDataSource

due to missing dependency:

`<dependency>`
`<groupId>com.h2database</groupId>`
`<artifactId>h2</artifactId>`
`<version>${h2.version}</version>`
`<scope>test</scope>`
`</dependency>`

- After adding the dependency, the alfresco-maven-plugin starts up the platform, then in the run the  ApplicationContextInit does the same thing. I'd expect only the ApplicationContextInit to initialize, not  the entire platform. Ending the build it throws an error after the 'BUILD SUCCESS' message:

`Exception in thread "Thread-4" ERROR: IllegalAccessException for stop method in class org.apache.tomcat.maven.plugin.tomcat7.run.ExtendedTomcat
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils`

But this has no real impact if running it on my local machine. On an integration server (Jenkins, ...) this might break the build, though, as an error is signalled.

- If I start a build with **mvn clean install alfresco-run** the build fails with

> Cannot load JDBC driver class 'org.gjt.mm.mysql.Driver'
> java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver

instead of starting the alfresco platform, while running the integration test(s) first or skipping them.

## Possible Solution
Add the missing dependencies to the archetype so they are included in the pom.xml

For the final issue, the alfresco-maven-plugin will probably need some code changes, and/or the way we design/run integration tests with ApplicationContextInit.

As a workaround, you can execute 2 build runs: start 'clean install' first, followed by an 'alfresco:run' build. By separating the goals into 2 steps the problem is avoided on a local machine, though a build server might still say the build failed. Haven't tested on our buildserver yet.

## Steps to Reproduce (for bugs)
See 'Current Behavior'

1. Generate a project using Archetype alfresco-platform-jar-archetype:3.0.0, see http://docs.alfresco.com/5.2/concepts/sdk-getting-started.html
2. Notice the alfresco-repository test artifact is missing, to continu you must include it.
3. Create a jUnit test class, add a classrule and some services:

`@ClassRule public static final ApplicationContextInit APP_CONTEXT_INIT = new ApplicationContextInit();`
`protected NodeService nodeService = APP_CONTEXT_INIT.getApplicationContext().getBean("nodeService", NodeService.class);`

4. Start a mvn build with goals 'clean install'
5. Notice the missing h2 class, to continu you must include it. Also set the 'h2.version' property.
6. Start a mvn build with goals 'clean install alfresco:run'
7. Notice the integration test tries to run with the mysql database instead of skipping and starting alfresco immediately

## Context
Just starting the prep work for an upgrade to SDK 3.0, have a customer who wants to upgrade to 5.2 asap, so needed to run a few integration tests.

## Your Environment

* Alfresco SDK version used: 3.0
* Alfresco version used: Enterprise 5.2
* Apache Maven 3.2.5, Java version: 1.8.0_112

**Comment by ohej** [comment]
Thanks for the in-depth report! 

I'll do some investigation around the issue. To ease the reproduction steps, are you able to build a sample project that we can run to reproduce it? Thanks

**Comment by jpotts** [comment]
Feels like this should be a high-priority bug as many people have integration tests in older SDK projects and we want those to keep working after upgrading to SDK 3.

**Comment by tom-vandepoele** [comment]
Having discussed this with Ole during BeeCon, it became apparent that you no longer have to use org.alfresco.util.test.junitrules.ApplicationContextInit. (which fires up the application context)

Don't import the alfresco-repository tests artifact or h2.

Instead, your tests need to start by extending: **org.alfresco.rad.test.AbstractAlfrescoIT**, which provides the application context and service registry of the full alfresco instance which starts up during the integration testing phase by the new alfresco maven plugin.

The All-In-One project makes that clear. (See integration-tests in AIO)

So essentially this means changing your integration tests so application context is received by this superclass. Since we were already using our own abstract superclass which imported it as classrule, changes to our code are minimal.

This can be closed as 'not a bug', though I would recommend adding a single example integration test to the platform-jar-archetype as to make it obvious how to use them from SDK 3.0 forwards.

**Comment by ohej** [comment]
While it could be valuable to add an example, we are pushing forward with SDK 4.0. I'm going to close the issue. If you still think it's valuable with an example test, feel free to raise a pull request.
