### ISSUE TITLE
SDK 3.0 - AIO - 'alfresco-api' has incorrect endpoint-url

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-sdk#452]
## I'm submitting a ...  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior
Generate an AIO project, start up alfresco.
Log in to Share. No message is displayed that share-services is missing.

## Current Behavior
Start an AIO project, start up alfresco.
Log in to Share. A message is displayed that share-services is missing.

Investigation reveals that the endpoint-url of 'alfresco-api' in src\test\resources\share\share-config-custom.xml points to:

`<endpoint-url>${alfresco.repo.url}/alfresco/api</endpoint-url>`

Which resolves to `http://localhost:8080/alfresco/alfresco/api`, 
instead of `http://localhost:8080/alfresco/api`

## Possible Solution
Replace endpoint url line for 'alfresco-api' in share-config-custom.xml with

`<endpoint-url>${alfresco.repo.url}/api</endpoint-url>`

Restart Alfresco.

## Steps to Reproduce (for bugs)
See current behaviour.
1. mvn archetype:generate -Dfilter=org.alfresco: (see http://docs.alfresco.com/5.2/concepts/sdk-getting-started.html, select All-In-One (AIO), give it some groupId and artifactId name.)
2. open src\test\resources\share\share-config-custom.xml
3. verify that the alfresco-api endpoint at the bottom points to the wrong url
4. start alfresco using mvn install alfresco:run
5. go to http://localhost:8080/share, log in with admin user
6. verify there's a message telling you share-services is not installed. See screenshot below.

## Context
Executing an upgrade to Alfresco 5.2 and SDK 3.0

## Your Environment
* Alfresco SDK version used: 3.0
* Alfresco version used: Enterprise 5.2
* Apache Maven 3.2.5, Java version: 1.8.0_112

## Additional information

![afbeelding](https://cloud.githubusercontent.com/assets/16918954/24908823/f12a5098-1ec1-11e7-8161-91a9f9f8f990.png)

**Comment by ohej** [comment]
Thanks for the report. We've already captured and address this in #445. A fix was committed in 68dda3b211796556c834de7bae76dcc5317c79b9 to address it, closing
