### ISSUE TITLE
Tests fail if executed with Java using language different from en

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#457]
```
[x] bug report
[ ] feature request
```

## Expected Behavior
When making changes and packaging the project, the tests phase should not depend on the local machine locale configuration.

## Current Behavior
In my case, my machine is configured for Brazilian Portuguese, and because of that, when I try to compile the project, the tests fail with the message bellow:

```
[INFO] RunTestWebScript: Stopped executing
[INFO] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.19 sec <<< FAILURE! - in it.pkg.platformsample.DemoComponentIT
[INFO] testGetCompanyHome(it.pkg.platformsample.DemoComponentIT)  Time elapsed: 0.169 sec  <<< FAILURE!
[INFO] org.junit.ComparisonFailure: expected:<[Company Home]> but was:<[Página inicial da empresa]>
[INFO]  at it.pkg.platformsample.DemoComponentIT.testGetCompanyHome(DemoComponentIT.java:58)

```

Adding the -Duser.language=en option did not help.
The only way I was able to compile SDK was by using the -DskipTests=true option.

## Steps to Reproduce (for bugs)
Clone the project and execute mvn clean install (in a machine configured with another language supported by Alfresco platform)

## Your Environment
* Alfresco SDK version used: 3.0.1-SNAPSHOT
* Alfresco version used: Community 5.2.f
* Output of command 'mvn -version': 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T14:41:47-02:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: pt_BR, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

**Comment by ohej** [comment]
The easiest way to work around this was to change the assertion in the test so it's not relying on the language pack. Fixed in #529.
