### ISSUE TITLE
Make SDK 3.0.1 compatible with the current GA version (201702-GA)

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#458]
## I'm submitting a ...
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

## Expected Behavior
As the 3.0.1 version is not released yet, I believe it would be nice to have it working with the latest GA version.

## Current Behavior
Right now, all the dependencies are older then the current one.

## Possible Solution
Upgrading all the dependencies

**Comment by ohej** [comment]
Thanks for the contribution! Really appreciate it :)
