### ISSUE TITLE
Purge doesn't remove alf_data_dev and log files

### ISSUE THREAD

**Issue by zhihailiu** [Alfresco/alfresco-sdk#460]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior

In previous SDK, run "mvn clean -Ppurge" will clean up H2 database, alf_data_dev folder and log files. 

## Current Behavior

"purge" doesn't cleanup anymore in SDK 3.0

## Steps to Reproduce (for bugs)

1. mvn clean -Ppurge
2.
3.
4.
5.

## Your Environment

* Alfresco SDK version used:  3.0.0
* Alfresco version used:  Community 5.2
* Output of command 'mvn -version':  3.3.3
* Link to your project:

**Comment by douglascrp** [comment]
There are no more profiles available.
The explanation is in the announcement here https://community.alfresco.com/people/ohej/blog/2017/03/31/announcing-alfresco-sdk-30
````
No forced parent pom - also means we have no profiles
```

**Comment by zhihailiu** [comment]
Thank you
