### ISSUE TITLE
SDK 3.0 change version to Alfresco 5.0 enterprise

### ISSUE THREAD

**Issue by zhihailiu** [Alfresco/alfresco-sdk#461]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior

I am trying to change Alfresco version from
  <alfresco.platform.version>5.2.e</alfresco.platform.version>
  <alfresco.share.version>5.2.d</alfresco.share.version>
  <maven.alfresco.edition>community</maven.alfresco.edition>
to 5.0.2.5 enterprise
  <alfresco.platform.version>5.0.2.5</alfresco.platform.version>
  <alfresco.share.version>5.0.2.5</alfresco.share.version>
  <maven.alfresco.edition>enterprise</maven.alfresco.edition>

## Current Behavior

There is no error in log. But localhost:8080/alfresco does not have the link to "Alfresco Administration Console (admin only)". I can login Share but it says the installation is "Alfresco Community v5.0.2".

By the way, changing the version works in other cases such as 5.1.1 enterprise and 5.0.d community. Not sure why it won't work in the combination of 5.0 and enterprise.

## Steps to Reproduce (for bugs)

1. Change pom.xml as above and start Alfresco
2.
3.
4.
5.

## Your Environment

* Alfresco SDK version used: 
* Alfresco version used: 
* Output of command 'mvn -version':  
* Link to your project:

**Comment by douglascrp** [comment]
@ohej Isn't this one also related with #454 ?
Maybe the problem with the platform artifact name?

**Comment by ohej** [comment]
Thanks for submitting this issue @zhihailiu. This is indeed a bug.
I've located this bug to https://github.com/Alfresco/alfresco-sdk/blob/master/plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java#L1565 where the logic needs to be expanded - but also to account for using the "alfresco-platform" version of the artifacts. 

Unfortunately due this bug there is no easy work around for this bug, we will have to include this in 3.0.1

**Comment by ohej** [comment]
I've committed a fix that fixes this issue, however I'm keeping it open as the fix raises questions around the usage of the `<alfresco.platform.war.artifactId />` property. With the fix I've committed it essentially makes the property useless. Would be worth investigating if the plugin can check if the default value has been overriden

**Comment by ohej** [comment]
@gravitonian Any chance you have any input to the fix I put in 37c26cfaa883a462e9168806acf67be643ebf02c ? You did a pull request that changed the default value of the `<alfresco.platform.war.artifactId />` property, but I'm questioning if it's relevant to keep the property. Let me know if you have any input

**Comment by ohej** [comment]
Note to self: 4.2.x enterprise the artifact ID is `alfresco`, same group id

**Comment by ohej** [comment]
Last commit does indeed address this issue, will be part of 3.0.1 that will be released shortly.

**Comment by ohej** [comment]
3.0.1 has been released to address this issue.

**Comment by zhihailiu** [comment]
Thank you @ohej. 

$mvn archetype:generate -Dfilter=org.alfresco:
and select 2 (for alfresco-allinone-archetype). 
I still see 3.0.0 instead of 3.0.1 in the list. Does it need to specify archetype catalog?

**Comment by touchvignesh** [comment]
@zhihailiu Option 10 should show 3.0.1 among the list.

Choose a number or apply filter (format: [groupId:]artifactId, case sensitive co
ntains): : 2
Choose org.alfresco.maven.archetype:alfresco-allinone-archetype version:
1: 2.0.0-beta-1
2: 2.0.0-beta-2
3: 2.0.0-beta-3
4: 2.0.0-beta-4
5: 2.0.0
6: 2.1.0
7: 2.1.1
8: 2.2.0
9: 3.0.0
10: 3.0.1
Choose a number: 10: 10
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/maven/archetype/a
lfresco-allinone-archetype/3.0.1/alfresco-allinone-archetype-3.0.1.pom....
