### ISSUE TITLE
Images (png/ico/jpg) from share assembly/web corrupted when copied to target/share-war

### ISSUE THREAD

**Issue by mjbrodsky** [Alfresco/alfresco-sdk#468]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior

With SDK 3.0 all-in-one project, images placed in project-share-jar/src/main/assembly/web directory (such as a custom favicon.ico) should be copied to target/share-war. This should work as long as <type>amp</type> is indicated in the project-share-jar moduleDependency as instructed.

## Current Behavior

Images are copied over to the correct destination, but they are corrupt. They cannot be opened on my local computer, and when viewed in the deployed webapp the images look scrambled.

So far, I have seen this behavior with jpg, png, and gif files. Note that I haven't touched the out-of-box maven-resources-plugin settings with all the nonFilteredFileExtensions listed (including ico).

## Possible Solution

Previously documented in #267, then fixed/closed.

## Steps to Reproduce (for bugs)

1. Place custom favicon.ico in project-share-jar/src/main/assembly/web
2. Insert <type>amp</type> in all-in-one pom.xml:
      ```
       <moduleDependency>
             <groupId>${project.groupId}</groupId>
             <artifactId>project-share-jar</artifactId>
             <version>${project.version}</version>
        </moduleDependency>
3. mvn clean install alfresco:run
4. Inspect image copied to target/share-war

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
I cannot use a custom favicon.ico or any images in my custom themes. They all show up as broken links or scrambled images in the webapp.
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Alfresco SDK version used: <!-- 2.1 / 2.2 / 3.0betaX--> 3.0-beta-5
* Alfresco version used: <!-- Enterprise 5.1, Community 5.0.f or ...--> Enterprise 5.2
* Output of command 'mvn -version': <!-- Maven/JDK version--> 
Apache Maven 3.3.9 
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

* Link to your project: <!-- optional for having a minimal example--> [not available]

## Additional information
<!-- include screenshots or any other hint you mave have for us -->
![screen shot 2017-05-18 at 5 31 41 pm](https://cloud.githubusercontent.com/assets/1797278/26224381/1096171e-3bf0-11e7-8ec7-68de4b09e10d.png)

**Comment by douglascrp** [comment]
This is the same problem described in #430

**Comment by mjbrodsky** [comment]
Thanks, you're correct. Changing `<filtered>true</filtered>` to `<filtered>false</filtered>` in the amp.xml file fixed it.
