### ISSUE TITLE
alfresco-maven-plugin 3.0.0 ignore amp files order [CRITICAL]

### ISSUE THREAD

**Issue by Sipaha** [Alfresco/alfresco-sdk#469]
## Expected Behavior

amp files install in a same order as in platformModules and shareModules

## Current Behavior

All amp files just install from ampsLocation and order is ignored:

InstallMojo installMojo = new InstallMojo();
installMojo.setAmpLocation(new File(ampsLocation));
installMojo.setWarLocation(new File(warLocation));
installMojo.setForce(true);
installMojo.execute();

https://github.com/Alfresco/alfresco-sdk/blob/master/plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java#L1153

## Your Environment

* Alfresco SDK version used: 3.0.0
* Alfresco version used:  Community 5.1.2
* Windows 10

**Comment by Sipaha** [comment]
[iproject-mvn3.zip](https://github.com/Alfresco/alfresco-sdk/files/1016912/iproject-mvn3.zip)
Archive with project based on sdk 3 and following error on apply_amps for alfresco.war:

[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0:run (default-cli) on project iproject: Execution default-cli of goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0:run failed: 04210001 An error was encountered during deployment of the AMP into the WAR: 04210000 The following modules must first be installed: [jproject-platform-jar:*] -> [Help 1]

Please note: It's critical bug for projects with multiple modules with dependencies.

**Comment by TheElvenPath** [comment]
+1 same issue

**Comment by Arioh002** [comment]
Same, +1

**Comment by ikaygorodov** [comment]
+1
Please fix.

**Comment by Romancha** [comment]
+1, need a fix

**Comment by AyselSeidova** [comment]
+1, please fix.

**Comment by ilyagalahov** [comment]
I have the same issue. Please fix.

**Comment by andreyplatunov** [comment]
Same problem. Fix is needed.

**Comment by slokoz** [comment]
Very important problem. Fix is needed.

**Comment by Antonlikov** [comment]
same problem

**Comment by mrgrechkinn** [comment]
It's critical issue. Please fix.

**Comment by alexeyesokolov** [comment]
Please fix it

**Comment by nemrioff** [comment]
I need this fix too

**Comment by ohej** [comment]
Good news everyone! This issue has been fixed in #469 and will be included in the SDK 3.1 release.
