### ISSUE TITLE
Support for code coverage reports based on unit and integration test results

### ISSUE THREAD

**Issue by marsv024** [Alfresco/alfresco-sdk#471]
## I'm submitting a ...   (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

## Expected Behavior

It is possible to have the surefire and failsafe plugins generate code coverage data using the maven Jacoco plugin.

## Current Behavior

When unit / integration tests are run, also generate code reports that can be used by external tools for analysis.

## Possible Solution

A guide exists on how to configure the surefire and failsafe plugins to make this work.
https://www.petrikainulainen.net/programming/maven/creating-code-coverage-reports-for-unit-and-integration-tests-with-the-jacoco-maven-plugin/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
5.

## Your Environment

* Alfresco SDK version used:  3.0.0
* Alfresco version used:  5.2 Community
* Output of command 'mvn -version':   
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.4", arch: "x86_64", family: "mac"
* Link to your project:

**Comment by marsv024** [comment]
Some additional resource: https://github.com/eeichinger/jacoco-remote-integration-test-coverage/blob/master/README.md

**Comment by LukasKraushofer** [comment]
Is there any new information about Alfresco SDK 3.x integration tests with jacoco coverage?
I can't get it to work.
