### ISSUE TITLE
Share's hot reload not refreshing changes to Aikau composite widgets

### ISSUE THREAD

**Issue by igorbga** [Alfresco/alfresco-sdk#473]
## I'm submitting a ...   (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior

Whenever a "js" file with an Aikau model changes the HotSwap Agent sees the changes and the next time the page is reloaded you can see the changes.

If the model contains a composite Aikau widget I expect that changes to the composite widget would also be detected and shown in the next reload of the page.

## Current Behavior

Changes to Aikau "js" model files are detected and refreshed properly but if the change is done in a composite widget reloading the page still shows the old version.

The HotSwap Agent seems to detect the change but the change is not applied. Here is the relevant part of the debug output of the hotswap agent: https://pastebin.com/0ZrSdtUa

Doing "mvn alfresco:refresh" does not solve the issue either.

## Steps to Reproduce (for bugs)

1. Create an Aikau composite widget
2. Create a hybrid page that uses the composite widget
3. Change something in the hybrid page and reload, you will see the change
4. Change something in the composite widget and reload the page, you won't see any change

## Context

This issue seriously impacts the development of Aikau pages with composite widgets because it forces the developer to restart whole Alfresco to check every change.

Composite widgets tend to have quite long model definitions and are very prone to syntax errors so being able to develop and check them incrementally is a must.

## Your Environment

* Alfresco SDK version used: 3.0
* Alfresco version used: 5.1.f
* Output of command 'mvn -version': 

Maven home: /home/iblanco/opt/apache-maven-3.2.5
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-79-generic", arch: "amd64", family: "unix"

**Comment by ohej** [comment]
Can you try enabling client-debug and development mode and retest?

Following additions to your `share-config-custom.xml` should do:
```
    <config evaluator="string-compare" condition="WebFramework">
        <web-framework>
            <autowire>
                <mode>production</mode>
            </autowire>
        </web-framework>
    </config>

    <config replace="true">
        <flags>
            <client-debug>true</client-debug>
            <client-debug-autologging>false</client-debug-autologging>
        </flags>
    </config>

```

If you are still seeing errors, please provide a sample project that demonstrates the problem.

**Comment by igorbga** [comment]
I tried enabling it in my project but it didn't make any difference.
So as requested I tried to create a sample project but in the sample project it works like a charm. 
So obviously I have something wrong in my project, sorry for the inconvenience you can close the issue.

If I find what's going on with my project I'll post it here just in case someone else has the same issue.

**Comment by igorbga** [comment]
I finally found the issue.

When declaring my dojo package name instead of doing it like so:

                <package name="tutorials" location="resources/issue473-share-jar/js/tutorials"/>

I was doing it like this:

                <package name="tutorials" location="issue473-share-jar/js/tutorials"/>

I was missing the resources part. I didn't even thought about this kind of error because in fact the packages load and work correctly but they just don't reload. I suppose that the SDK is doing some kind of overlapping of the classpath that makes the JS's accesible even declaring them wrong, but of course the hot reloading those not relate the changed files with those.
