### ISSUE TITLE
Feature request: adding support for custom solr config

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-sdk#474]
## I'm submitting a ...  
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

## Expected Behavior
I can add custom solr configuration, which gets picked up by the alfresco-maven-plugin when executing alfresco:run, without any manual intervention.

## Current Behavior
Currently the alfresco-maven-plugin checks on start if the "alf_data_dev/solr" folder exists, if it doesn't it grabs the OOTB solr configuration zip, does some filtering and other operations and puts it in.
If it does exist the alf_data_dev/solr is left as-is.

So the only way to use custom solr config at the moment is to execute an alfresco:run, stop it, change the files you need changed then execute alfresco:run again.

## Possible Solution
Have a folder "src/test/resources/solr" in which you can put in custom solr configuration files, which will be automatically injected into "alf_data_dev/solr", so a developer can overwrite any files needed. If a developer doesn't need this feature he/she can simply leave that folder empty.

If you add a method between fixSolrHomePath(); and replaceSolrConfigProperties(); in the RunMojo of alfresco-maven-plugin to execute the copy (overwrite!), developers could use the @@ALFRESCO_SOLR4_DATA_DIR@@ and @@ALFRESCO_SOLR_DIR@@ variables as to have machine-independent paths in his custom config.

## Context
In Enterprise environments SOLR is often customized to improve the end-users search experience. It would take little effort to add this feature to the alfresco-maven-plugin, and save us from having to do a lot of restarts.

## Your Environment
* Alfresco SDK version used: 3.0.0
* Alfresco version used: Enterprise 5.2
Apache Maven 3.2.5, Java version: 1.8.0_112

**Comment by ohej** [comment]
Hi Tom

Thanks for the feedback. This is indeed an interesting use case and definitely something we should add. I have set this for a 3.1 milestone initially, but will have to review it later.

It looks like you have already had a look at the code, if you want, I would be more than happy to help you implement this feature (if you need any guidance I'm more than happy to help) and you could do a PR? 

Let me know what you think, otherwise we let it sit in the backlog and will get picked up :)

/Ole

**Comment by tom-vandepoele** [comment]
Hi Ole,

I've tested this change locally, and created the pull request: https://github.com/Alfresco/alfresco-sdk/pull/475

If there are any remarks, or anything else is expected I'll be happy to make the changes.

**Comment by ohej** [comment]
Thanks, Tom! I will review this ASAP and get back to you :)

**Comment by ohej** [comment]
PR accepted, closing the issue, thanks for the contribution!
