### ISSUE TITLE
Fix null check to work with assertEqual-failures and exception messages containing reserved xml characters

### ISSUE THREAD

**Issue by marsv024** [Alfresco/alfresco-sdk#485]
See PR  #484  for bug report.

@ohej This is a follow up to #477 which I also proposed a solution for in #472. The #472 solution did not have this issue. Greatful if this could be merged into master and snapshot built for the sonatype snapshot repo.

**Comment by ohej** [comment]
Thanks for the PR. I've merged now, if the build is green (which it should be) the snapshots should automatically be produced. I'll update the issue when it's done and you can verify

**Comment by marsv024** [comment]
Thanks for quick handling! 👍

**Comment by ohej** [comment]
The build was successful and the snapshots are now on Maven central

**Comment by marsv024** [comment]
Works! Closing issue
