### ISSUE TITLE
SDK 3.0.1 archetypes missing in catalog https://artifacts.alfresco.com/nexus/content/groups/public/archetype-catalog.xml

### ISSUE THREAD

**Issue by pzrinscak** [Alfresco/alfresco-sdk#494]
It is not clear how to use SDK 3.0.0 and 3.0.1

You say on your front page that 3.0.1. has been released

when I run

mvn archetype:generate -Dfilter=org.alfresco:

and which ever archetype I choose I'm only offered with 

[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
1: remote -> org.alfresco:aikau-sample-archetype (A Maven archetype for quickly creating pre-configured clients for accessing a locally hosts Alfresco Repository)
2: remote -> org.alfresco:alfresco-benchmark-bm-sample-archetype (-)
3: remote -> org.alfresco:alfresco-benchmark-client-archetype (-)
4: remote -> org.alfresco:alfresco-benchmark-sample-archetype (-)
5: remote -> org.alfresco:maven-alfresco-amp-archetype (This archetype aims to provide a standardized approach to development, release and deployment of Alfresco AMPs (as opposed to Alfresco
                extensions, released as a different artifact ))
6: remote -> org.alfresco:maven-alfresco-extension-archetype (This archetype developed aims to provide a standardized approach to development, release and deployment of Alfresco extensions (as opposed to
                AMP builds, to be released as a different artifact ).)
7: remote -> org.alfresco.enablement.codecamps.cmis:cmis-master-labs-archetype (-)
8: remote -> org.alfresco.maven:maven-alfresco-share-archetype (Maven Archetype to allow Maven based customization of Alfresco SHARE)
9: remote -> org.alfresco.maven:maven-alfresco-share-module-archetype (-)
10: remote -> org.alfresco.maven.archetype:activiti-jar-archetype (Sample project with full support for lifecycle and rapid development of Activiti JARs)
11: remote -> org.alfresco.maven.archetype:alfresco-allinone-archetype (Sample multi-module project for All-in-One development on the Alfresco plaftorm. Includes modules for: Repository, AMP, Share, Solr, Web Quick Start and embedded Jetty run)
12: remote -> org.alfresco.maven.archetype:alfresco-amp-archetype (Sample project with full support for lifecycle and rapid development of AMPs (Alfresco Module Packages))
13: remote -> org.alfresco.maven.archetype:alfresco-platform-jar-archetype (Sample project with full support for lifecycle and rapid development of Platform/Repository JARs and AMPs (Alfresco Module Packages))
14: remote -> org.alfresco.maven.archetype:alfresco-share-jar-archetype (Share project with full support for lifecycle and rapid development of JARs and AMPs (Alfresco Module
        Packages))
15: remote -> org.alfresco.maven.archetype:share-amp-archetype (Share project with full support for lifecycle and rapid development of AMPs (Alfresco Module Packages))
16: remote -> org.alfresco.surf:spring-surf-archetype (-)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :

**Comment by ohej** [comment]
We don't rely on our own nexus to host the archetypes, they are all on Maven central.
