### ISSUE TITLE
Cannot execute tests declared in abstract classes

### ISSUE THREAD

**Issue by tartard** [Alfresco/alfresco-sdk#495]
## I'm submitting a ...   (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

Assume we have a test Class B which extends an abstract class A.
A has a test method methodA.

## Expected Behavior

When running test B#methodA using the AlfrescoTestRunner, the runner should instantiate the class being executed, i.e B.

## Current Behavior

The remote AlfrescoTestRunner tries to instantiate the class A instead of B. Since A is abstract, an InstantiationException is thrown \:

RunTestWebScript: Start executing ...
RunTestWebScript: clazzAndMethod = **me.tartard.alfresco.demo.PR491.AbstractIT#test**
RunTestWebScript: [clazz=me.tartard.alfresco.demo.PR491.AbstractIT][method=test]
RunTestWebScript: model = {result=FAILURE, throwables=[rO0ABXNyACBqYXZhLmxhbmcuSW5zdGFudGlhdGlvbkV4Y2VwdGlvborYPidN1YWKAgAAeHIAJmphdmE
...], failures=[test(me.tartard.alfresco.demo.PR491.AbstractIT): null], test=me.tartard.alfresco.demo.PR491.AbstractIT#test#test, ignoreCount=0, wasSuccessful=false, runTime=32, runCount=1, resultObject=org.junit.runner
.Result@7ae67e6c, failureCount=1}
RunTestWebScript: Stopped executing
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.104 sec <<< FAILURE! - in me.tartard.alfresco.demo.PR491.ChildIT
test(me.tartard.alfresco.demo.PR491.ChildIT)  Time elapsed: 0.424 sec  <<< ERROR!
**java.lang.InstantiationException**

Results :

Tests in error:
  ChildIT.test » Instantiation

## Possible Solution
Merge Pull Request #491 

## Steps to Reproduce (for bugs)

1. Run :
```
$ git clone https://github.com/Alfresco/alfresco-sdk.git
$ cd alfresco-sdk/modules/alfresco-rad
$ mvn clean install -DskipTests
```
2. Run :
```
$ git clone https://github.com/tartard/test-sdk3.git
$ cd test-sdk3
$ mvn clean verify -Dit.test=ChildIT
```
3. 
4.
5.

## Context

We are currently migrating our projects from SDK 2.1.1 to SDK 3.0.1 to prepare an Alfresco migration from v5.0.1 to v5.2.
In our projects we have a lot of integration tests and are trying to make them pass using the AlfrescoTestRunner.

## Your Environment

* Alfresco SDK version used: 3.0.1
* Alfresco version used: Enterprise 5.0.1
* Output of command 'mvn -version': 
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Users\b88779\Programmes\apache-maven-3.3.3
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_144\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by ohej** [comment]
We've merged #491, thanks for the contribution. This will be included in SDK 3.1
