### ISSUE TITLE
3.0.2 release

### ISSUE THREAD

**Issue by marsv024** [Alfresco/alfresco-sdk#504]
Could we please have a 3.0.2 release which sums up the bug fixes made in 2017 on master and that now are in 3.0.2-snapshot on central?

**Comment by marsv024** [comment]
@ohej

Since you started working on sdkn 4.0 the snapshot version 3.0.2 got pushed to the sonatype repo replacing the old 3.0.2 snapshot version breaking our builds depending on it. Please release the master branch to 3.0.2 asap.

Thanks!

**Comment by ohej** [comment]
We're ramping up to push a 3.1 release soon, apologies for the long delay.
