### ISSUE TITLE
Alfresco-maven-plugin issue

### ISSUE THREAD

**Issue by AzizADD** [Alfresco/alfresco-sdk#506]
Hi,
I'm new in alfresco, when trying to configure Alfresco Maven plugin, i have a building errors (see an extract from the log below).

thanks in advance. 

- Windows 7
- Java 1.8
- Alfresco Enterprise - 5.2.3
- apache-maven-3.5.4

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.2.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.2.0 -> org.alfrescolabs.alfresco-technical-validation:org.alfrescolabs.alfresco-technical-validation:jar:0.6.0 -> clojurewerkz:neocons:jar:3.0.0 -> clj-http:clj-http:jar:0.9.1 -> crouton:crouton:jar:0.1.1 -> org.jsoup:jsoup:jar:1.7.1 @ 
[ERROR] Non-resolvable import POM: Could not transfer artifact org.alfresco:alfresco-platform-distribution:pom:5.2.f from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): Access denied to: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.2.f/alfresco-platform-distribution-5.2.f.pom , ReasonPhrase:Forbidden. @ line 70, column 25
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.GedRma:alfrescoMono:1.0-SNAPSHOT (C:\ProjetsJava\Alfresco\alfrescoMono\pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.2.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.2.0 -> org.alfrescolabs.alfresco-technical-validation:org.alfrescolabs.alfresco-technical-validation:jar:0.6.0 -> clojurewerkz:neocons:jar:3.0.0 -> clj-http:clj-http:jar:0.9.1 -> crouton:crouton:jar:0.1.1 -> org.jsoup:jsoup:jar:1.7.1: Failed to read artifact descriptor for org.jsoup:jsoup:jar:1.7.1: Could not transfer artifact org.jsoup:jsoup:pom:1.7.1 from/to sonatype-public (http://oss.sonatype.org/content/groups/public): Access denied to: http://oss.sonatype.org/content/groups/public/org/jsoup/jsoup/1.7.1/jsoup-1.7.1.pom , ReasonPhrase:Forbidden. -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.alfresco:alfresco-platform-distribution:pom:5.2.f from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): Access denied to: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.2.f/alfresco-platform-distribution-5.2.f.pom , ReasonPhrase:Forbidden. @ line 70, column

**Comment by douglascrp** [comment]
You say you are using Enterprise.
Have you setup your environment as described at https://docs.alfresco.com/5.2/concepts/sdk-using-enterprise.html ?

**Comment by AzizADD** [comment]
It's resolved. 
Thanks. 

1. I added in maven setting (setting.xml) :
 ```
<profile>
        <id>alwaysActive</id>
        <activation>
                 <activeByDefault>true</activeByDefault>
        </activation>
      <repositories>
        <repository>
          <id>clojars</id>
          <name>Clojars</name>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>http://clojars.org/repo</url>
          <layout>default</layout>
        </repository>
      </repositories>
      <pluginRepositories>
      </pluginRepositories>
    </profile>    
```
2. I Updated maven dependencies with selecting "Force Update of snapshots/Releases"
