### ISSUE TITLE
SDK 4 documentation improvement: Installing 3rd Party AMPs

### ISSUE THREAD

**Issue by jpotts** [Alfresco/alfresco-sdk#526]
[This document ](https://github.com/Alfresco/alfresco-sdk/blob/sdk-4/documentation-update/docs/advanced-topics/amps.md)describes installing third-party AMPs by adding a dependency to the platform or share project.

You can do that, but if you do, the AMPs will be added to that project's AMP when it is built, which is probably not what you want.

Instead, the dependency should be added to the *docker* module for platform/share. When you do this, the third-party AMPs are properly added to the docker images but are not added to the platform and share AMPs that get built, which is the correct behavior.

**Comment by ohej** [comment]
Thanks for spotting this! The documentation has been updated with #527.
