### ISSUE TITLE
Not able to execute the project after changing version from 1.0-SNAPSHOT into newer one

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#548]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior
A new project is created, usually using a default version of 1.0-SNAPSHOT
Once the project is ready to be release, the version is changed to 1.0
With the new version in place, by setting the project's version as <version>1.0</version>, if one tries to execute it again using 
```
./run.sh build_start
```
The project should start without any problem.

## Current Behavior
A new project is created, usually using a default version of 1.0-SNAPSHOT
Once the project is ready to be release, the version is changed to 1.0
With the new version in place, by setting the project's version as <version>1.0</version>, if one tries to execute it again using 
```
./run.sh build_start
```
The execution log shows:
```
[INFO] --- maven-dependency-plugin:3.0.2:copy (copy-repo-extension) @ my-project-repo ---
[INFO] Configured Artifact: br.com.dgcloud:my-project-repo:1.0-SNAPSHOT:jar
```
When it should be 
```
br.com.dgcloud:my-project-repo:1.0:jar
```

## Possible Solution
A simple fix for this is to set the project's dependency version, inside the maven-dependency-plugin, as follow:
```
<artifactItem>
    <groupId>br.com.dgcloud</groupId>
    <artifactId>my-project-repo</artifactId>
    <version>**${project.version}**</version>
    <overWrite>false</overWrite>
    <outputDirectory>${project.build.directory}/extensions</outputDirectory>
</artifactItem>
```

The problem right now is because the version is hardcoded when the project is first created, and has to be updated manually by the developer.

## Steps to Reproduce (for bugs)
1. Create a new jar platform project, setting version as 1.0-SNAPSHOT
2. Execute the project using ./run.sh build_start
3. Stop the project
4. Change the project's version to 1.0
5. Execute the project again

## Your Environment

* Alfresco SDK version used: 4.0-beta1
* Alfresco version used: Community 6.0.7-ga
* Output of command 'mvn -version': Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-45-generic", arch: "amd64", family: "unix"

**Comment by ohej** [comment]
Fixed in #555
