### ISSUE TITLE
Share image doesn't have the project's generated jar updated after changing the project's version

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#549]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior
Once the project's version is changed from 1.0-SNAPSHOT into something else, the resulting image should have the generated artifact updated.

## Current Behavior
Just like with the alfresco-jar artifact, the share-jar artifact has the version hard-coded inside the section below:
```
<execution>
    <id>copy-repo-extension</id>
    <phase>pre-integration-test</phase>
    <goals>
        <goal>copy</goal>
    </goals>
    <configuration>
        <artifactItems>
            <artifactItem>
                <groupId>br.com.dgcloud</groupId>
                <artifactId>project-share</artifactId>
                <version>1.0-SNAPSHOT</version>
                <overWrite>false</overWrite>
                <outputDirectory>${project.build.directory}/extensions</outputDirectory>
            </artifactItem>
         </artifactItems>
     </configuration>
</execution>
```
This is similar to what is described in https://github.com/Alfresco/alfresco-sdk/issues/548

## Possible Solution
Replacing the hard coded version with ${project.version} would fix the issue, just like:

```
<execution>
    <id>copy-repo-extension</id>
    <phase>pre-integration-test</phase>
    <goals>
        <goal>copy</goal>
    </goals>
    <configuration>
        <artifactItems>
            <artifactItem>
                <groupId>br.com.dgcloud</groupId>
                <artifactId>project-share</artifactId>
                <version>${project.version}</version>
                <overWrite>false</overWrite>
                <outputDirectory>${project.build.directory}/extensions</outputDirectory>
            </artifactItem>
         </artifactItems>
     </configuration>
</execution>
```

## Steps to Reproduce (for bugs)
1. Create a new jar share project, setting version as 1.0-SNAPSHOT
2. Execute the project using ./run.sh build_start
3. Stop the project
4. Change the project's version to 1.0
5. Execute the project again

## Your Environment

* Alfresco SDK version used: 4.0-beta1
* Alfresco version used: Community 6.0.7-ga
* Output of command 'mvn -version': Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-45-generic", arch: "amd64", family: "unix"

**Comment by ohej** [comment]
Fixed in #555
