### ISSUE TITLE
Make the alfresco-share-jar-archetype's docker-compose.yml dependencies for acs, ass and pgsql optional by default

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-sdk#551]
## I'm submitting a ...   (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

## Expected Behavior
Usually developers have different projects for each layer (acs and share), and before sdk 4.0, it was easy to have separate projects that could be restarted independently.

Just like the docker-compose.yml for the alfresco-platform-jar-archetype has the ${rootArtifactId}-share configuration commented out, I think it would be nice to have the same for the alfresco-share-jar-archetype

## Current Behavior
Right now, when one creates a project based on the alfresco-share-jar-archetype, it comes with all the repository side elements configured to be executed by the run.sh script.
If the developer also has a project based on the alfresco-platform-jar-archetype, containing custom logic/content model, it is not required to have all the components running by the share project.

## Possible Solution
It would be ideal to let the developer select, by configuring the acs.repo and acs.port properties inside the pom.xml file which repository to use.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
5.

## Your Environment
* Alfresco SDK version used: 4.0-beta1
* Alfresco version used: Community 6.0.7-ga
* Output of command 'mvn -version': Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-45-generic", arch: "amd64", family: "unix"

**Comment by ohej** [comment]
Merged, Thanks for the contribution :)
