### ISSUE TITLE
add an install option to run.sh build (or just create a new command run.sh install)

### ISSUE THREAD

**Issue by rmknightstar** [Alfresco/alfresco-sdk#565]
There is no way to install the AMP/JAR that you are creating into your local maven repository.  This would make it easier to include it in other runner instances.

**Comment by narkuss** [comment]
Change your run.bat or run.sh files to execute mvn clean install instead of mvn clean package:

![image](https://user-images.githubusercontent.com/28560745/57655200-5883e200-75d6-11e9-8ab2-17b618c84a43.png)
