### ISSUE TITLE
SDK4 model custom not visible

### ISSUE THREAD

**Issue by fraveau** [Alfresco/alfresco-sdk#570]
Hi,

When trying to customize the SDK4 model according to the "Working With Custom Content Types in Alfresco" tutorial, the new types do not show in rules pages

I have modified the bootstrap-context.xml and created my model in ftth-model.xml (see attach). The application start well but I don't see the new types or aspects in the rule page.

Thanks

FTTH-model.xml

<?xml version="1.0" encoding="UTF-8"?>

<model name="sc:somecomodel" xmlns="http://www.alfresco.org/model/dictionary/1.0">
    
    <description>Someco Model</description>
    <author>Jeff Potts</author>
    <version>1.0</version>

    
    <imports>
        
        <import uri="http://www.alfresco.org/model/dictionary/1.0" prefix="d" />
        
        <import uri="http://www.alfresco.org/model/content/1.0" prefix="cm" />
    </imports>

    
    <namespaces>
        <namespace uri="http://www.someco.com/model/content/1.0" prefix="sc" />
    </namespaces>
    <constraints>
        <constraint name="sc:campaignList" type="LIST">
            <parameter name="allowedValues">
                <list>
                    <value>Application Syndication</value>
                    <value>Private Event Retailing</value>
                    <value>Social Shopping</value>
                </list>
            </parameter>
        </constraint>
    </constraints>

    <types>
        
        <type name="sc:doc">
            <title>Someco Document</title>
            <parent>cm:content</parent>
            <associations>
                <association name="sc:relatedDocuments">
                    <title>Related Documents</title>
                    <source>
                        <mandatory>false</mandatory>
                        <many>true</many>
                    </source>
                    <target>
                        <class>sc:doc</class>
                        <mandatory>false</mandatory>
                        <many>true</many>
                    </target>
                </association>
            </associations>
            <mandatory-aspects>
                <aspect>cm:generalclassifiable</aspect>
            </mandatory-aspects>
        </type>

        <type name="sc:whitepaper">
            <title>Someco Whitepaper</title>
            <parent>sc:doc</parent>
        </type>
        <type name="sc:facture">
            <title>Facture SFR FTTH</title>
            <parent>sc:doc</parent>
        </type>
        <type name="sc:marketingDoc">
            <title>Someco Marketing Document</title>
            <parent>sc:doc</parent>
            <properties>
                <property name="sc:campaign">
                    <type>d:text</type>
                    <multiple>true</multiple>
                    <constraints>
                        <constraint ref="sc:campaignList" />
                    </constraints>
                </property>
            </properties>
        </type>

    </types>

    <aspects>
        <aspect name="sc:webable">
            <title>Someco Webable</title>
            <properties>
                <property name="sc:published">
                    <type>d:date</type>
                </property>
                <property name="sc:isActive">
                    <type>d:boolean</type>
                    <default>false</default>
                </property>
            </properties>
        </aspect>
        <aspect name="sc:productRelated">
            <title>Someco Product Metadata</title>
            <properties>
                <property name="sc:product">
                    <type>d:text</type>
                    <mandatory>true</mandatory>
                    <multiple>true</multiple>
                </property>             
                <property name="sc:version">
                    <type>d:text</type>
                    <mandatory>true</mandatory>
                    <multiple>true</multiple>
                </property>
            </properties>
        </aspect>
    </aspects>
</model>

bootstrap-context.xml

<?xml version='1.0' encoding='UTF-8'?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
          http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

    

     
  
  <bean id="${project.artifactId}_dictionaryBootstrap" parent="dictionaryModelBootstrap" depends-on="dictionaryBootstrap">
    <property name="models">
        <list>
        
            <value>alfresco/module/${project.artifactId}/model/ftth-model.xml</value> 
        </list>
    </property>
</bean>
  
  
  
</beans>

**Comment by douglascrp** [comment]
Hello.

This is not a problem with the SDK, but it is because you have not finished the tutorial.
If you keep following it, you will find this:

```
<types>
    <type name="cm:content">
        <subtype name="sc:doc" />
        <subtype name="sc:whitepaper" />
    </type>
    <type name="sc:doc">
        <subtype name="sc:whitepaper" />
    </type>
</types>
```
Follow the steps described in https://ecmarchitect.com/alfresco-developer-series-tutorials/content/tutorial/tutorial.html#part-2-configuring-alfresco-share and you will see the type.
