### ISSUE TITLE
"Making the new page the default" - not working

### ISSUE THREAD

**Issue by kachaj7** [Alfresco/alfresco-sdk#572]
## I'm submitting a ...   (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior
Should set new default page after success login.

## Current Behavior
Is still default Alfresco page.

## Steps to Reproduce (for bugs)

1. https://docs.alfresco.com/6.1/tasks/dev-extensions-share-tutorials-add-page.html
2. https://docs.alfresco.com/6.1/tasks/dev-extensions-share-tutorials-make-default.html

**Comment by jlosornogil** [comment]
Hello @kachaj7 

I've created a new AIO project from scratch using the SDK 4 and I've followed the steps of the tutorials and it has worked properly for me.

Are you sure you've restarted the service after the configuration changes?
