### ISSUE TITLE
hotswap-agent Not working with Windows 10, Docker Desktop for Windows

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/alfresco-sdk#576]
I have a project i built on Mac with hotswap-agent applied/enabled that works. Hot reloading does not work on same project run on Windows 10 laptop with Docker Desktop for Windows. Have checked container and mapped volumes are present in project, etc but on mvn compile
no messages are triggered, no reloading occurs. 
Any suggestions as to why, what issue might be?

**Comment by 10SPD** [comment]
@mtwallach you have SDK4 with hot-swap working? We cannot seem to get that working at all  - what were your steps?
