### ISSUE TITLE
"Deprecated" warning is displayed when building

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-sdk#578]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

Deprecated warning is displayed when building.

## Expected Behavior

No deprecated warning is displayed.

## Current Behavior

The following warning is output.

- Platform Archetype
```
$ ./run.sh build_start
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for <Group ID>:<Archetype ID>:jar:1.0-SNAPSHOT
[WARNING] The expression ${build.finalName} is deprecated. Please use ${project.build.finalName} instead.
[WARNING] The expression ${build.finalName} is deprecated. Please use ${project.build.finalName} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

- Share Archetype
```
$ ./run.sh build_start
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for <Group ID>:<Archetype ID>:jar:1.0-SNAPSHOT
[WARNING] The expression ${build.finalName} is deprecated. Please use ${project.build.finalName} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

## Possible Solution

The workaround is to modify `${build.finalName}` to `${project.build.finalName}` in the `pom.xml` file.

## Steps to Reproduce (for bugs)

1. Create a Platform/Share archetype project using `mvn archetype:generate -Dfilter=org.alfresco:` command
2. Move created project folder
3. Start build using `./run.sh build_start`

## Context

Occurs when a build is executed after creating a template.
If the Maven version changes in the future and the property is deleted, the build may not be able to be executed.

## Your Environment

* Alfresco SDK version used: 4.0.0
* Alfresco version used: 6.1.2-ga
* Output of command 'mvn -version': Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-28T00:06:16+09:00)
* Link to your project: 

## Additional information

Displayed in Platform Archetype and Share Archetype.

**Comment by jlosornogil** [comment]
This will be included in sdk-4.1 https://github.com/Alfresco/alfresco-sdk/pull/581.
Thanks @silverskyvicto !
