### ISSUE TITLE
Java 11 Maven All In One project pom.xml format has many blank lines 

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/alfresco-sdk#597]
## I'm submitting a ...   (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior
Properly formatted pom.xml
## Current Behavior
pom.xml contains many blank lines making it difficult, unpleasant to read
## Steps to Reproduce (for bugs)

1. Set your JAVA_HOME to use Java 11
2. Using Maven 3.6.1 generate an all in one Alfresco archetype project.
3. Edit pom.xml file, you will see the properties are all spread out by 5 blank lines. (I have attached mine for review to the case.)
4. Set your JAVA_HOME to use Java 8 
5. Repeat steps to generate all in one project.
6. Edit pom.xml and notice the file is formatted correctly.

Can attach pom if needed.

 
## Your Environment

* Alfresco SDK version used: 4.1
* Alfresco version used: 6.2
* Output of command 'mvn -version': Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
* Link to your project:

**Comment by CharlesCZ** [comment]
You can do workaround, by simple removing blank spaces like 
![Screenshot from 2020-07-02 18-46-08](https://user-images.githubusercontent.com/37272177/86388068-64c47600-bc94-11ea-8925-27d253432a84.png)
Then press CTRL+ALT+L
