### ISSUE TITLE
SDK 4.2 is not displayed 🥺

### ISSUE THREAD

**Issue by Wity4** [Alfresco/alfresco-sdk#610]
I want to try the new SDK, but unfortunately I don't see sdk 4.2 in the list as described here:  https://github.com/Alfresco/alfresco-sdk/blob/master/docs/getting-started.md

> Vit-MacBook-Pro:shareevitax vitsanda$ mvn archetype:generate -Dfilter=org.alfresco:
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< shareevitax:shareevitax >-----------------------
[INFO] Building shareevitax Share JAR Module 1.7
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ shareevitax >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-and-filter-docker-compose-resources) @ shareevitax ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-and-filter-docker-resources) @ shareevitax ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ shareevitax <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ shareevitax ---
[INFO] Generating project in Interactive mode
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
1: remote -> org.alfresco.maven.archetype:activiti-jar-archetype (DEPRECATED - UNSUPPORTED - EXPERIMENTAL)
2: remote -> org.alfresco.maven.archetype:alfresco-allinone-archetype (Sample multi-module project for All-in-One development on the Alfresco platform. Includes modules for Platform/Repository JAR and Share JAR)
3: remote -> org.alfresco.maven.archetype:alfresco-amp-archetype (Sample project with full support for lifecycle and rapid development of Repository AMPs (Alfresco Module Packages))
4: remote -> org.alfresco.maven.archetype:alfresco-platform-jar-archetype (Sample project with full support for lifecycle and rapid development of Platform/Repository JARs and AMPs (Alfresco Module Packages))
5: remote -> org.alfresco.maven.archetype:alfresco-share-jar-archetype (Share project with full support for lifecycle and rapid development of JARs and AMPs (Alfresco Module
        Packages))
6: remote -> org.alfresco.maven.archetype:share-amp-archetype (Share project with full support for lifecycle and rapid development of AMPs (Alfresco Module
        Packages))
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): : 4
Choose org.alfresco.maven.archetype:alfresco-platform-jar-archetype version: 
1: 3.0.0
2: 3.0.1
3: 3.1.0
4: 4.0.0-beta-1
5: 4.0.0
6: 4.1.0
Choose a number: 6:

**Comment by Fikili** [comment]
Hi Vít,
as far as I know, SDK4.2 is just in "creation" process for Alfresco 7. You can use SDK 4.1 for now.
Ahoj,
Filip
