### ISSUE TITLE
Missing org.alfresco.authorization:alfresco-authorised-users:jar:7.1

### ISSUE THREAD

**Issue by am-tribia** [Alfresco/alfresco-sdk#615]
Could not find artifact org.alfresco.authorization:alfresco-authorised-users:jar:7.1

I can see the 7.0 in the alfresco maven nexus (https://artifacts.alfresco.com/nexus/service/local/repositories/enterprise-releases/content/org/alfresco/authorization/alfresco-authorised-users/7.0/alfresco-authorised-users-7.0.jar), but not this version.

Could you please publish the org.alfresco.authorization:alfresco-authorised-users:jar:7.1 artifact?

Here is the snippet of mvn error msg

[INFO]
[INFO] ---------------< tribia.interaxo:alfresco-ext-platform >----------------
[INFO] Building Alfresco Platform/Repository JAR Module 1.0-SNAPSHOT      [2/6]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.alfresco:alfresco-elasticsearch-shared:jar:3.0.0-M1 is missing, no dependency information available
[WARNING] The POM for org.alfresco.authorization:alfresco-authorised-users:jar:7.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for AIO - SDK 4.2 1.0-SNAPSHOT:
[INFO]
[INFO] AIO - SDK 4.2 ...................................... SUCCESS [  0.390 s]
[INFO] Alfresco Platform/Repository JAR Module ............ FAILURE [  0.922 s]
[INFO] Alfresco Share JAR Module .......................... SKIPPED
[INFO] Integration Tests Module ........................... SKIPPED
[INFO] Alfresco Platform/Repository Docker Module ......... SKIPPED
[INFO] Alfresco Share Docker Module ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.425 s
[INFO] Finished at: 2021-03-22T06:43:07+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alfresco-ext-platform: Could not resolve dependencies for project tribia.interaxo:alfresco-ext-platform:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.alfresco.authorization:alfresco-authorised-users:jar:7.1, org.alfresco:alfresco-elasticsearch-shared:jar:3.0.0-M1: Failure to find org.alfresco.authorization:alfresco-authorised-users:jar:7.1

`
<alfresco.bomDependencyArtifactId>acs-packaging</alfresco.bomDependencyArtifactId>
<alfresco.platform.version>7.0.0</alfresco.platform.version>
<alfresco.share.version>7.0.0</alfresco.share.version>
`
Thanks.

**Comment by andrea-ligios** [comment]
Hi, I can see 7.1 version is there since February: 
![image](https://user-images.githubusercontent.com/11974750/112011262-625ac280-8b28-11eb-826f-423119ec080e.png)

![image](https://user-images.githubusercontent.com/11974750/112011269-6555b300-8b28-11eb-9ae9-8f88d6e1f06c.png)

Can you please check your URL and retry?

If you still have problems, please post your full pom.xml and the exact sequence of commands you've used, thank you.

**Comment by am-tribia** [comment]
Hi,

I am attaching my view of the nexus repository.

<img width="1128" alt="Screenshot 2021-03-22 at 16 10 00" src="https://user-images.githubusercontent.com/58597840/112012506-8a96f100-8b29-11eb-846c-c5c63ef61a0d.png">

I don't see any artifacts related to 7.1

Cheers

Ayyanar.M

**Comment by andrea-ligios** [comment]
You're right, it's there in another repository but not in `enterprise-releases` , yet.
We're on it, thank you.

**Comment by andrea-ligios** [comment]
The artifact for 7.1 has been ported to `enterprise-releases` as well, please retry @am-tribia

**Comment by am-tribia** [comment]
@andrea-ligios,

I could see the 7.1 artifact now, thank you. Now i get the following error when building the enterprise project.

<img width="1594" alt="Screenshot 2021-03-23 at 12 10 43" src="https://user-images.githubusercontent.com/58597840/112137736-e8cadf00-8bd0-11eb-9056-78376cf053c1.png">

**Comment by am-tribia** [comment]
@andrea-ligios Thank you, now i see its published and available in enterprise repository

**Comment by andrea-ligios** [comment]
You're welcome

**Comment by am-tribia** [comment]
@andrea-ligios looks like you have included the classifier as M1

`
<dependency>
  <groupId>org.alfresco</groupId>
  <artifactId>alfresco-elasticsearch-shared</artifactId>
  <version>3.0.0-M1</version>
  <classifier>M1</classifier>
</dependency>
`

<img width="553" alt="Screenshot 2021-03-24 at 10 19 35" src="https://user-images.githubusercontent.com/58597840/112285338-7fa7a200-8c8a-11eb-8c8b-0094d420b2f0.png">


Could you please fix this?

**Comment by andrea-ligios** [comment]
It should be fine now, please let me know if you find anything else @am-tribia
