### ISSUE TITLE
Receiving Error on new SDK build

### ISSUE THREAD

**Issue by ESWBitto** [Alfresco/alfresco-sdk#620]
## I'm submitting a ...   (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior

When I run ./run.sh build_start it should build the project and I should be able to go to http://my.ip:8080/share nothing happens.

## Current Behavior

Receiving Error Message.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
5.

## Your Environment

* Alfresco SDK version used: 
* 4.2
* Alfresco version used: 
* should be the newest community edition 6.x
* Output of command 'mvn -version': 
* Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.11, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-1.el7_9.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.24.1.el7.x86_64", arch: "amd64", family: "unix" 
Docker version 20.10.6, build 370c289
docker-compose version 1.29.1, build c34c88b2

## Additional information

alfresco-dev-upgrade-acs_1       | 27-Apr-2021 20:40:15.435 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
alfresco-dev-upgrade-acs_1       | 27-Apr-2021 20:40:15.451 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [47960] milliseconds
alfresco-dev-upgrade-acs_1       |  2021-04-27 20:40:15,552  INFO  [management.subsystems.ChildApplicationContextFactory] [http-nio-8080-exec-1] Starting 'Search' subsystem, ID: [Search, managed, solr6]
alfresco-dev-upgrade-acs_1       |  2021-04-27 20:40:15,862  INFO  [management.subsystems.ChildApplicationContextFactory] [http-nio-8080-exec-1] Startup of 'Search' subsystem, ID: [Search, managed, solr6] complete
alfresco-dev-upgrade-acs_1       |  2021-04-27 20:40:20,115  ERROR [component.jms.DefaultJmsMessageListenerContainer] [Camel (alfrescoCamelContext) thread #0 - JmsConsumer[acs-repo-transform-request]] Could not refresh JMS Connection for destination 'acs-repo-transform-request' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not create Transport. Reason: java.io.IOException: Transport scheme NOT recognized: [vm]
alfresco-dev-upgrade-acs_1       |  2021-04-27 20:40:20,136  ERROR [component.jms.DefaultJmsMessageListenerContainer] [Camel (alfrescoCamelContext) thread #1 - JmsConsumer[acs-repo-rendition-events]] Could not refresh JMS Connection for destination 'acs-repo-rendition-events' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not create Transport. Reason: java.io.IOException: Transport scheme NOT recognized: [vm]
alfresco-dev-upgrade-acs_1       |  2021-04-27 20:40:25,120  ERROR [component.jms.DefaultJmsMessageListenerContainer] [Camel (alfrescoCamelContext) thread #0 - JmsConsumer[acs-repo-transform-request]] Could not refresh JMS Connection for destination 'acs-repo-transform-request' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not create Transport. Reason: java.io.IOException: Transport scheme NOT recognized: [vm]
alfresco-dev-upgrade-acs_1       |  2021-04-27 20:40:25,145  ERROR [component.jms.DefaultJmsMessageListenerContainer] [Camel (alfrescoCamelContext) thread #1 - JmsConsumer[acs-repo-rendition-events]] Could not refresh JMS Connection for destination 'acs-repo-rendition-events' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not create Transport. Reason: java.io.IOException: Transport scheme NOT recognized: [vm]

**Comment by Fikili** [comment]
Well, I can access Repo and Share but I see the same error messages in log file even with Jeff's suggestion (messaging.subsystem.autoStart=false) mentioned in https://github.com/Alfresco/alfresco-sdk/issues/616. 
Anyone working on that?

**Comment by Scouil** [comment]
Independently of the error in the logs, the issue initially reported is probably because he tries to access share on port 8080 (http://my.ip:8080/share ) while it should now be accessed on port 8180

**Comment by ecarbenay** [comment]
I had the same issue and Jeff's suggestion in #616 did not solve it neither.
The way I solved this was to comment the scope in the following `activemq-all` dependency in the pom.xml of the project, like this : 
``` xml
        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>activemq-all</artifactId>
            <version>${activemq.version}</version>
            <!-- not only to be available for test scope - need to be available also for run -->
            <!-- <scope>test</scope> -->
        </dependency>
```

**Comment by andrea-ligios** [comment]
Thank you @ecarbenay , the scope is now `compile` by default on master and future releases
