### ISSUE TITLE
Alfresco 7.0.1 release

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#623]
Are there plans for a release to mirror the Alfresco 7.0.1 release? If not, will you publish specific artifact versions we should use?

**Comment by andrea-ligios** [comment]
AFAIK the plan should be to support Alfresco 7.1.0 in the next SDK 4.3 release. 

If this answers your question, please remember to close the issue, thank you

**Comment by binduwavell** [comment]
Thank you andrea-ligios... I do think we should push out an update for issue #612 sooner rather than later, at which point we could potentially bump to 7.0.1... I will as you suggest close this issue. Thanks again.

**Comment by andrea-ligios** [comment]
Thank you @binduwavell , we're on it (#612).

Also, I didn't mention that SDK 4.3 will use 7.1.0 as default but will test 7.0.1 on the 70-tests profiles.
