### ISSUE TITLE
Password disclose

### ISSUE THREAD

**Issue by ackbase** [Alfresco/alfresco-sdk#624]
https://github.com/Alfresco/alfresco-sdk/blob/master/pom.xml#L68

**Comment by andrea-ligios** [comment]
Thank you @ackbase .

That is the keystore's default password. 

It's there to have the whole thing working out of the box and in the tests.

You'll find it also in [many other projects](https://github.com/search?q=org%3AAlfresco+mp6yc0UD9e&type=code) across GitHub. 

For production usages, you should set your own keystore's password.

Cheers
