### ISSUE TITLE
Search Services 1.2 throw error 403 with ACS 7.2

### ISSUE THREAD

**Issue by andrea-ligios** [Alfresco/alfresco-sdk#635]
## Current Behavior
The Search Services 1.2 are too old to work properly with ACS 7.2, and are not configured to use Secure Communications.

Hence, the following error is thrown: 

```
ERROR (searcherExecutor-21-thread-1-processing-x:alfresco) [   x:alfresco] o.a.s.t.AbstractTracker Model tracking failed for core: archive
 org.alfresco.error.AlfrescoRuntimeException: 02220000 archive GetModelsDiff return status is 403
```

## Solution

To fix the problem, let's edit the `docker/docker-compose.yml` as follows.

1. Add the following Java options to ACS:

```
-Dsolr.secureComms=secret
-Dsolr.sharedSecret=secret
```

Example:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/11974750/160157670-477e6be9-feaf-490c-a410-4298c45a0505.png">

2. Change the Alfresco Search Services version from `1.2.0` to `2.0.3`, and add the following environment variables:
```
ALFRESCO_SECURE_COMMS: "secret"
JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
```

Example:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/11974750/160168234-3c48f953-6a8a-46d8-ac28-f7b54f16cc83.png">

**Comment by SanjayBandhniya** [comment]
It works. thanks

**Comment by eagleeye1984** [comment]
Nice, but I had to use SOLR_OPTS instead of JAVA_TOOL_OPTIONS.
![image](https://user-images.githubusercontent.com/13055882/194284057-5a26e2bd-de24-404d-ad9e-8bb24a152adc.png)
