### ISSUE TITLE
SDK 4.4 with Alfresco Enterprise 7.2.0

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#636]
The documentation for switching SDK 4.4 from community to enterprise: https://docs.alfresco.com/content-services/latest/develop/sdk/#workingwithenterprise

Suggests updating the `docker.acs.image` property to:

```xml
<docker.acs.image>alfresco/alfresco-content-repository</docker.acs.image>
```

However, it and the related `docker.share.image` should be changed to:

```xml
<docker.acs.image>quay.io/alfresco/alfresco-content-repository</docker.acs.image>
<docker.share.image>quay.io/alfresco/alfresco-share</docker.share.image>
```
Notice that `quay.io/` must be prefixed to the values.

In a way this is a documentation bug, but I suspect folks are more likely to find the solution here in the SDK issues. I hope the SDK team can either solve this problem in a more elegant way or can work with the docs team to make this update.

**Comment by jottley** [comment]
@binduwavell Can you also open an issue from the docs page?  The coordinated changes will help to get the changes addressed and may help to get us discussing how to better solve the issue.

**Comment by andrea-ligios** [comment]
Thank you @binduwavell, I confirm it's an error in the DOCS.

In the README.md it's fine, though: https://github.com/Alfresco/alfresco-sdk/blame/master/docs/advanced-topics/working-with-enterprise/README.md#L41

@jottley I suggest someone on our side opens the bug for DOCS, if not already done (cc @anxumalo )

**Comment by anxumalo** [comment]
@andrea-ligios @jottley I've opened [DOCS-6794](https://alfresco.atlassian.net/browse/DOCS-6794) to address the DOCS issue.

**Comment by anxumalo** [comment]
@andrea-ligios Can you please close this issue as **Done** - I don't have permission. Thanks
